== Preface

[.salutation]
To the Reader:

Most men will acknowledge that the primitive churches to whom Paul wrote his epistles,
exceeded in many respects the professors of Christianity in our present age;
and good grounds they have so to believe.
For the said apostle, in his epistles, told the Corinthians,
that their "`bodies were the temples of the Holy Spirit;`"^
footnote:[1 Corinthians 6:19]
he told the Ephesians that "`they were fellow-citizens with the saints,
and of the household of God;`"^
footnote:[Ephesians 2:19]
he told the Philippians that "`their citizenship was in heaven;`"^
footnote:[Philippians 3:20]
he told the Colossians that "`they were delivered from the power of darkness,
and translated into the kingdom of the dear Son of God;`"^
footnote:[Colossians 1:13]
he told the Hebrews that "`they were come to the city of the living God,
the heavenly Jerusalem.`"^
footnote:[Hebrews 12:22]
And Peter, in his general epistle to the churches,
told them that they were "`a chosen generation, a royal priesthood, a holy nation,
His own special people.`"^
footnote:[1 Peter 2:9]

But is this our state?
Can we say, from a discernible feeling, that the Holy Spirit of God dwells in us?
Or that our bodies are the temples in which we may behold His presence, feel His power,
and fear, worship, and serve Him?
Can we say that our citizenship is in heaven?
That we are translated into the kingdom of the dear Son of God,
and live under the scepter of His government?
That we have come to the heavenly Jerusalem,
where the great God is worshipped in Spirit and in truth?
Or, are we rather strangers to all these things,
and yet persuade ourselves that we are the people of God, and good Christians?

The primitive churches had the honorable name of saints;
we often can give ourselves no better name than "`miserable sinners;`"^
footnote:[The Book of Common Prayer, of the Church of England]
and what is the reason?
Most in the aforementioned churches, before their conversion, were but heathens;
they were not born of Christian parents nor trained up in the Christian faith,
as we think we are.
And after conversion they had but little preaching in comparison to what we now have;
neither were they so plentifully furnished with books as we are.

We cannot conclude that the kingdom of Christ that then appeared in power,
did (as the natural sun sometimes does) show itself in a morning,
and be seen no more all day; for the kingdom of Christ is an everlasting kingdom,
and the new covenant that was made with the house of Jacob is an everlasting covenant.
Neither may we conclude that God has withdrawn Himself from the children of men;
for He never forsakes us, unless we first forsake Him.

The apostles foresaw that there would be a falling away from the
grace in which many primitive Christians were established;
which soon after their decease came to pass.
But our preachers say, "`The dark night of apostasy is over,
and we live in gospel days again.`"
But if so, where are the fruits?
We may, I confess, hear gospel words;
but where is the gospel power by which believers come to be the sons of God,
and to bear His image in righteousness?
Why are we, who are called Christians,
not grown to the stature of those who were born Heathens
and brought up in blindness and ignorance?
Why are we not sanctified, and made a holy people, as well as they?
Why are our bodies not cleansed and made a habitation
for the eternal Spirit as theirs were?
Why is our citizenship not in heaven, or our lives at least more heavenly than they are?
The reason to me is this: we have not built upon the same foundation that they built upon.
For this we must understand--that the Heathen had not the Scriptures as we have,
and so could not set up a "`form of godliness`"^
footnote:[2 Timothy 3:5]
from them, as many have done since, made up of good words, calling it godliness,
and resting in outward performances,
without any true conversion or a sense of that inward life and power that
the primitive Christians came to feel and find in themselves through faith,
with the operation of the eternal quickening Spirit of Jesus Christ.

The Heathen, as well as others,
were men and women of God`'s creation (all nations being made of one blood),
and so had in themselves, as everyone has,^
footnote:[See John 1:9, Titus 2:11, Romans 1:19, 2:15, John 3:19,
John 16:8, Micah 6:8, Ecclesiastes 3:11.]
a seed of His kingdom
(a measure of His Spirit, a heavenly talent or mina)
along with the seed or spirit of the evil one.
Thus they knew good as well as bad; light as well as darkness;
something that reproved them for sin, as well as something that tempted them to sin.
And being, by the Apostle, turned from the darkness that was in them, to the light;^
footnote:[Acts 26:18]
from that which tempted them to sin, to that which convicted and reproved them for sin,
they cleaved thereunto, confided therein, and became followers thereof.
And by cleaving to the good, they were delivered from evil; by following Christ`'s light,
they came to be translated out of the kingdom of darkness,
and to have their citizenship in heaven, even while they were upon earth.

These built on a sure rock, a living foundation, on Christ as He was in all ages,
and still is--on His spiritual appearance as the light of the world,
and the life of righteousness.
And taking His eternal Spirit in themselves for their guide,
they turned away from whatever they were thereby convicted of and reproved for.
Thus Esau (or the first nature) came to be supplanted,
and He whose right it is to reign came to have the
rule in them and the government over them.
And as the darkness (that had eclipsed the brightness of
the Sun of righteousness in them) came to be removed,
they grew to have a clear discerning as to what was of God,
and also what was selfish and so to be denied;
and turning from every motion that was not of God, the body of sin was put to death,
their insides became cleansed, and the whole lump became leavened.
In this way, those who were carnal became spiritual,
and this made them "`God`'s own special people.`"^
footnote:[Titus 2:14; 1 Peter 2:9]

And did we but walk in their footsteps, we might rise to their attainment;
but if we build on words, and outward services without Spirit and life,
we can never arise.
For, as Paul said in another case--that though we speak with the tongues of men and angels,
but have not love,
we become as sounding brass or a clanging symbol--so I say in this case,
that though we hear the preaching of men and angels,
and live continually under the sound of good words,
but have no regard to that inward light which discovers the rising of evil motions,
and bestows power from God to turn from them, we can never mortify sin,
cleanse our souls, and become a holy people.
The work of sanctification is inward, and is to be effected by inward means.
Nothing but inward light can expel inward darkness;
nothing less than eternal life can deliver our souls from the power of death.

But ever since men came to be persuaded that though they sow tares,
they shall still reap wheat, and though they go down to the grave sinners,
they shall still rise saints,
and attain in another world what the primitive Christians attained in this world;
since then, I say, the citizenship of Christians has not been in heaven,
but in the earth.
They have walked in darkness and not in the light; the god of this world has been served,
and not the God of heaven.
And what future happiness this can produce, let the wise in heart judge.

[.signed-section-signature]
Hugh Turford
