== Walk in the Spirit

Paul, in his epistle to the Galatians, chapter 5:16, has this saying,
"`Walk in the Spirit, and you shall not fulfill the lust of the flesh.`"
And, in his epistle to the Romans, chapter 8:13, he has this saying,
"`If you live after the flesh, you shall die; but if you, through the Spirit,
put to death the deeds of the body, you shall live.`"
If ever scriptures were written for our learning, these scriptures were;
for much may be learned from them.
The end of preaching, both in our present age and in many ages past,
has been that the sons and daughters of men might thereby learn to deny, turn from,
and forsake every evil deed, and come to live a sober, righteous,
godly life in this present world,
that they might have peace with God in their own consciences here,
and eternal life hereafter.

Now to effect this great work,
in which thousands of laborers have for many years been employed,
the apostle gives this short exhortation:
"`Walk in the Spirit,`" affirming unto the Galatians, that if they walked in the Spirit,
they should not fulfill the lusts of the flesh; they should not yield to evil motions,
nor satisfy their carnal desires,
which is the only way to put to death the deeds of the body and cure all spiritual infirmities.
But this way of God`'s salvation has been so long rejected,
that few in our present age know _what_ this Spirit is,
_where_ they may become acquaintance with it, or _how_ they may walk in it.
Therefore, in order that our understanding may be opened in this weighty concern,
let us consider:

[.numbered]
1+++.+++ What Paul was, and how he came to be a gospel minister.

[.numbered]
2+++.+++ What the people were to whom he wrote his epistles.

[.numbered]
3+++.+++ What the apostle called flesh and spirit, and in what way we walk after them.

[.numbered]
4+++.+++ What we are to understand by his words "`die`" and "`live.`"

[.numbered]
5+++.+++ How we may, through the Spirit, put to death the deeds of the body.

By reading the Scriptures we may find, that Paul was an Israelite,
of the seed of Abraham, and brought up a scholar, well instructed in the law.
As to his religion, he was a Pharisee.
And what were the Pharisees?
Not a loose, profane people; but (in outward appearance) a very religious people,
zealous for their temple and its services, and for many other outward observations;
insomuch that Jesus said of them,
they "`made clean the outside of the cup and the platter;`"^
footnote:[Matthew 23:25; Luke 11:39]
which few now do.

But when the time drew near in which God would no
longer be worshipped in temples made with hands,
but would dwell in and be worshipped by sanctified hearts;
and when the laws that were written by that great prophet
Moses for the house of Israel to observe and walk in,
must no longer be a rule of righteousness,
but Jews and Gentiles must walk by a law proceeding
from the Spirit of God in the inward parts;
and when One greater than Moses had come,
proclaiming a kingdom at hand that consisted of a
more excellent righteousness than theirs,
testifying to the faces of those outward worshippers that,
notwithstanding their great zeal for the temple and its services,
they were but hypocrites and blind guides;--then,
the rulers of this people were greatly offended.
And having a bitter spirit within, notwithstanding their show of righteousness without,
they endeavored to stop the coming of that kingdom by murdering the Prince,
and imprisoning His subjects.
And in this persecution none was more active than Paul,
wasting the church of God beyond measure, and seeking to destroy it.

But in the height of his persecution, it was not man, but God,
who put a stop to his proceedings; showing him that it was not men, but Christ in men,
that he persecuted.
And indeed this was true; for had not Christ, by His eternal Spirit,
been in the men whom Paul was persecuting,
opening the eyes of their understandings to see the emptiness of all shadows,
and turning them from them, Paul would have had nothing to say to them.
But seeing that they inclined to worship God in Spirit,
and so neglected the temple-worship,
Paul looked upon them as a people not worthy to live.

But it pleased God to reveal in Paul the same Christ that he had persecuted in others;
and this revelation, or inward knowledge of Christ,
was the foundation of all Paul`'s knowledge in the mystery of godliness.
His future teachings were not from men, nor from books,
but from the operation of the eternal Spirit of Jesus in himself.
And keeping to the leading of that Spirit, he grew in grace; and as he grew in grace,
he grew in the knowledge of Christ.
Thus he did not go up to Jerusalem to receive instructions
or orders from those who were apostles before him,
but in the strength of the Lord, with a book of experience in his heart,
instead of a bible in his hand, he went into Arabia to preach the gospel to the Heathen.
And what foundation did he lay?
Not circumcision (which was the foundation of the Jewish religion),
nor John`'s water baptism (which has since became
the foundation of much of the Christian religion);
for he told the Corinthians that Christ did not send him to baptize,
but to preach the gospel,
and thanked God that he baptized no more of them than Crispus and Gaius,
and the household of Stephanus.
But as Paul`'s eyes had been opened to see the gift of God in himself,
so his work was to open the eyes of others,
that they might see the gift of God in themselves also.

The Heathen too had a "`light that shines in darkness`"^
footnote:[John 1:5]
and "`gives light to every man that comes into the world,`"^
footnote:[John 1:9]
which light showed them, as it shows us, what is right and what is wrong;
what is just and what is unjust;
though in their ignorance they might have paid it as little regard as many of us do now.

As the kingdom of heaven consists of righteousness,
Paul`'s work was to bring those people to a righteous and heavenly life.
And what better foundation could any man lay in order to bring about a righteous life,
than the light of Christ that shines within, manifesting every unrighteous action?
A guide that, when truly followed, leads unto God,
from whom all men depart by their unrighteous living.
This Paul experienced, and his experience made him an able minister,
capable of preaching without book or study,
and of affirming with confidence that the way to a righteous
life was to "`walk in the Spirit,`" or to keep to this Guide.

Thus I have shown how Paul came to be a gospel minister;
and now I shall show what the people were to whom he wrote his epistles.

The Romans and Galatians, before their conversion, were called Heathen,
for they knew not the true God, but worshipped dumb idols.
These were a people who lived, as too many do now, in all manner of ungodliness,
walking (as Paul told the Ephesians),
"`according to the prince of the power of the air.`"^
footnote:[Ephesians 2:20]
But being turned from their darkness, they became acquainted with this true light,
which never consented to any unrighteous action.
Yes, to this light many of the Heathen turned, taking it for their guide,
and confiding in it as a sure foundation;
and this is the true faith in Him who was "`given for a light to the Gentiles,`"^
footnote:[Isaiah 42:6; 49:6]
and is one in nature with the faith of Abraham.

This people became convinced (though many of us are
not) that after they had turned unto the Lord,
they then had a race to run.
And as it was from God and godliness that they had departed,
so to God and to godliness they had to return.
They did not content themselves (as too many of us do) with a Christian name,
but following this Leader, they walked in newness of life, and became "`sober, righteous,
and godly in the present age.`"^
footnote:[Titus 2:12]
This Paul commended, telling the Galatians that they ran well;
and we would run well also, if we ran the same race--growing,
from day to day more righteous, more upright, more honest, more faithful,
and more circumspect--which cannot be expected until we take their Guide for our Leader.

But the churches of Galatia, being at that time "`little children`"^
footnote:[Galatians 4:19]
(as Paul called them),
a people of small growth in the knowledge of the mystery of godliness,
were persuaded by some (as many are now) that a new and heavenly life was not enough;
but they must also be in the exercise of various forms of outward worship.
And as the Jews`' religion carried the greatest show of godliness,
they were persuaded to imitate their customs and observations.

But Paul,
having experienced the insufficiency of all outward services
to change a man`'s nature and bring him to a righteous life,
told the Galatians that, "`if they were circumcised,
Christ should profit them nothing.`"^
footnote:[Galatians 5:2]
That is, if they went from their inward Guide,
to rest upon outward performances (as the zealous Pharisees did),
then He that was given for a light and a leader,
would no longer be their light or their leader.
And, indeed, nothing is more evident!
For if Christ is _the way,_
and if walking by the Spirit is _the means_ by which
we must mortify sin and come to a righteous life,
then whoever goes from this way, whosoever slights this means,
has no more benefit from Christ, than a traveller has from a guide whom he has forsaken.
As Christ is a "`living-giving Spirit,`"^
footnote:[1 Corinthians 15:45]
it must be by following Him in His spiritual manifestations
that a righteous life is recovered.
Nothing less can change our natures and make us new creatures.
And until we are new creatures, our citizenship cannot be in heaven.

So the epistles of Paul were written to a people
who were on their journey from death to life.
They had come out of Egypt, but had not come to the promised land.
They were turned from their darkness, and had their faces set towards Zion,
but had not come to the New Jerusalem, the city of God.
They had begun in the Spirit, but had not come to the true worship in Spirit.
They had received Christ, but were not rooted and grounded in Christ.
And in order to perfect what was begun, the apostle put them upon nothing but this:
"`Walk in the Spirit;`" keep to your inward Guide, the light of righteousness,
for this alone can raise the sons and daughters of men from
their fall and bring them to a life of righteousness.

The third thing to be considered is this: what the apostle calls flesh and Spirit,
and how we may walk after them.

It is evident, that flesh and Spirit are both leaders,
otherwise we could not walk after them; and if these are leaders,
then our visible parts must be followers,
bringing forth in our words and deeds that which
has been conceived in our hearts or minds.
For every deed is first a thought, either good or evil.
Evil thoughts arise from that which Paul called flesh.
Good thoughts proceed from that which he called Spirit.
So then, flesh is a root of evil and Spirit is a spring of good,
and both are in ourselves.

From the flesh proceed all such motions as lead unto vice.
From the Spirit proceed all cautions and scruples we find in ourselves of yielding thereto,
along with all rebukes that follow when we have allowed the enemy to prevail over us.
These rebukes are in love to us, even as our rebukes are in love to our children,
that they may stand in awe and not offend.

As often as we yield to evil motions we give place to the devil;
and whoever yields to one evil motion, shall have another of the same kind.
The more often we yield, the more ground he has in us,
and the more power he comes to have over us.
And the only refuge a man has to fly to when evil motions arise,
is that gift in his own heart which Paul calls the Spirit;
for this will not consent to any evil deed.
Whoever keeps close to this, keeps close to God; they abide with their Guide,
and "`walk in the Spirit.`"

The converted Heathens walked by this rule.
They took the eternal Spirit of Christ in themselves for their guide.
They confided therein, and became followers thereof;
and it is this that brought them to be "`a holy nation, and a peculiar people.`"^
footnote:[1 Peter 2:9]
And we would be the same if we would but turn to this eternal Spirit in our own hearts,
and order all things according to its leading and guiding; for keeping to this,
we should not fulfill the deeds of the flesh.

The fourth thing to be considered is, what the Apostle intended by these words,
die and live.

Certainly, with the word die, he did not intend a cessation of their mortal lives,
for such a dying in the Lord`'s appointed time is common to all men.
They that live after the Spirit, as well as they who walk after the flesh,
must go down into the grave.
But the dying that the Apostle intended was a decay of our inward life,
a dying unto righteousness (which few in our present age take notice of)--such a dying
as the first man Adam died when he fell from the government of the eternal Spirit,
which was man`'s first state; or such a dying as the house of Israel died,
when they clung to outward observations, and disregarded justice, mercy,
and a humble walking with their God.

Now such as walk after the flesh, living in the practice of any known sin,
depart further from God, and come to have less life, less light, less grace,
less fear of offending God and injuring their neighbors, as we may see by men`'s conduct.
And this decrease is a dying unto righteousness.

And as they who live after the flesh have less life, less light, less grace,
and less fear; so those who walk after the Spirit, doing such things as are upright,
honest, and of good report, from the righteous Seed sown in their own hearts,
find an increase.
These come to have more life, more light, more grace,
more fear of offending God or their neighbor.
And this increase is a living unto righteousness.
As the one goes further from, so the other draws nearer to, the kingdom of heaven.

Had we not in ourselves Spirit as well as flesh, light as well as darkness,
a Conductor in the way of life and salvation as well as a leader in the paths of destruction,
we might lay all the blame for loss of life and the
calamities of sin entirely upon Adam`'s score,
or charge them exclusively to the account of the wicked one,
from whom all wicked motions proceed.
But Paul was an expert doctor in divinity.
He knew what corrupted the sons and daughters of men,
and from where all the ungodliness that is in the world does arise.
And to cleanse, to purge, to purify, to make Heathens become sound Christians,
and sinners become saints, he describes no other means but this, "`Walk in the Spirit.`"
For as we keep to this Spirit,
we shall learn (as the converted Heathens did) not only to deny ungodliness,
but also to live godly in this present world.

But if we make no use of the aforesaid means,
but rest in outward performances (as the zealous Pharisees did),
accounting ourselves righteous because of a supposed right form of godliness, then,
though we have as great a zeal for our forms and practices
as ever Paul had for the religion of the Jews,
it will profit us no more than circumcision would have profited the Galatians.

We have had much preaching and teaching.
The joys of heaven have been promised to those who do well;
the torments of hell have been threatened to those who do evil.
But have all these promises and threatenings made us a holy nation and special people,
exceeding all others in the fruits of the Spirit?
Have all the exhortations that we have received enabled us to mortify the body of sin,
which is the cause of ungodliness?
Are we thereby translated, as the Heathen were,
out of the region of darkness into the kingdom of the dear Son of God,
so as to have our citizenship in heaven even while our bodies are on earth?
Can we truly say that, "`Old things are done away,`"^
footnote:[2 Corinthians 5:17]
all exalted thoughts, all covetous inclinations, all wrath and bitterness;
and that these new things have come in their place: humility, meekness, temperance,
self-denial, with unfeigned love to God and our neighbor?
Can we say,
'`There was a time in which sin had such dominion over us that
we could not refrain from fulfilling the lusts of the flesh,
but now we are so governed by the eternal Spirit that we must be temperate,
we must be sober and vigilant, we must be just, upright,
and faithful in word and deed.`' If this is really our state, then we are,
as the primitive Christians were at their full attainments,
dead unto sin and alive unto righteousness,
having been built upon the same rock as they were.
But if we have not come to this, it would be wisdom to turn to the Lord, as they did,
and build on the same foundation that they built upon, namely,
"`The true Light that enlightens every man that comes into the world,`"^
footnote:[John 1:9]
that we may come to be acquainted with the eternal Spirit, as they were,
and have a Guide and Leader in the paths of godliness, as they had;
for it is by and through the power of the eternal Spirit of Jesus
in our own hearts that our corruptions must be purged out,
and our inside made clean.
For indeed, as our walking after the flesh made all wounds,
so our walking after the Spirit must heal all wounds.
As our living after the flesh caused the growth of our unrighteousness,
so by walking after the Spirit we mortify sin, and recover a life of righteousness.

Paul spoke from a good understanding when he told the Romans,
"`That which may be known of God is manifest within.`"^
footnote:[Romans 1:19]
It is there he had his knowledge in the mysteries of godliness; whatever he preached,
whatever he wrote, the spring was in himself.
He knew no more of the operation of inward and spiritual grace than any other man,
until he came to have his eyes turned inward, and to walk in the Spirit;
and so he recommended to the churches what he himself had experienced.

Many can talk of redemption, justification, sanctification, and salvation by Christ,
but he is a Christian who witnesses these things wrought in himself.
Such may properly be called learned men; for they know what it is to rise,
what it is to die, and what it is to live, what they are redeemed and saved from,
and by what means.

The fifth thing to be considered is, how the sons and daughters of men may,
through the Spirit, put to death the deeds of the body.

But first, let us consider which deeds of the body are to be put to death,
which in general are these: As an evil spirit in man is the root of all evil deeds,
so _every deed that proceeds from that root_ is to be put to death.
And nothing can manifest such deeds, giving us a true sight of their nature and rise,
but the Spirit of the Lord, or the Light of righteousness in our own hearts,
as it comes to shine in brightness.

In order to know which deeds are to be mortified in all of our efforts and undertakings,
let us consider our aim therein.
If we have nothing in our eye but righteousness, equity, honesty, and love,
we may proceed with safety; but if self is the moving cause,
if we do not have an eye to our neighbor`'s good as well as our own,
then pretend what we will, such deeds proceed from an evil root and are to be denied;
and in our denying them, they come to be mortified.
And what can manifest our aim in every action?
Not books nor preachers, but only the Spirit of the Lord, who is an inward light.

Now we do not find that Paul directly charged the
Galatians with any manner of loose living,
but only with their "`observing days and times;`" and what harm could there be in that?

Though the Galatians might have seen none, yet Paul saw much,
otherwise he would not have asked them,
'`Who had bewitched them?`' For they had begun in the Spirit;
they had walked for a season after an inward Guide,
which is the only leader to such a life of righteousness as the
Lord (in all ages) has required of the sons and daughters of men.
This was not a form of godliness without life, but truth in their inward parts;
for if we have truth in our hearts, righteousness will be performed by our hands.
And to this Paul knew they could never come by imitating an outward worship,
much less by observing days and times, and so counted such things deeds of the flesh,
reasoning with them in this way: "`Are you so foolish, having begun in the Spirit,
are you now being perfected by the flesh?`"^
footnote:[Galatians 3:3]
Which is to say, '`Are you so void of understanding?
Having begun to walk in newness of life,
do you expect to come to such perfection as to have
your citizenship in heaven while living on the earth,
by going back to the performance of outward services?`' "`This persuasion,`" he said,
"`does not come from Him who calls you;`"^
footnote:[Galatians 5:8]
and if it was not from God, it must be from the old deceiver.
And truly, many have since been deceived in like manner,
persuading themselves that godliness consists in
that which is called (but is not) true devotion,
and yet live in pride, covetousness, envy,
and many other things which are clearly deeds of the flesh,
never coming so far as to be translated out of the kingdom of darkness,
nor to live under the government of the eternal Spirit.

Man`'s fall was not from any outward religion or form of godliness,
but from a life of righteousness.
Man fell from a state in which husband, wife, parents, children, masters, servants,
and all other relations, would have known their place and duty, and been found therein;
from a state in which all created things which God has given for man`'s use,
would have been rightly used, and none of them, through excess, wasted or abused;
from a state in which truth would have been found in all our words,
and equity in all of our deeds;
from a state in which the will of God would have
been done on earth as it is done in heaven,
and the great God glorified by us, and not dishonored.
From this state, through the entrance and growth of sin,
the sons and daughters of men have departed; and to this state the primitive Christians,
through the mortification of sin, returned.

This was the life that the first Adam lost.
This is the life that the second Adam came to recover.
As many as have the Spirit of Christ, and become true followers thereof,
rise from this fall, return unto God, live under His government,
and become witnesses of this heavenly life restored.

When I have looked upon the Book of Common Prayer,
I have found the words therein as good as could be collected from the Scriptures,
with a requirement that not one man be admitted into the church
without promising on their behalf as much as I have mentioned.
Were these promises truly performed, we would indeed be a holy nation,
in no way behind the chiefest of saints; for those who rose highest,
rose no higher than to "`walk in God`'s commands all the days of their lives.`"^
footnote:[A Catechism; 1662 Book of Common Prayer.]

But it is rare to find one man that performs this covenant, and the reason is this:
we say the Scriptures are our rule, but we heed not their counsel.
Paul`'s advice is not followed, we do not "`walk in the Spirit;`" which if we did,
the light of righteousness in our own hearts would
show us the risings of every evil motion,
and what they lead to.
This is the time to "`forsake the devil and all his works,
with all worldly vanities and sinful lusts:`"^
footnote:[A Catechism; 1662 Book of Common Prayer.]
for if we deny evil motions, we shall never be found in evil actions;
and until we depart from evil, we cannot do the things that are good.^
footnote:[Isaiah 1:16-17]
Sin must be put to death before we can live a life of righteousness.
The works of the devil must be denied,
before the commands of our God can be walked in even one day,
much less all the days of our lives.

And this Paul experienced, which made him say with great confidence,
"`Walk in the Spirit, and you shall not fulfill the lust of the flesh.`"
For if we deny and turn from every motion that the light
of Christ in our own hearts shows us to be evil,
we shall not fulfill them, but instead put to death the root from which they arise;
for that which is not fed, in time comes to die.

By this the converted Heathen came to be a holy nation.
This is the way to become citizens of the New Jerusalem.
By this means the Colossians were (and we may be)
translated into the kingdom of the dear Son of God,
to live under His government.
This is the kingdom that John the Baptist proclaimed to be then at hand.
This is the kingdom for which the disciples of Christ were instructed to pray.
This is the kingdom that consists of righteousness and stands in power.
This is the kingdom that all believers are to seek first;
for under the government of the eternal Spirit of Jesus in their hearts,
the sons and daughters of men are limited from doing any unrighteous thing.

Many of the present professors of Christianity are persuaded that,
though they remain unrighteous in their lives,
yet being in the exercise of something called religion,
it shall go well with them in the end.
But the living Lord does not take notice what religion we profess,
but what leader we follow; for let our religion be what it will,
if we live after the flesh, we shall die.
And, though little appears that is considered religion, if we walk after the Spirit,
if our citizenship is in heaven,
if truth is in our mouths and righteousness performed by our hands, we shall live.

But who is capable of walking after the Spirit, and through the Spirit,
of putting to death the deeds of the body?

There are many, even amongst those who bear the name of Christians, who,
through a perseverance in evil-doing, have become dead in sin,
having no sense or feeling of anything in themselves that is of God; and such as these,
who have no acquaintance with the Spirit, certainly cannot "`walk after the Spirit.`"

There are others who are not dead, but dying.
They have both sense and feeling;
they have that in themselves that would lead them to better things than they practice,
but pay it little or no regard.
They do not take it for their guide.
And while they disregard that light within them which manifests the deeds of the body,
they can in no way put them to death.

But some may be found who are weary of their sins and burdened with their iniquities,
having in themselves a hunger and thirst after righteousness.
Such as these are a living people, and capable, through the Spirit,
of putting to death the deeds of the body.

I am convinced that in our present age, many have been awakened from the sleep of sin,
and have found in themselves a true hunger and thirst after righteousness;
but having been awakened by an outward ministry,
from that they have expected to have their hunger and thirst satisfied.

Many may be awakened, but not be quickened,^
footnote:[i.e. made alive]
by an outward ministry.
"`It is,`" as Jesus said,
"`the Spirit that gives life;`" and what can raise life but that which gives life?
What can satisfy a soul that thirsts after righteousness,
but that which in truth is the very Spring of righteousness?
It is in ourselves that the well is to be found, where those who drink shall never thirst.
Only there is the fountain that springs up unto everlasting life.

As the kingdom of heaven stands not in words but in power, so it is not words,
but the power of God that can put to death the deeds of the body, change our nature,
and make us new creatures.
Could words fill us with righteousness, justice, truth, equity, and faithfulness,
we would have long since been a holy nation; for there has been no lack of words,
but there is still a great lack of righteousness and faithfulness.

If good words could bring hearers to a righteous life,
then instead of saying,"`Walk in the Spirit,`" Paul would have said to the Galatians,
"`Hearken to your minister!`"
He would have had no need to commend them to an inward Guide.^
footnote:[Acts 20:32]
But Paul`'s experience demonstrated unto him, that it was not by the hearing of words,
but through an obedience to the law of the Spirit,
that he put to death the deeds of the body, and came to lead a righteous life.
And what he found to be effectual in himself, that he recommended to the churches.

Words, though ever so numerous, may be easily forgotten; they do not abide.
But the eternal Spirit abides,
and is that "`teacher who that can never be removed into a corner.`"^
footnote:[Isaiah 30:20]
The use of words in the work of salvation is to awaken those who are asleep in sin,
and to turn them (as Paul turned the Heathen)^
footnote:[Acts 26:18]
to an inward Guide; and also for admonition, while they are on their journey,
to keep to their Guide.

Had such who hungered and thirsted after righteousness
pressed after what they hungered for;
had they acquainted themselves with the eternal Spirit who begot those desires,
and followed His leading, He would have rooted out all pride and selfishness.
He would have brought them to a humble, lowly, meek, patient, peaceable frame,
and to do what was right at all times.
This indeed would have removed their burden and given them rest and peace.

And if we would be as the primitive Christians were, we must begin where they did.
We must turn to the light of righteousness in our own hearts,
and walk in that light until we become children of the light.
We must walk in the just man`'s path by the shining thereof,^
footnote:[Proverbs 4:18]
till righteousness becomes our center.
This made the primitive Christians a godly people indeed; by this they prospered,
otherwise the blind and ignorant Heathens could never have come to be
fellow-citizens with saints and of the household of God.

Paul was not a settled minister at any one place, they heard him but seldom;
but they heard the voice of the eternal Spirit as often
as they transgressed the covenant of light and life.
It is to this voice that Christians must incline their ear;
for under the new covenant God speaks to His people by His Son,
through the eternal Spirit in their hearts.

The first step to a life of righteousness is to acquaint ourselves with
the gift of grace in our own hearts that reproves us for unrighteousness;^
footnote:[Titus 2:11]
for until we come to this, we are strangers to the foundation of a godly life.
For all building, all journeying, all rising, all approaching near to the kingdom of God,
depends upon our denying, turning from,
and utterly forsaking what the light of righteousness in our own heart convicts us of,
and reproves us for; for by such denials the deeds of the body are put to death.
As we make this our concern, and are faithful therein, His light shines more and more;
and the more light we have, the greater discovery it makes of what is evil,
what is to be denied, turned from, and forsaken.
And so guiding our steps by this, we build on the true foundation,
we walk in the living way, we grow in grace and the knowledge of Christ,
and draw nearer and nearer to His kingdom and righteous government;
and His power is felt in a righteous life.

This was the advice of Christ: "`Strive to enter in at the strait gate;`" testifying,
that the way to eternal life was narrow and difficult.
What is this strait gate, and narrow way?
It is not self-interest, nor yet self-righteousness.
Self-interest is the root of all covetous practices, dishonest dealings,
and unjust actions.
Self-righteousness is the root of all formality and contention about religion,
of which there has been (and still is) too much in the Christian world,
persecuting one another, even as the unconverted Heathens did the primitive converts.

Neither of these paths leads to that kingdom that
consists of righteousness and peace in the Holy Spirit.
Had the newly-converted Heathen walked in these paths,
they would never have become a holy nation;
for their citizenship would have been in the earth, and not in heaven.
But the strait gate, and narrow way, that leads to a righteous life,
is _self-denial_--a denying of everything that proceeds from the evil root,
from the smallest concern to weightiest desire;
which nothing can manifest but an inward light, shining in brightness.
But with sorrow we may say, it is rare to find even one amongst many,
who lives in the practice of what he himself acknowledges to be right.
Who will not confess that to speak the truth on all occasions is a right thing?
Who will not allow that to keep our word, though it be to our hurt, is an honest thing?
Who will not grant, that to do unto all men as we would have them do unto us,
is a just thing?
Yet how few live in the practice of these things?
And if we do not live in the practice of what we know to be right,
what does our knowledge profit us?
We may keep moving, as Israel did in the wilderness,
but unless we walk in the narrow way, we can never come to a righteous life.

And so, if we do not willfully shut our eyes,
we may plainly see that the way to a righteous life,
is to "`walk in the Spirit,`" to come under the government of our inward Guide,
to deny and turn from all that the light of righteousness
in our own hearts manifests to be unrighteous,
unjust, or dishonest.
And in turning from evil, we turn to the One who is good; in forsaking vice,
we seek to be filled with virtue; in dying unto sin,
we are made alive unto righteousness, and so truth, purity,
and love come to have dominion in our hearts.
To such as these, Paul said,
"`There is no condemnation;`" for they have "`the answer of a good conscience,`"^
footnote:[1 Peter 3:21]
peace with God, and peace in themselves--peace while they are here,
and peace when they go hence.
