== Considerations on the Previous Discourse

Man was created (as many will acknowledge) to glorify God, and to do His will on earth.
And in order that man might be capable of serving his Creator according to His will,
God gave him a measure of His good Spirit for an instructor;
so that there was much of God in man,
according as he was first created--much humility and meekness,
much truth and faithfulness, much heavenly wisdom and understanding.

This eternal Spirit was to be man`'s head and leader,
man`'s guide and instructor in the paths of righteousness.
On this Spirit man was to fix his eye; to this Spirit man was to incline his ear;
by this Spirit man was to be governed; and so following this guide, this leader,
and this instructor,
man would have been capable of governing both himself
and the creation over which he was made lord,
according to the will of God.

Did mankind live under the government of this eternal Spirit,
we would all bear the image of God.
We would be all godly, humble, lowly, meek, merciful, patient, peaceable, upright,
and faithful; right in all our ways, and just in all our works.
But not keeping with this guide, man disobeys the command of his Maker.
And by yielding himself a servant to another master,
so another spirit enters which is as contrary in nature as darkness is to light.
And as many as follow this leader serve not the God of heaven, but the god of this world;
for every man is a servant to whom he obeys.^
footnote:[Romans 6:16]

Now we, being the offspring of Adam in his fallen state, bear his likeness.^
footnote:[Genesis 5:3]
We have in ourselves both good and evil, a Seed of grace, and a seed of sin.
These, in Scripture, are called light and darkness, flesh and spirit,
the old man and new man,
according to the growth of the seeds in us and the
dominion that they come to have over us.
For as there is a difference between a seed and an herb, a plant and a tree,
a child and a man, so there are differences in grace and in sin;
according to their growth in us, so is their strength felt by us,
and the names given in Scripture correspond thereto.

For though we all have a seed of sin in us, yet we are not mastered by it,
nor fully enslaved to it, just as soon as we are born.
It must have time to spring and grow in us before it comes to have dominion over us.
And I may say the same of the Seed of grace, for it is also of a growing nature;
otherwise the kingdom of heaven (or government of Christ in the hearts
of His people) would not have been compared to a mustard seed,
which, though small when it is sown, through its springing and growth,
comes to be of great stature.

There are indeed many in the world who are notoriously wicked,
and who would appear much more wicked were they not limited by an outward law.
These were not so born; it is the growth of sin, and its increasing dominion over men,
that makes them notoriously wicked.
For the seed of sin, as it comes to full growth in any of the sons and daughters of men,
converts them into its own nature,
by which they come to be habitually active in wickedness.

This was the devil`'s aim in Adam`'s fall, but as his design was not then fully effected,
he has followed the sons and daughters of men in
all ages of the world (and does so at this day),
putting evil motions in their minds along with various temptations,
displaying false colors,
and painting forbidden things with a beautiful gloss that is more
attractive to fallen man than the paths of righteousness.
All of his evil motions, temptations, baits, snares, lures, and false colors,
are to effect his first design--that being ensnared and led away,
we might forget God and cause Him to take His Holy Spirit from us.
Until then, the god of this world can call no man his own; we may be his captives,
but he has not complete dominion over us.

In our present age, to speak of God`'s light within, law within, Spirit within,
Christ within, etc., is a matter of scoffing to some, and is little regarded by many.
But whether they know it or not, I must tell them,
they scoff and slight the chiefest treasure that ever was given to the soul of any man.
They despise the heavenly talent that God has given to every man to improve,
in order to effect their rising from their fall and returning to their native country,
to live under the government of the eternal Spirit.
Whosoever is without Spirit and light within, is without God in the world.
Take away this treasure, and we shall have nothing in us that is good;
we shall be left quite graceless.

We read of Jacob and Esau, who were living figures of these two seeds in man,
how they struggled while they were in the womb of Rebecca.
And as there was a struggling between the seed of two nations in the womb of Rebecca,
so there is a struggling between the seed of two kingdoms in every man,
as to which shall rise to rule in us, and have the whole dominion over us.

As we are born into the world, we are all innocent.
Though we have a seed of sin in us,
we are not actual sinners until we yield to some sinful motion that proceeds from it.
This the devil knows (though many are of a different opinion), and so,
in order that the seed he has sown may spring up and grow,
and that an evil spirit may come to have the rule in us, he early begins his struggle,
before we well know our right hand from our left.

Now, where evil is not kept down by careful parents or guardians,
it quickly becomes head, and such may say (as many do today),
"`There is no good thing in us.`"
For, through the speedy growth of that which is evil,
such as these never have any acquaintance with that which is good,
except for inward rebukes, which few will acknowledge to be from God.
For even as weeds left to grow in a garden do overshadow and keep down the herbs,
so vice suppresses virtue,
and makes God`'s creation such strangers to their Creator that,
though "`in Him they live, move, and have their being,`"^
footnote:[Acts 17:28]
yet are they without any sense or feeling of His presence.

And even as all evil motions that lead into sin, all baits, snares, and lures,
that we meet with in the course of our lives,
are the strugglings and strivings of the evil seed;
so all the calls that we find in ourselves for righteousness, honesty, truth,
and faithfulness, with all inward checks, rebukes, and convictions,
are the strugglings and strivings of the good Seed.
And if these things are hearkened to, obeyed, followed after, and lived in,
they keep down the growth of evil; so that, though we have a root of sin in us,
it remains powerless; it does not rise and come to reign over us.

For this reason,
parents and guardians ought to be much concerned in the suppressing of sin,
in order to allow for the growth of grace.
For as the wicked one takes the advantage of our childhood,
to make us commit evil before we have any acquaintance with that which is good;
parents and guardians (like faithful weeders) should watch, suppress, keep down,
and use all endeavors to root out vice as soon as it appears, until grace grows,
and a right Spirit comes to reign in them, and have the rule over them.

But this is our present state:
just as Esau by his struggling came to be the first-born in days past, even so iniquity,
through the early rising of the subtle serpent, is the first-born still.
And though most parents in the Christian world are concerned to provide weeders at times,
yet few weeds do they actually root up, and many parents none at all;
by which great neglect most children come to be wild, stubborn, self-willed,
disobedient to parents, and very ungodly in their lives.
But the ground of all ungodliness is the growth of that seed which the wicked one sowed.
And how may wickedness be brought down when it has already sprouted?
Not by parents or guardians or even by preachers;
but as it was Jacob that supplanted Esau, so it must be grace that supplants sin.
For we see that, notwithstanding all preaching,
there is far more pride and haughtiness than humility and meekness,
more deceptive dealings and evil practices than self-denial,
more seeking the world and its vanities than the kingdom of heaven and its righteousness.
And it will always be so while the firstborn is uppermost.

And if we would have the firstborn supplanted;
if we would have that which strives to deprive us of life, light, and grace,
and all goodness, made powerless;
if we would have that suppressed which continually labors
to make us servants to sin and bond-slaves to Satan;
if we would see the death of that which makes us
incapable of glorifying God in our lives;
if we would be (as the primitive Christians were) delivered from the power
of darkness and translated into the kingdom of the dear Son of God,
to live under the government of His eternal Spirit,
which was man`'s first state--then let us consider
how that which now hinders us came to arise,
and by what means it may be brought down.

I have said, and say again, that it is not the mere indwelling,
but the growth and reign of the evil seed that makes the sons and daughters of men proud,
haughty, high-minded, envious, cruel, merciless, fraudulent, and ungodly;
darkening their understandings,
and making them strangers to the gift of God in themselves.
And the growth of this evil seed lies in our often
yielding to such evil motions as proceed from it.
This the subtle serpent knows, and we may know it also,
from the manifold temptations we feel towards evil,
especially where our enemy has found them to be effectual.

Who has ever yielded to any evil motion, committing sin and taking pleasure therein,
and then has not been tempted again to do the same thing?
Or who does not know, that the more often we yield to any temptation,
the stronger our temptations are, and the harder to be denied?
And with every yielding, there sin rises up, and comes to have more power over us.

Therefore, if it is by our yielding to evil motions that the evil spirit rises,
and comes to have power over us,
it must be by denying evil motions that he comes to be supplanted,
and made powerless in us.

Whosoever will be a follower of Christ, must first learn to deny himself.
We must turn from whatsoever the eternal light in our own hearts shows us to be selfish,
though this may seem ever so much to our disadvantage; and by thus denying ourselves,
we shall abundantly deny the author of all evil motions.

Pride, pleasure, and selfish gain, are baits that have caught many.
These, with many other such things, must be denied and turned from,
if we will be followers of Christ in a life of righteousness.
And by continued denials we shall find that the root of iniquity withers,
and grace grows; sinful motions diminish, and heavenly desires increase;
the small seed will become the tallest of herbs;
and the lump of meal comes to be one in nature with the heavenly leaven.

But this denial must be while the dragon is still in the shell, that is,
while sin is still in the motion, before it comes to be action;
for sinful motions may be turned from, but sinful actions are past recall.
And what can show us the rising of evil motions?
Preachers cannot; books cannot;
nothing that is without can effectually show us what is within.
It must be an inward light; it must be the candle of the Lord,
the eternal Spirit that was in the beginning given unto man for an instructor.

We read in Scripture of good men, faithful men, self-denying men,
even when there were no preachers or books;
and who was their teacher but the eternal Spirit?
What guide did they have but the light of righteousness in their own hearts?
And if our present preachers would make it their
concern to turn people`'s hearts to this inward Guide,^
footnote:[See Acts 26:18, and Acts 20:32]
and to become faithful followers thereof, we would have more good men, faithful men,
and self-denying men, than can now be found.

Neither men nor angels could give better advice to
a people who have been turned to this inward light,
than that which Paul gave to the Galatians when he exhorted them to "`Walk
in the Spirit;`" for if we are not guided by a right Spirit,
we can never lead a righteous life.

But even as the seed of sin grows and waxes strong in us by our yielding to evil motions,
so the Seed of grace grows and waxes strong in us by the denying of evil motions.
The putting off of the old man is the putting on of the new,
and it is the new man that makes us new creatures,
and to bring forth a new and heavenly life.

If we do not learn to deny evil motions, and to live in the continual exercise thereof,
then (though we hear preachers all the days of our
lives) we shall be but like the door on its hinges,
or like Israel in the wilderness, often moving back and forth,
yet falling just as short of a righteous life,
as the first generation that came out of Egypt fell short of the Promised Land.

We cannot abide in the path of the righteous,
until His light shines with such brightness that we can
see the rising of all evil motions at a distance.
For as grace comes to be uppermost in us, the root of iniquity will be lowermost.
As the one comes to abide before our faces, the other will remain behind our backs.
For where do pride and haughtiness, contention and strife, fraud and deceit,
oppression and cruelty come from, but the author of all wickedness?
But where the flesh and its affections are crucified, such things are not to be found.
And, let us profess what religion we will,
while we live in the practice of any such evil, we keep alive what ought to be slain.

Where an evil spirit is uppermost, men know no limits; their ears, eyes, tongues, hands,
and feet, are all at liberty.
They are free to hear evil reports, to behold vanity, to speak proudly, rashly,
unadvisedly, and deceitfully, to do violence, to take bribes, and to go where they wish.
But where a right Spirit rules, every member of the body is brought under His government.
The ear is turned from fables and the eye from beholding vanity.
They cannot (as too many do), cover, disguise, and lie, to accomplish self-ends.
Vain communication is not allowed to come out of their mouths,
and their hands are kept from doing any wrong.
The paths of impurity they cannot walk in, but are lovers of righteousness,
and haters of iniquity both in themselves and in others.
And to this state we might all come,
by denying such motions as the light of righteousness
in our own hearts manifests to be evil.

And now my advice to all professors of Christianity is this:
that instead of contending about outward forms of godliness,
you take heed to that gift in yourselves which leads unto godliness;
instead of searching the Scriptures for a right form or practice,
you seek to live under the government of a right Spirit;
for then you will be delivered from the power of darkness,
and return to Zion the city of God, and to the New Jerusalem,
where God is known and truly worshipped.

There is one thing more I would have the reader to consider, which is this:
Though every man that comes into the world is attended with two spirits,
yet he can have but one Lord; and he is Lord that has the whole rule over you.

The right of government in all men belongs to the eternal
Spirit that was with the Father before the world began.
This, in Scripture, is called the Spirit of Christ;
for in Jesus (the second Adam) no other spirit dwelt.
Christ was not attended with two spirits, as the offspring of fallen Adam are.
He did not have in himself light and darkness, good and evil,
a seed of grace and a seed of sin; but as the Scripture says, He was "`full of grace,
and full of truth.`"^
footnote:[John 1:14]
In Him was life, even the life that the first Adam lost, as a spring of righteousness;
and this life He retained,
and so kept out the evil spirit who is the author of all wickedness,
though His temptations far exceeded those of Eve.
And though He lived many years on earth, and met with many provocations,
yet in the whole course of His life He fulfilled all righteousness
and accomplished the will of God on earth.

Now, the Seed of grace in every man, is one in nature with the fulness that dwelt in Him.
And as this Seed springs up in any of us, and grows in strength and stature,
it makes us conformable to His image.
Thus the more grace we have, the more humble, meek, and loving we will be.
The more light we have,
the greater discoveries it will make of what is amiss in ourselves and in others.
The more truth dwells within, the less evil and impurity will be manifested without.

And as we walk in the light, we shall grow in grace, and "`add to our faith virtue,
knowledge, temperance, patience, godliness, brotherly kindness, and love;`"^
footnote:[2 Peter 1:5-7]
by which, as Peter said,
"`an entrance will be ministered unto us abundantly
into the everlasting kingdom of Christ.`"^
footnote:[2 Peter 1:11]
A right Spirit will come to be exalted in us,
and to have the only rule and government over us;
and under the government of a right Spirit,
we shall bring forth fruit that is acceptable in the sight of God.

Now the prince of darkness, being an enemy to all righteousness,
uses all endeavors to blind the eyes of our understanding and keep us
strangers to this righteous Seed (which is the spring of all grace and
virtue within) that he may draw us away from God and godliness.
So that,
just as those who walk in the light of the Lord add virtue
to virtue until they are filled with His righteousness,
so those who follow the leadings of an evil spirit add vice
to vice until they come to be filled with wickedness.
These also have but one lord,
for the prince of the power of darkness has the whole rule over them.
And these two states in Scripture are called _life_ and _death._

I believe it can be said that every man, as he comes into the world,
has life and salvation before him, and death and destruction behind him,
and both are at a distance from him.
He has also a good Spirit to conduct him in the way of life and salvation,
and an evil spirit waits to lead him in paths of death and destruction;
and though these are in him, yet most men are strangers to both.
Now the preaching of the gospel was (and still ought to be) for the opening of
such blind eyes to see the workings and leadings of these two spirits within,
that men might turn from the evil and become followers of that which is good,
that He whose right it is might come to have the rule in them and over them.

And certain I am, that though many are ignorant of these things,
still there are many who have had some sight, some sense,
and some feeling of the eternal Spirit of Jesus.
They have the knowledge of something in themselves that calls for truth and righteousness;
and were they to keep to this, they would follow a right Guide,
and the Seed of grace would grow, truth and faithfulness would grow, knowledge,
temperance, patience, brotherly-kindness, and love would grow;
and they would find in themselves that an entrance into the kingdom
of Christ would be abundantly administered.

But while the evil spirit remains unmortified, self stands in our way,
and in order to accomplish our selfish ends, an equal balance is not kept,
justice is not done, equity is not performed, promises are not kept,
undertakings are not faithfully managed,
and the fashions and customs of this sinful world are not forsaken.
This hinders the growth of the righteous Seed;
for as there was no bringing down of the Canaanites while the "`accursed thing`"^
footnote:[See Joshua 7]
was still in the camp,
so there is no bringing down the strength of sin
while we have more regard to self than to our Savior.
That which manifests self is light,^
footnote:[Ephesians 5:13]
and by it we may see where every evil motion leads; so that walking in the light,
we walk in the way of God`'s salvation.

But some may say of this eternal life (as the wicked men and sons of Belial said of Saul,
the chosen of the Lord)--"`How shall this man save us?`"^
footnote:[1 Samuel 10:1]
'`What advantage could there be in taking heed to this light?
We find in ourselves rebukes for sin,
but we find nothing in ourselves to save us from sin!`'

To such as these I have this to say: Christ was given to the Gentiles for a light^
footnote:[Isaiah 42:6, 49:6]
and for a leader.^
footnote:[Isaiah 54:4]
While we are in the nature of the Gentiles, while we walk after the flesh;
while we follow evil motions, we are departed from God,
we are aliens from the commonwealth of Israel and strangers
to the new covenant that God made with the house of Jacob.
In this state we cannot know Christ the Savior of
the world in any way other than a reprover;
but these reproofs, being "`reproofs of instruction, are the way to life,`"^
footnote:[Proverbs 6:23]
even to that life that the first Adam lost through transgression.

For if we turn at these reproofs from the things
we are reproved for--whether it be idle communication,
intemperate living, pride, passion,
or any other vice that the evil spirit of this world leads unto--and follow after righteousness,
then the rebukes will cease, and our reprover will become our leader.
Then that which was behind our backs, will be before our faces;
and that which desired to lead us, will now seek to pursue us, as Pharaoh pursued Israel,
to bring us back to our old manner of living again--and
_then_ we shall find Christ to be our Savior.
For as many as followed Saul in the beginning of his reign
saw how he saved them from their outward enemies;
and all who come to be followers of the eternal Spirit of Jesus
see how He saves them from their spiritual enemies.

While we follow the motions of sin, we follow a wrong guide,
and in this path we may know the prevailing power of sin,
but can never know the restraining and transforming power of grace.
It is to as many as receive Christ that He gives power;^
footnote:[John 1:12 KJV]
and none really receive Him, but such as turn from sin at His reproof,
and confide in Him for a Savior.
Only these truly believe in His name.

I grant that the shining of an inward light (which is the first manifestation
of Christ to the sons and daughters of men) seems small and powerless at first;
and so do the first motions to sin.
But if you follow such sinful motions as far as they will lead,
you shall find them powerful enough.
Are there not many to be found at this day, even amongst us who are called Christians,
who are so captivated under the power of sin,
that a slave held in chains of iron could more easily break his bonds, arise, depart,
and return unto his native country, than these could cease from iniquity,
rise from their fall, and lead a sober, righteous, godly life.

Now, if the seed of sin comes to have such power over us by our following its motions,
why may not the Seed of grace have just as much power over us,
if we return to it and become its followers?
Surely John, who had travelled from death to life,
and was an eye-witness of things as they were in the beginning,
felt such a power in himself when he wrote,
"`Whosoever is born of God does not commit sin, for His Seed remains in him,
and he cannot sin.`"^
footnote:[1 John 3:9]
And many living witnesses may be found at this day,
who can say from a sensible experience,
that where this righteous Seed has risen and come to have dominion,
it is so powerful and restraining that they cannot be unjust in their dealings,
nor unfaithful in their promises; they cannot tell a lie,
though it would be ever so much to their outward advantage; they cannot be intemperate,
wasting the good creation that God has given for
their nourishment by excessive eating and drinking;
they cannot oppress the poor, the widow, and fatherless,
nor take by violence that which they have no right to have.
The small Seed in them has become the tallest of plants,
and has as much power over them as sin has over all who dwell therein.
These, like the Colossians, are delivered from the power of darkness.
These, like the Philippians, have their citizenship in heaven.
These glorify God in their lives, and so answer the end of their creation.

An abundance of preaching has made many godly talkers, but it is grace in the heart,
and truth in our inward parts, that makes godly livers.
And there is no way to attain to the fulness of this heavenly treasure
but by denying all motions which the eternal light of righteousness
in our inward parts shows us to be unjust and dishonest.
For in denying the evil, we are choosing the good;
and as the growth of sin stands in our embracing what is evil,
so the growth of grace stands in our embracing what is good.

Conformity to outward forms of worship (being more attractive to people than the strait
and narrow way of the cross) has in our present age gotten the name of religion,
Christianity, and true godliness.
But the conformity which the living God requires is a conformity to the image
of Christ in the whole course of our lives--to be holy as He was holy.
Without this we cannot truly be (as the primitive Christians were) the household of God;
we have not come to the New Jerusalem, and so cannot be fellow-citizens with the saints.
Though we bear the primitive Christians`' name,
we are not in the primitive Christians`' nature;
for the first-born is not brought down so as to have a right Spirit rule in us,
and have the dominion over us.

If the sayings contained in this book seem strange to the reader,
it is because the reader is a stranger to the primitive Christians`' life.
For if He who was the head and leader of the early Church had become our head and leader,
we should have an echo in ourselves answering to what is here written;
and our hearts would say, "`It is so.`"

And the way to come to their righteous life, is to walk in the light,
denying and turning from the least thing that it manifests unto us to be evil.
At the beginning of our journey, it will seem a narrow and difficult way,
but after we have travelled a while, we shall run therein with great delight.
For the kingdom of heaven--or Christ`'s government by His eternal Spirit
in the hearts of His people--does not consist of righteousness alone;
the righteousness that proceeds from a right Spirit is accompanied with peace and joy.
As evil-doing is attended with trouble and sorrow,
well-doing is attended with peace and joy.
All the pleasures of wickedness that the whole world can afford,
are not to be compared to the joys of a righteous life.

When the Heathen, through the preaching of the gospel,
turned from their darkness and came to be followers of the eternal Spirit,
thereby mortifying the strength of sin, they were called by the apostle "`Saints.`"
This was a name more suitable than that of "`Christians,`" for
the title of saint is peculiar to all truly sanctified souls.

As conforming to outward circumcision had given many the name of Jews,
so imitating John`'s water baptism has given many the name of Christians;
but nothing can give either a Jew or Christian the name of a saint,
but a heart made pure, single, and righteous, through the mortification of sin, which,
in Scripture, is called "`the baptism of the Holy Spirit`"^
footnote:["`He shall baptize you with the Holy Spirit, and with fire:
Whose fan is in his hand, and he will throughly purge his floor,
and gather his wheat into the garner;
but he will burn up the chaff with unquenchable fire.`"--Matt
3:11-12]--for this is effected not by any outward means,
but by our walking after the Holy Spirit.
Till this is wrought, though we have a Christian name,
we can in no way bring forth a heavenly conduct, and so the name profits little.

For we who are called Christians have in ourselves a seed of sin, just as all others do;
and for lack of faithful weeders to root up evil as soon as it appears,
iniquity grows to such a height that nothing less
than the powerful Spirit of Christ can bring it down.
And from those who remain strangers to the working of this Spirit a cry has gone forth,
"`That there is no freedom from sin on this side the grave!`"
But the Colossians, who were delivered from the power of darkness, knew better things;
and so should we, if we would but turn from iniquity,
acquaint ourselves with their Guide, and walk in newness of life.

But just as nothing discouraged the camp of Israel from going up to possess the
land of Canaan more than the report which the ten spies gave of the giants within,
so nothing discourages awakened souls from pressing after a life of righteousness more
than the report which professors of Christianity give concerning the strength of sin,
and how it cannot be overcome.
Those who give this report have never made a trial of the way of God`'s salvation.

All the spies spoke well of the land, as all sorts of people do now of a sober,
righteous, and godly life.
All will commend humility, meekness, moderation, temperance, patience, chastity, and,
above all, plain, upright, honest and just dealings, though they do not practice them.
And nothing hinders a life of godliness but this:
that the evil spirit of this world remains uppermost within,
and few endeavor (in God`'s way) to bring it down.

Had the camp of Israel appointed a captain and gone back into Egypt,
they could never have subdued the Canaanites in the land.
And while we allow ourselves to live in sin, it is impossible for us to subdue it;
for we strengthen what we should put to death.
The strength of the Canaanites was made weak by war,
and so must be the strength of sin--with this difference:
their war was outward and aggressive, and ours must be inward and defensive.
When, by the candle of the Lord that shines in our souls we see an aspiring thought,
a lustful desire, a covetous inclination, or any other evil motion,
if we stand on our guard and deny it entrance into our affections, it will retreat.
And after many attempts, being still resisted, it will hardly attempt any more,
and the motions thereof will be but weak at best.

While there was an "`accursed thing`"^
footnote:[Joshua 7:1, 11-15]
in the camp, the enemy prevailed, and Israel retreated; and so it is at this day.
If we cover, if we hide, if we justify what our own hearts condemn,
then evil prevails and the Spirit is quenched.
But if we accustom ourselves to the yoke of the cross, then the strength of sin,
from day to day, will be weakened,
and (as Joshua and Caleb said) "`the Lord will be with us.`"^
footnote:[Numbers 14:9]
His grace will be in our hearts, and His fear will be before our eyes.
Truth, equity, and honesty will be uppermost within,
and then it will be as easy to lead a sober, righteous, godly life,
as ever it was to live a loose and ungodly life.
For though something of sin may remain in us,
as some of the Canaanites remained in the good land, yet it will be powerless,
as they were.
And so all our members that were once servants to sin,
will become servants to righteousness, as it is written,
"`The elder shall serve the younger.`"^
footnote:[Genesis 25:23]

But if we rebel against the Lord by joining with
the motions of sin (as many who are called Christians,
as well as the Heathen, now do), then this war will be over before it has begun.
That seed which is uppermost will continue to be so; and as we live,
so we shall die--receiving wages, not according to our _words,_ but,
according to our _works._^
footnote:[Matthew 16:27; John 5:29; Romans 2:6; 2 Corinthians 5:10; Revelation 2:23,
20:12]
And then we shall know that a Christian name, without a Christian nature,
will be to no profit in the end; for it is not he who is overcome, but he who overcomes,
that shall not be hurt by the second death.
