== The Grace that Brings Salvation

[.salutation]
To the Reader

Most men have learned to speak well of grace,
but few can tell what it is or where it may be found.
Many will acknowledge it to be the gift of God;
yet they presume to have it from the lips of men.
Many are persuaded that all wickedness springs from the lack of grace,
yet through ignorance they neglect its appearances within themselves.
Many are convinced that, were grace their leader,
it would be sufficient to preserve from great sins,
but these cannot believe it is sufficient to save from all sin.
All of which plainly shows that their speaking well of grace is from hear-say,
and not from experience.

This little treatise shows: 1) what grace is, 2) where it may be found,
3) how it comes to be man`'s leader 4) how it is that which saves from sin,
and so effects man`'s true salvation.
For whosoever is saved from sin here,
shall certainly be saved from death and condemnation hereafter;
and that many may come to be witnesses of this salvation is the desire of,

[.signed-section-signature]
Hugh Turford

[.asterism]
'''

Paul, an apostle of Jesus Christ, writing to Titus, the first bishop of Crete,
had this saying, "`The grace of God, that brings salvation, has appeared unto all men,
teaching us, that denying ungodliness and worldly lusts, we should live soberly,
righteously, and godly, in this present world.`"^
footnote:[Titus 2:11]
From which weighty sayings these following questions arise:

[.discourse-part]
_Question 1:_ What is the grace of God?

[.discourse-part]
Answer: The grace of God, that brings Salvation, is no less than a divine inspiration,
a gift of God to the sons and daughters of men, an adversary to the devil,
a destroyer of sin, and that which saves mankind therefrom.

The gift of grace, under the gospel administration,
is the fulfilling of that promised covenant which God,
by the mouth of His prophet Jeremiah, promised to make with the house of Jacob,
which was, "`That He would write His law in their hearts,
and put His Spirit in their inward parts;`"^
footnote:[Jeremiah 31:33]
that His people might have a rule of righteousness
within themselves by which to guide their steps.

As the princes of the earth rule and govern their people by an outward law,
so the Lord resolved to rule and govern His people by an inward law.
They should have no need to turn over the pages of
a book to know how to walk in right paths,
as did the seed of Abraham under the first covenant;
but by looking to "`the law of the Spirit of life in Christ Jesus`"^
footnote:[Romans 8:2]
in their own hearts, they should know what was right and what was wrong,
what they might do and what they should leave undone, what was just and what was unjust,
what was pleasing to God and what was not.
For this "`law is a light`"^
footnote:[Proverbs 6:23]
that enlightens men`'s souls, even as the sun in the firmament enlightens our houses,
showing what is clean and what is unclean,
what may remain and what needs to be swept out.

For as God made man in the beginning to be humble, lowly, meek, merciful, pure,
peaceable, just, and faithful, He desires all men to be so.
But because nothing less than the good Spirit of God in the inward
parts of man can bring any of us to such a qualification,
God has given to every man a measure thereof to enlighten his understanding,
and to guide him in the path of life and salvation.
And this measure, being the free gift of God, is called _grace_ by the apostle,
both in this text and in many other places of Scripture.

[.discourse-part]
_Question 2:_ Where does the grace of God, that brings salvation, appear?

[.discourse-part]
Answer: The great God, in His infinite wisdom and everlasting love,
has placed His royal Seed or "`plant of renown`"^
footnote:[Ezekiel 34:29]
in the hearts of the sons and daughters of men,
for that is the chief command post of the soul.
There the grace of God, that brings salvation, may be found.
And from there (until it comes to be veiled by clouds of iniquity) it shows itself
as a witness against all unrighteousness and ungodliness.

Just as every evil motion and temptation that leads to sin appears within,
so the grace of God--which is given to men to save from sin--also appears within.
There is not a man born into the world (if he has lived long enough to
commit sin) who has not felt and known rebukes for sin within himself;
and these inward rebukes are some of the appearances of grace,
and are called in Scripture "`Light,`" or "`true Light,`"^
footnote:[John 1:4, 5, 7, 9; 3:19-20; 11:9-10; Acts 26:18; 2 Corinthians 4:6;
Ephesians 5:13; 2 Peter 1:19, etc.]
for it manifests every work of darkness,
showing us both when and wherein we have done amiss.
This it has done in all ages.

God has not (in any age) left Himself without a witness in the hearts of men,
to declare His righteousness, truth, and faithfulness.
But there is a great difference between the first appearance of grace,
and the power of grace unto salvation; between the light of righteousness,
and that fulness which enables us to lead a life of righteousness;
between a seed that is sown, and the plant when it has come to full growth.
Nevertheless, the one leads to the other;
and it is he who attains to the fulness of grace that comes to lead a sober, righteous,
and godly life in this present world.

It was said of Jesus, the second Adam, that He was "`full of grace;`"^
footnote:[John 1:14]
and we may easily believe it from the fruits He brought forth in His life.
He was humble, lowly, meek, patient, peaceable, just, and faithful.
He resisted the devil in all his temptations, led a blameless life,
fulfilled all righteousness,
and in the whole course of His life retained what the first Adam soon lost, namely,
the image of God.
And whosoever grows in grace until he attains full stature,
(becoming filled with grace) may be called, as Job was, "`a perfect man.`"^
footnote:[Job 1:1, 8; 2:3]

And as the appearances of grace are inward, so are all its discoveries, revelations,
and teachings.
Whosoever applies himself to man for a right knowledge of the things of God,
goes to a wrong school; for, as Paul truly said,
"`That which may be known of God is manifest within.`"^
footnote:[Romans 1:19]

The proud, the covetous, the envious, and other ungodly persons, may,
for a time (even a long time), experience the appearances of grace.
They may experience rebukes for sin;
but if by such rebukes they do not learn righteousness, then they do not grow in grace,
nor does grace grow in them.
Such as these "`hide their talent in the earth,`"^
footnote:[Matthew 25:25]
and in time (for lack of increase), have it quite taken from them;^
footnote:[Matthew 25:28]
and then being left graceless, they lead a wicked and ungodly life in this present world.

[.discourse-part]
_Question 3:_ If the grace of God appears unto all,
and if there is sufficiency therein to make them godly, then why are so many ungodly?

[.discourse-part]
Answer: Even as the grace of God that brings salvation appears unto all men,
so the motions of sin that lead to destruction appear unto all men,
and these commonly make the first appearance.
All men find evil motions and temptations in themselves
to sin before they are acquainted with rebukes for sin;
and the work of the devil is to make forbidden things appear desirable,
and to make the world and its vanities appear full of pleasantness.
Now as our affections come to be captivated,
as we make the world our delight and pursue it, so we depart from God.
And though grace may make many appearances,
though the good Spirit of God may long strive with us,
though we find in ourselves many checks and rebukes and are thereby
made sensible that our ways and our deeds are displeasing God,
yet we are prone to persevere in our course.
And through this continued perseverance,
sin grows strong and comes to have dominion over us,
and the devil makes one ungodly person the bait to catch another.
This is the very cause why we have so many ungodly men and women in the world.

The further any man goes from God and godliness, the less desire he has to return.
The more delight he takes in the vanities of this world,
the less happiness he beholds in the things of God.
But as long as one spark of grace remains,
the devil follows and pursues with all of his temptations;
for he can call none truly his own until they become quite graceless.
And indeed,
there would be many more graceless men and women found in the world
if wickedness were not limited by an outward law.

Were we, as Israel once was, without a king; or were we like the inhabitants of Laish,
who "`had no magistrate in the land to put them to shame for anything,`"^
footnote:[Judges 18:7]
we would find many who bear the Christian name to be of the devil`'s nature,
working all manner of wickedness.
So it highly concerns all who still feel the appearances
of grace to learn righteousness from its rebukes,
that grace may grow in them and be their guide; for nothing but grace,
and obedience unto righteousness,
makes us differ from the worst of men who commit vile actions.
For just as all righteousness proceeds from the fulness of grace,
so the abounding of wickedness proceeds from the lack of grace.

[.discourse-part]
_Question 4:_ What manner of salvation does the grace of God bring?

[.discourse-part]
Answer: As the appearances of grace are rebukes for sin,
so the salvation that grace brings is a saving from sin.
If grace teaches men to live soberly, righteously, and godly in this present world,
then grace saves good men from the power of sin in this present world.

We read of an angel that appeared to Joseph, saying,
"`Fear not to take unto you Mary your wife,
for that which is conceived in her is of the Holy Spirit;
and she shall bring forth a Son, and you shall call His name Jesus,
for He shall save His people from their sins.`"^
footnote:[Matthew 1:21]

Nothing defaces the image of God in man but sin;
nor can anything recover that image again, but our being saved from sin.
The mortification of sin brings men back to their beginning.
Paul told the Ephesians that they were saved by grace; and what were they saved from,
but from the power of sin and Satan?
And where did they experience this grace but in their own hearts?
Before these came (by turning from their iniquities) to have grace reign in their hearts,
they walked, as thousands now do, according to the course of the world, not denying,
but rather fulfilling the desires of their minds.
Then they were without Christ, without light, without life,
without the sense or feeling of anything in them that is of God.
They were aliens from the government of Christ`'s eternal Spirit in their inward parts,
and strangers to the promised covenant, knowing no more of a law in their hearts,
by which to guide their steps, than the ungodly men of this age.

But when they came to be quickened by Christ,
and were turned to His good Spirit in their own hearts to be led by it,
they were saved from sin, and came to have new natures, and so were made new creatures.
Then they were no longer strangers to Christ`'s government,
but finding His law within themselves, they became subjects to righteousness,
citizens with saints, and members of God`'s own family.
And to this blessed state we might all come,
if we would but embrace the gift of God for our salvation,
and give ourselves up to be taught and guided thereby.
Indeed, this would be our wisdom, since nothing else can subdue Satan, save from sin,
and enable us to live soberly, righteously, and godly in this present world.

Saving from sin on this side the grave may seem a preposterous
thing to such as are strangers to God`'s salvation;
but were men as well acquainted with the power of grace,
as too many are acquainted with the strength of sin, they would say,
'`Christ`'s yoke was easy.`'

Has it not been the common saying of many ungodly men, that they would amend their lives,
if they only had the power?

Wherever the hearts of any, through perseverance in sin,
have become filled with unrighteousness,
there sin and Satan have such power over the faculties of their
souls that they cannot resist evil motions and temptations,
but must yield thereto, and allow themselves to be led away,
though they know it is unto evil practices.
But if sin has such dominion over ungodly men,
why may not grace have as much dominion over godly men?
Surely good Joseph found such a power in his soul, when he said,
"`How can I do this great wickedness, and sin against God?`"^
footnote:[Genesis 39:9]

Grace, being a divine inspiration, commands the hearts of all truly good men.
And as the heart is the chief command post of the soul,
it commands every member of the body, reining them in as with bit and bridle.
Thus the ear of a gracious man is shut from hearkening to fables and evil reports.
His eye is turned aside from gazing upon vanity.
His tongue is not allowed to curse, swear, lie,
or to be employed in any idle communication.
His hand is limited from receiving bribes to pervert justice,
and from taking anything that is not his own.
His feet are restrained from going with the drunkard into excess,
or with the immoral woman to the chamber of wantonness, or with rude persons to rioting,
reveling, or any other such practice.
By this dominion that grace comes to have over the soul,
the Lord saves His people from their sins.
And as we live in subjection to its power, we are servants to another Prince;
sin and Satan have lost their dominion over us.
This is God`'s salvation, and by it we come to live soberly, righteously, and godly,
in this present world.

[.discourse-part]
_Question 5:_ Of whom was the apostle speaking when he said,
"`teaching _us_`"? Did he mean the world in general, or only some particulars?

[.discourse-part]
Answer: Christ was given as "`a light to the Gentiles;`"^
footnote:[Isaiah 42:6; 49:6; Isa 60:3; Luke 2:32; Acts 13:47; 26:23]
and as they became obedient, He was also their leader out of all ungodliness,
and they came to live under the government of His eternal Spirit in their own hearts.
These alone does the Lord acknowledge for His people,
and none but these can call Him Lord in truth.

Grace "`appears unto all men.`"^
footnote:[Titus 2:11]
Everyone that is born into the world is given a gift of light in his soul,^
footnote:[John 1:9]
that shows him the motions of sin,^
footnote:[John 16:8; Rom 1:19; John 3:19-21]
and rebukes him as often as he yields thereto.

All true righteousness is learned from the book of
the law when it comes to be written in our hearts.
But as this law is "`the law of the Spirit of life,`"^
footnote:[Romans 8:2]
we must first be quickened by Christ, and have the Spirit of life,
before we can learn from that law.
And then, as we turn from ungodliness to the gift of grace,
we bring forth the fruits of grace in our lives.
But since we find so few producing such fruits, we may certainly conclude that,
though grace appears unto all, all are not obedient thereto.

[.discourse-part]
_Question 6:_ We confess that we have known inward rebukes for sin; we have been checked,
reproved, and convicted in ourselves after we have done wrong.
But when strong motions and temptations have arisen in our minds,
we have not found anything in and of ourselves to restrain us from doing wrong;
and to deny ungodliness and worldly lusts in our
own strength seems too hard for any mortal,
especially when any sin has gotten the dominion over us.
What can we do in such a case?

[.discourse-part]
Answer: If man, in his own strength,
could deliver his soul from under the power of sin and Satan, return unto God,
and lead a sober, righteous, and godly life in this present world,
there would have been no need of a Redeemer, no occasion for a Savior,
no use of a life-giving Spirit to give life to our souls,
no necessity of God`'s writing His law in our hearts
for a rule by which to guide our steps.
There would be no need of a light in our souls to
show us where the devil spreads his net,
casts his bait, lays his snare, and displays his false colors.
But man can no more deliver his soul from the power
of sin and Satan without the power of the Lord,
than Israel could go free from servitude to Pharaoh
without God`'s mighty hand and outstretched arm.
For this reason, grace appears unto all men for their aid.
And though the appearance of grace may seem but a small savior
to set our souls free from a severe slavery to sin and Satan,
and to conduct us in the way of life and salvation until we come to the end of our race,
to live under Christ`'s government; yet it is not smaller than Israel`'s deliverer,
who was sent to bring them out from under bondage to Pharaoh,
and to conduct them to the Promised Land.

Israel`'s aid came through two aged men (the younger of them being about
eighty years old) having no weapon but the rod in one of their hands.
Yet by this small means--God being with them--they brought six hundred thousand
men (besides women and children) out from under the power and bondage of Pharaoh.
And grace, being a divine inspiration,
is aid enough to bring millions out from under the
servitude of sin and the power of Satan,
if men would but confide in it, and give themselves up to be guided by it.

If I am checked in myself for telling a lie,
and have regard to that power which checked me, I shall be afraid of telling another.
Or if I find rebukes in myself for not keeping my word, or for doing anything wrong,
and have regard to such rebukes, I shall be afraid to repeat my folly,
lest the next rebukes be sharper.
And as this holy fear abides in us, we learn to deny ungodliness,
and in denying ungodliness we come to learn righteousness.
But those who find in themselves rebukes for sin, but pay them no regard,
are like school children who carry books at their sides and learn nothing therein;
these are no students in the school of grace.

We have read that, "`Reproofs of instruction are the way of life,`"^
footnote:[Proverbs 6:23]
and many good men at this day will acknowledge that,
were it not for reproofs of instruction that were felt in their own hearts,
by which they came to deny unrighteousness,
they would never have come to a life of righteousness.
For where rebukes for sin are received in love, the Lord does not withdraw,
but follows with more.
And the more evil is hereby subdued,
the more the soul comes to see in the light of the Lord,
and more power is received from Him to overcome all sin.

If one plague will not make Pharaoh willing to let Israel go,
he shall find another and another, until he is willing.
And if one rebuke will not make us willing to part with a beloved sin,
we shall have another and another, yes, even trouble and terror.

Paul knew "`the terror of the Lord`"^
footnote:[2 Corinthians 5:11]
before he came to find peace with God, and peace in his own conscience.
He was acquainted with judgment before he came to obtain victory.
Nothing has power to break the bonds of captivity,
and set us free from the law of sin and death,
but the law of the Spirit of life in our own hearts.

Israel`'s greatest enemies were not subdued as soon as they came out of Egypt,
but when they came into the Promised Land;
neither is the body of sin made weak just as soon as we turn from unrighteousness,
but rather when we come into the life of righteousness, with grace as our leader,
as Joshua was theirs.
For sin cannot stand in the presence of righteousness,
any more than the Canaanites could stand in the presence of Joshua.

And if any sin has got dominion over us, and its violent motions arise against us,
then is the time to "`Stand still, and the Lord will fight for us.`"^
footnote:[Exodus 14:14]
For as our hearts come to be possessed with grace,
then "`when the enemy comes in as a flood,
the Spirit of the Lord,`" being in our inward parts,
"`will lift up a standard against him.`"^
footnote:[Isaiah 59:19]

The Lord`'s controversy is not (as men vainly imagine) against the sinner,
but against the author of sin.
His appearances are all in love to save the sinner,
and His judgments are to weaken the strength of sin.
For once a man is freed from sin,
he is as willing to lead a righteous life as any
ungodly man can be to lead a wicked life;
and his joy is far greater, though the world cannot see it.

[.discourse-part]
_Question 7:_ What may truly and properly be called a "`sober, righteous, and godly life`"?

[.discourse-part]
Answer: Many, in some measure, may be acquainted with a sober life;
but a righteous and godly life is rarely considered.

A sort of devotion which consists of hearing sermons, reading good books,
and performing family duties, has for many ages been accounted as godliness,
and those who practice such things have been called a righteous people.
These things are not to be discouraged when they are done in sincerity;
but they are not the true nature of righteousness and godliness.
This and much more might have been found among the Scribes and Pharisees,
yet Jesus told His disciples,
"`unless your righteousness exceeds the righteousness of the Scribes and Pharisees,
you will by no means enter the kingdom of heaven.`"^
footnote:[Matthew 5:20]

Who is there amongst those called Christians who, one day in seven,
is not in the exercise of something called godliness?
But the greater part of these have not learned to deny ungodliness.
And such as have not learned to deny ungodliness,
are still far from the righteous and godly life that the
grace of our Lord Jesus Christ teaches all of its followers.
For whosoever thinks to attain to a righteous and godly life,
except by the teachings of grace in his own heart, deceives his own soul.

Men may lop off or hinder the growth of many branches of iniquity that appear outwardly,
but they cannot remove the cause that is within; and until the cause is removed,
there can be no thorough cure.
Now just as grace has a Spring, so iniquity has a root,
and the axe that strikes at this root is in Christ`'s hands.
And what is the axe, but "`the law of the Spirit of life,`"^
footnote:[Romans 8:2]
a law of righteousness in our own inward parts.
This wrought a perfect cure in Paul.
This made him a free man, a good man, and a minister of the gospel;
and that which cured Paul, and set him free from the power of sin,
is sufficient to do the same for all men.

"`Walk in the Spirit,`" said Paul, "`and you shall not fulfill the lust of the flesh.`"^
footnote:[Galatians 5:16]
This is the only remedy.
This is the soul-healing salve.
And what is this walking in the Spirit,
but following the leadings of grace in our own hearts.
For grace, as it comes to have the rule over us, brings down all exalted thoughts,
abases pride, shuts out covetousness, gives no place to wrath,
and reduces us to quiet frame of spirit.
Grace will not allow us to do any unjust thing, nor speak an ill word,
for it is the promised Spirit of truth that "`leads into all truth,`"^
footnote:[John 16:13]
leads out of all error, and so brings salvation indeed.

No man can lead a righteous life until a right Spirit
comes to have the whole possession of his heart;
for it is out of the good treasure of the heart that all goodness proceeds.
The Spirit is our guide, and this guide being of a divine nature,
makes us to be heavenly-minded.

Nothing exceeds the righteousness of the Scribes and Pharisees,
but the righteousness that proceeds from a right Spirit
in our own hearts--this is not our own righteousness,
but the righteousness of Christ.
And just as evil proceeds out of the heart where the evil
spirit of this world has the possession thereof,
so love to all men proceeds out of the heart where
the good Spirit of God has come to abide.
But this abode is not known, till by denying ungodliness and worldly lusts,
the spirit of this world is denied, and thereby the heart is cleansed.
Then, and not till then, we come to know "`the Lord our Righteousness.`"^
footnote:[Jeremiah 23:6; 33:16]

And since this reformation comes only by the grace of our Lord Jesus Christ,
give me leave to say with the prophet, "`Ho, everyone that thirsts, come to the waters`"^
footnote:[Isaiah 55:1]
and drink!
Everyone that has a desire in his soul after righteousness,
turn in to the grace of God in your own heart!
The water to which the prophet invited all thirsty souls,
is no other than that which Christ gives.
Whosoever drinks of this water thirsts no more,
but has (as many at this day can witness) a well in himself, not only issuing,
but springing up to eternal life.

The grace of God is a free gift, without money and without price.
Nothing is required on man`'s part but to hearken thereunto, and take counsel therefrom.
"`Hear,`" said the prophet, "`and your soul shall live.`"^
footnote:[Isaiah 55:3]
Adam, by hearkening to evil motions, died unto righteousness, and so do all ungodly men.
But he that hearkens to the voice of grace, lives unto righteousness;
and from the flowing of that Spring which he has in himself, leads a sober, righteous,
and godly life in this present world.

[.discourse-part]
_Question 8:_ Were not the Scriptures written for our learning,
and are they not a sufficient rule of righteousness?

[.discourse-part]
Answer: The Scriptures are indeed a good rule; but who can walk by this rule,
unless he is filled with the good Spirit of God?

The house of Jacob had not only ten commands written on tablets of stone,
but many other statutes and commandments written in their books,
which proceeded from a righteous Judge.
These were not only read, but also expounded to them every Sabbath day,
that they might walk in righteous paths.
But though Israel had the words of God in their books,
many had not the fear of God in their hearts, and so,
though they had a great zeal for their outward worship and form of devotion,
they were ungodly in life and conduct.

And what shall I say of us who are called Christians?
We have the words of God, the words of the prophets, the words of Christ,
and the words of the apostles in our book.
We have great rules of righteousness, but do we guide our steps by this rule?
Or can we?

Let those who say the Scripture is our only rule,
examine your ability to walk by this rule.
Are you lights to the world?
Are you so far from committing adultery, that you have not so much as a lustful thought?
Can you refrain from striking when you are struck?
Can you give your cloak to him that wrongfully takes your coat?
Can you love your enemies?
Can you bless those that curse you?
Can you do good to those that hate you?
Can you pray for those that despitefully use you?
Do you worry what you shall eat or drink, or what you shall wear?
Can you do unto all men according as you would have them do unto you?
This is Christ`'s yoke; can you bow your hearts and mind thereto?
This is Christ`'s burden, can you bear it?
He said, "`My yoke is easy and My burden light,`"^
footnote:[Matthew 11:30]
but if these things are too hard and too heavy for you,
it is because you do not yet know His grace and His spirit.
You have a Christian name, but are not yet in the Christian nature.
You have a written rule, but have no power to walk by your rule.
And so what good does your written rule do you?

If ever we desire to walk according to the rule of Scripture,
if ever we intend to keep our Lord`'s commands,
and if we desire to lead a righteous and godly life in this present world,
we must turn in to the grace of God in our own hearts;
for only grace gives power to keep to this rule.
The fulness of grace that dwelt in Christ made all these things easy to Him.
And as we grow in grace and come to be filled therewith, they are made easy to us as well.
Grace mortifies sin, and where sin is mortified,
nothing is easier than to lead a righteous life.

[.discourse-part]
Objection: But some may say,
"`Our dependance for life and salvation is not on works of righteousness, but on faith.
We believe, and therefore we expect to be saved.`"

[.discourse-part]
Answer: I know that this is where most men have placed their dependence,
and all assume that they have saving faith.
But is yours a "`faith that purifies the heart,`"^
footnote:[Acts 15:9]
and makes your bodies fit temples for the Holy Spirit of God?

Paul put the Corinthians on an examination of themselves,
for the trial and proof of their faith;
and it would be wise if all that accounted themselves
believers did prove their faith by the same touchstone.
"`Examine yourselves as to whether you are in the faith.
Test yourselves.
Do you not know yourselves,
that Jesus Christ is in you?--unless indeed you are disqualified.`"^
footnote:[2 Corinthians 13:5]

How can we know the only true God if we do not behold His presence?
How can we know our Savior if He is not found within us,
saving us from our spiritual enemies,
even as Joshua was in the camp of Israel to save them from their outward enemies?
And this is life eternal, not to hear of a God and a Savior, but to know Him,
to feel His power, and become a witnesses of His salvation.
Such as these are true believers, for their eyes have seen what they believe.

Faith and works of righteousness go together.
He that has the one has both, and grace is the spring from which both proceed.
The unbeliever, the ungodly, and the graceless, have neither.

[.discourse-part]
_Question 9:_ If inward and spiritual grace is sufficient
to teach us our duty towards God and man,
and to establish us in righteousness, why then was there an outward ministry,
and to what end were apostles, prophets, evangelists, pastors, and teachers,
given to the church?

[.discourse-part]
Answer: Paul told king Agrippa that he was made "`a minister and a witness.`"^
footnote:[Acts 26:16]
He was a witness of the powerful operation of grace in his own soul,
and so could tell others what it could do for them.

In the state of degeneration all men are strangers to grace, and they know not the Lord.
The work of the ministry is to open the understandings of such as these,
and to turn them to this heavenly Teacher.
Paul was sent "`to turn men from darkness to light, and from the power of Satan to God,
that they may receive forgiveness of sins and an inheritance
among those who are sanctified by faith in Me.`"^
footnote:[Acts 26:17-18]

Some were sent to plant, others were sent to water,^
footnote:[1 Corinthians 3:5-8]
that no young plant might wither before it came to be rooted and grounded.
But we find that, even in the primitive times,
some turned back from what they had attained, for they kept not to their Guide;
and with these,
Paul was forced to "`labor in birth again until Christ was formed in them.`"^
footnote:[Galatians 4:19]
For even as plants are not grounded just as soon as they are planted,
so men are not established in righteousness as soon as they are turned from unrighteousness.
Therefore, those who were strong were to watch over the weak,
and lend them a hand in their travails until they came, in the unity of the Spirit,
"`to a perfect man, to the measure of the stature of the fullness of Christ.`"^
footnote:[Ephesians 4:13; See also Colossians 1:28]
Then there is no more need of an outward ministry;
for this perfection is witnessed when a right Spirit
comes to have the whole government in us.

But who are fit to plant and water?
No ungodly men, for these have not the Spirit of Jesus,
nor know the way of God`'s salvation in themselves,
and so are unfit to direct others or lend them a hand.
But true ministers are those, like Paul, who are witnesses of what they testify,
who have travelled in the way of God`'s salvation themselves,
have come through the many teachings of grace unto such a strength and perfection,
so as to "`deny ungodliness and worldly lusts, and to live soberly, righteously,
and godly, in this present world.`"^
footnote:[Titus 2:!2]
