== Preface

[.salutation]
To The Reader:

Most men will acknowledge that the primitive churches, to whom Paul wrote his epistles,
exceeded in many respects the professors of Christianity in our present age;
and good grounds they have so to believe: for the said apostle, in his epistles,
told the Corinthians, That their bodies were the temples of the Holy Spirit;
he told the Ephesians, That they were fellow-citizens with the saints,
and of the household of God: he told the Philippians,
That their citizenship was in heaven; he told the Colossians,
That they were delivered from the power of darkness,
and translated into the kingdom of the dear Son of God; he told the Hebrews,
That they were come to the city of the living God, the heavenly Jerusalem.
And Peter, in his general epistle to the churches, told them,
That they were a chosen generation, a royal priesthood, a holy nation,
a peculiar people.

But is this our state?
Can we say, from a sensible feeling, that the Holy Spirit of God dwells in us?
that our bodies are the temples, in which we may behold his presence, feel his power,
fear, worship, and serve him: Can we say that our citizenship is in heaven?
that we are translated into the kingdom of the dear Son of God,
and live under the sceptre of his government?
that we are come to the heavenly Jerusalem,
where the great God is worshipped in spirit and in truth?
Or, are we not strangers to all these things,
and yet persuade ourselves that we are the people of God, and good Christians?

The primitive churches had the honorable name of saints;
we can give ourselves no better name than miserable sinners; and what is the reason?
Most in
the aforementioned churches, before their conversion, were but heathens;
they were not born of Christian parents, nor trained up in the Christian faith,
as we think we are; and after conversion they had but little preaching,
in comparison to what we have;
neither were they furnished with books so plentifully as we are.

We cannot conclude that the kingdom of Christ, that then appeared in power,
did (as the sun in the firmament sometimes does) show itself in a morning,
and be no more seen all day: for the kingdom of Christ is an everlasting kingdom,
and the new covenant that was made with the house of Jacob an everlasting covenant.
Neither may we conclude that God has withdrawn himself from the children of men;
for he never forsakes us, unless we first forsake him.

The apostle foresaw that there would be a falling away from
the grace in which many primitive Christians were established:
which soon after his decease came to pass.
But our preachers say, "`That the dark night of apostasy is over,
and that we live in gospel days again;`" but if so, where are the fruits?
We may, I confess, hear gospel words;
but where is the gospel power by which believers come to be the sons of God,
and to bear his image in righteousness?
Why are not we, who are called Christians,
grown to the stature of them that were born Heathens,
and brought up in blindness and ignorance: Why are not we sanctified,
and made a holy people, as well as they?
Why are not our bodies cleansed, and made a habitation for the eternal Spirit,
as theirs were?
Why is not our citizenship in heaven, or at least more heavenly than it is?
The reason to me is this,
we have not built upon the same foundation that they built upon:
for this we are to understand, that the Heathens had not the Scriptures as we have,
and so could not frame a form of godliness therefrom, as many since have done,
made up with good words, calling that godliness,
and resting in an outward performance thereof, without any true conversion,
or sense of that inward life and power, that the primitive Christians came to feel,
and found in themselves through faith,
and the operation of the eternal quickening Spirit of Jesus.

The Heathens, as well as others, were of God`'s creation,
(all nations being made of one blood,) and so had in themselves, as every man has,
a good spirit, as well as a bad; light, as well as darkness;
something that reproved them for sin, as well as something that tempted them to sin.
And being, by the Apostle, turned from the darkness that was in them, to the light;
from that which tempted them to sin, to that which convicted and reproved them for sin;
they cleaved thereunto, confided therein, and became followers thereof:
and by cleaving to the good, they were delivered from evil; by following the light,
they came to be translated out of the kingdom of darkness,
and to have their citizenship in heaven, while they were upon earth.

These built on a sure rock, a living foundation, on Christ, as he in all ages was,
and still is, in his spiritual appearance, the light of the world,
and the life of righteousness; and,
taking his eternal Spirit in themselves for their guide,
turned from whatsoever they were thereby convicted of, and reproved for; by which Esau,
or the first nature, came to be supplanted, and He, whose right it is to reign,
came to have the rule in them, and the government over them.
And, as the darkness that eclipsed the brightness of the
sun of righteousness in them came to be removed,
they came to have a clear discerning what was of God, and what was selfish,
and to be denied; and, turning from every motion that was not of God,
the body of sin became mortified, their insides became cleansed,
the lump became leavened; such as were carnal became spiritual;
and this made them a peculiar people.

And did we walk in their footsteps, we might rise to their attainment;
but if we build on words, and outward services without spirit and life,
we can never rise; for, as Paul said in another case,
"`If I speak with the tongue of men and angels, and have not charity,
I am become as sounding brass:`" so, say I in this case, if we hear men and angels,
if we could live continually under the sound of good words,
if we have no regard to that inward light which discovers the rising of evil motions,
and power from God to turn from them, we can never mortify sin, cleanse our souls,
and become a holy people.
The work of sanctification is inward, and to be effected by inward means;
nothing but inward light can expel inward darkness;
nothing less than eternal life can deliver our souls from the power of death.

Since men came to be persuaded that though they sow tares, they shall reap wheat;
though they go down into the grave sinners, they shall rise saints,
and attain in another world what the primitive Christians attained to in this world;
their citizenship has not been in heaven, but in the earth; they have walked in darkness,
and not in the light; the god of this world has been served, and not the God of heaven.
And what future happiness this can produce, let the wise in heart judge.

[.signed-section-signature]
Hugh Turford
