== The Grace that Brings Salvation

[.salutation]
To the Reader

Most men have learned to speak well of grace, but few of them can tell what it is,
or where it may be found: many will acknowledge it to be the gift of God;
yet think to have it from the lips of men: many are persuaded,
that all wickedness is for lack of grace;
yet through their ignorance slight the appearances thereof in themselves:
many are convinced, that there is a sufficiency therein, were it before men`'s faces,
to preserve them from great sins;
but cannot believe there is a sufficiency therein to save them from any sin.
Which plainly shows, that their speaking well of grace is from hear-say,
and not from experience.

This little Treatise shows, what grace is, where it may be found,
and how it comes to be before men`'s faces; that it is +++[+++that which saves]
from sin, and so the true salvation.
For whosoever is saved from sin here,
shall certainly be saved from death and condemnation hereafter:
and that many may come to be witnesses of this salvation is the desire of,

[.signed-section-signature]
Hugh Turford

[.asterism]
'''

Paul, an apostle of Jesus Christ, writing to Titus, the first bishop of Crete,
had this saying, "`The grace of God, that brings salvation, has appeared unto all men,
teaching us, that denying ungodliness and worldly lusts, we should live soberly,
righteously, and godly, in this present World.`"
From which weighty sayings these following questions arise:

[.discourse-part]
_Question 1:_ What is the grace of God?

[.discourse-part]
Answer: The grace of God, that brings Salvation, is no less than a divine inspiration,
the gift of God to the sons and daughters of men, an adversary to the devil,
a destroyer of sin, and that which saves mankind therefrom.

The gift of grace, under the gospel administration,
is the fulfilling of that promised covenant, which God,
by the mouth of his prophet Jeremiah, promised to make with the house of Jacob,
which was, "`that he would write his law in their hearts,
and put his Spirit in their inward parts:`" that his people might have
a rule of righteousness in themselves to guide their steps by.

As the princes of the earth rule and govern their people by an outward law,
so the Lord resolved to rule and govern his people by an inward law:
they should have no need to turn over the leaves of a book,
as the seed of Abraham under the first covenant had,
to know how they should walk in right paths; but they should know,
by looking into their own hearts, what was right, and what was wrong; what they might do,
and what they should leave undone; what was just, and what was unjust;
what was pleasing to God, and what was not: for this law is a light,
that enlightens men`'s souls, as the sun in the firmament enlightens our houses,
showing what is clean, and what is unclean; what may remain,
and what is to be swept out.

For as God made man in the beginning, humble, lowly, meek, merciful, pure, peaceable,
just, and faithful; he would have all men to be so.
But forasmuch as nothing less than the good Spirit of God, in the inward parts of man,
can reduce any of us to such a qualification,
God has given to every man a measure thereof, to enlighten his understanding,
and to guide him in the path of life and salvation; and this measure,
being the free gift of God, is, by the apostle in the text,
and in many other places of Scripture, called _Grace._

[.discourse-part]
_Question 2:_ Where does the grace of God, that brings salvation, appear?

[.discourse-part]
Answer: The great God, in his infinite wisdom and everlasting love,
has placed his royal seed and plant of renown in
the hearts of the sons and daughters of men,
for that is the chief garrison of the soul; there the grace of God,
that brings salvation, may be found: from there,
until it come to be veiled by clouds of iniquity,
it shows itself a witness against all unrighteousness and ungodliness.

As every evil motion and temptation, that leads to sin, appears within;
so the grace of God, that is given to men, to save from sin, appears also within.

There is not a man born into the world, if he has lived to commit sin,
but has felt and known in himself rebukes for sin;
and these rebukes are the appearances of grace, and called in Scripture Light,
and true Light; for it manifests every work of darkness;
it shows us both when and wherein we have done amiss: and this it has done in all ages.

God has not in any age left himself without a witness in the hearts of men,
to declare his righteousness, truth, and faithfulness.
But there is as much difference between the appearance of grace,
and the power of grace to salvation; the light of righteousness,
and that fulness which enables us to lead a life of righteousness;
as is between a seed that is sown, and the herb when it is come to full growth;
but the one leads to the other; and it is he that attains to the fulness of grace,
that comes to lead a sober, righteous, godly life in this present world.

It was said of Jesus, the second Adam,
that he was "`full of grace;`" and we may believe
it from the fruits he brought forth in this life:
he was humble, lowly, meek, patient, peaceable, just, and faithful;
he resisted the devil in all his temptations, led a blameless life,
fulfilled all righteousness, and in the whole course of his life,
retained what the first Adam soon lost, namely, the image of God:
and whosoever grows in grace until he attains to his stature, namely,
to be filled therewith, may be called, as Job was, "`a perfect man.`"

And as the appearances of grace are inward, so are all its discoveries, revelations,
and teachings;
whosoever applies himself to man for a right knowledge of the things of God,
goes to a wrong school; for, as Paul truly said,
"`That which may be known of God is manifest within.`"

The proud, the covetous, the envious, and other ungodly persons, may, for a time,
and a long time, have the appearances of grace; they may have rebukes for sin;
but if by such rebukes, they do not learn righteousness, they grow not in grace,
neither does grace grow in them; all such hide their talent, and in time,
for lack of improvement, come to have it quite taken from them; and being left graceless,
lead a wicked and ungodly life in this present world.

[.discourse-part]
_Question 3:_ If the grace of God appears unto all,
and if there is a sufficiency therein to make them godly, how comes it to pass,
that there are so many ungodly:

[.discourse-part]
Answer: As the grace of God that brings salvation, appears unto all men,
so motions of sin, that lead to destruction, appear unto all men,
and commonly make the first appearance.
All men have evil motions and temptations in themselves to sin,
before they are acquainted with any rebukes in themselves for sin;
and the work of the devil is to make forbidden things appear desirable,
the world and the vanities thereof to be full of pleasantness:
and as our affections come to be taken therewith, as we make the world our delight,
and pursue after it, we depart from God; and though grace may make many appearances,
though the good Spirit of God may long strive with us,
though we have in ourselves many checks and rebukes,
and are thereby made sensible that our ways and our doings displease God,
yet are we prone to persevere therein; and through a continued perseverance,
sin grows and comes to have dominion over us:
and the devil making one ungodly person a bait to catch another,
is the very cause why we have so many ungodly livers in the world.

The further any man goes from God and godliness, the less desire he has to return;
and the more delight he takes in the vanities of this world,
the less felicity he beholds in the things of God.
And as long as one spark of grace remains,
the devil will follow all such with his temptations; for he can call none really his own,
until they become quite graceless;
and many such graceless ones would be apparently found,
were not wickedness limited by an outward law.

Were we, as Israel once was, without a king; or as the inhabitants of Laish,
who had no magistrate in the land, to put them to shame for anything;
we should find many who bear the Christian name to be of the devil`'s nature,
working all manner of wickedness.
And so it highly concerns all who have the appearances of grace,
from the rebukes thereof, to learn righteousness, that it may grow in them,
and be their guide: for nothing but grace, and obedience unto righteousness,
makes any of us differ from the worst of men in vile actions;
for as all righteousness proceeds from a fulness of grace,
so the aboundings of wickedness are through a deprivation of grace.

[.discourse-part]
_Question 4:_ What manner of salvation does the grace of God bring?

[.discourse-part]
Answer: As the appearances of grace are rebukes for sin,
so the salvation that grace brings, is a saving from sin.

If grace teaches men to live soberly, righteously, and godly in this present world,
grace saves good men from sin in this present world.

We read of an angel that appeared to Joseph, saying,
"`Fear not to take unto you Mary your wife, for that which is conceived in her,
is of the Holy Spirit; and she shall bring forth a Son,
and you shall call his name Jesus, for he shall save his people from their sins.`"

Nothing defaces the image of God in man but sin;
nor can anything recover that image again, but our being saved from sin.

The mortification of sin brings men to their beginning: the more humble, lowly, meek,
and merciful any man is, the more patient, peaceable, just, upright,
and faithful any man is found,
the more conformable he is to the life and nature of Christ.

Paul told the Ephesians, that they were saved by grace; and what were they saved from,
but from the power of sin and Satan: And where was this grace but in their own hearts:
Before they came, through turning from their iniquities, to have grace in their hearts,
they walked, as thousands now do, according to the course of the world, not denying,
but fulfilling the desires of their minds; and all such are, as they then were,
without Christ, without light, without life,
without the sense or feeling of anything in them that was of God;
aliens from the government of Christ`'s eternal Spirit in their inward parts,
and strangers from the promised covenant; knowing no more of a law in their hearts,
to guide their steps by, than the ungodly men of this age do.

But when they came to be quickened by Christ,
and to have in their own hearts his good Spirit, and to be led thereby,
they were saved from sin, they came to have new natures, and so to be new creatures:
and then they were no longer strangers to Christ`'s government, by a law in themselves,
but subjects to righteousness, citizens with saints, and of God`'s family.
To which blessed state we might all come,
did we but embrace the gift of God for our salvation,
and give ourselves up to be taught and guided thereby; which would be our wisdom,
since nothing else can subdue Satan, save from sin, and enable us to live soberly,
righteously, and godly, in this present world.

Saving from sin, on this side the grave, may,
to such as are strangers to God`'s salvation, seem an incredible thing;
but were they so well acquainted with the power of grace,
as too many are with the strength of sin, they would say, Christ`'s yoke was easy.

Has it not been the saying of many ungodly men, "`That they would amend their lives,
if they had but power.`"

Where the hearts of any, through a perseverance in sin,
come to be filled with unrighteousness,
sin and Satan has such power over the faculties of their souls,
that they cannot resist evil motions and temptations; but must yield thereunto,
and allow themselves to be led away thereby, though they know it is to evil practices.

And if sin has such dominion over ungodly men,
why may not grace have as much dominion over godly men?
Surely good Joseph found such a power in his soul, when he said,
"`How can I do this great wickedness, and sin against God?`"

Grace being a divine inspiration, commands the hearts of all good men;
and the heart being the chief garrison of the soul, commands every member of the body,
holding them in with bit and bridle.

The ear of a gracious man is shut from hearkening to fables and evil reports;
his eye is turned aside from gazing upon vanity; his tongue is not allowed to curse,
swear, lie, or to be employed in any idle communication;
his hand is limited from taking of bribes to pervert justice,
and from taking by violence, or otherwise, anything that is not his own:
his feet are restrained from going with the drunkard to excess,
or with a lewd woman to the chamber of wantonness, or with rude persons to rioting,
revelling, or any other rude exercise: and by this dominion,
that grace comes to have over us, the Lord saves his people from their sins.
And as we live in subjection to this power, we are servants to another prince;
sin and Satan have lost their dominion over us; and this is God`'s salvation;
by this we come to live soberly, righteously, and godly, in this present world.

[.discourse-part]
_Question 5:_ Whom did the apostle mean when he said,
"`teaching us;`" was it the world in general, or only some particulars?

[.discourse-part]
Answer: Christ was given as a light to the Gentiles; to which, as they became obedient,
he was also their leader out of all ungodliness,
and they came to live under the government of his eternal Spirit in their own hearts;
for such only the Lord owns for his people,
and none but such can call him Lord in truth.

Grace appears unto all men:
every one that is born into the world has a light in his soul,
that shows him the motions of sin,
and rebukes him when and as oft as he yields thereunto.

All righteousness is learned out of the book of the law,
when it comes to be written in our hearts;
but that law being the law of the Spirit of life, we must be quickened by Christ,
and have the Spirit of life, before we can learn from that law.

Our ancestors made it their concern to teach youth good manners, as temperance,
moderation, chastity, civil behavior, to be dutiful to parents,
to show respect to their elders, to be circumspect in their communication, swift to hear,
slow to speak, to answer with meekness and gravity, to be true to their trust,
faithful in their promises, just in their dealings, keeping to their word in all things,
that their word might be taken in all cases without doubt or scruple;
every one to know his place, and abide therein.

Now as we turn from ungodliness to sobriety,
we bring forth all these fruits in our lives; for grace teaches all this and much more;
but since we find so few thus qualified, we may certainly conclude,
that though grace appears unto all, all are not obedient thereto.

[.discourse-part]
_Question 6:_ We must confess that we have known inward rebukes for sin;
we have been checked, reproved, and convicted in ourselves after we have done amiss;
but we have not found anything in and of ourselves,
when strong motions and temptations have arisen in our minds,
to restrain us with bit and bridle from doing amiss;
and to deny ungodliness and worldly lusts in our own strength,
seems too hard for any mortal;
especially when any worldly sin has got the dominion over us:
what can we do in such a case?

[.discourse-part]
Answer: Could man, in his own strength,
deliver his soul from under the power of sin and Satan, return unto God,
and lead a sober, righteous, godly life in this present world,
there would have been no need of a Redeemer, no occasion for a Saviour,
no use of a quickening Spirit, to give life to our souls,
no necessity of God`'s writing his law in our hearts, for a rule to guide our steps by;
no need of a light in our souls to show us where the devil spreads his net,
casts his bait, lays his snare, and displays his false colors:
but man can no more deliver his soul from the power
of sin and Satan without the help of the Lord,
than Israel, when they were in Egypt,
could go free from the servitude of Pharaoh without his help;
therefore grace appears unto all men for their aid.
And though the appearance of grace may seem but small aid
to set our souls free from the servitude of sin and Satan,
and to conduct us in the way of life and salvation, till we come to the end of our race,
to live under Christ`'s government; it is not smaller than Israel`'s aid was,
to bring them from under the servitude of Pharaoh,
and conduct them to the promised land.

Israel`'s aid was but two aged men (the younger of them being about
eighty years old) having no weapons but a rod in one of their hands;
yet by this small means, God being with them,
they brought from under the power and servitude of Pharaoh, six hundred thousand men,
besides women and children; and grace, being a divine inspiration,
is aid enough to bring six hundred thousand millions
from under the servitude of sin and power of Satan,
did men but confide therein, and give themselves up to be guided thereby.

Inward rebukes, if we have regard thereunto, beget a fear in men,
as the shaking of the rod does in children;
and as "`The fear of the Lord is the beginning of wisdom,`"
so it is the beginning of a reformation of our lives.

If I am checked in myself for making a lie, and have regard to that which checked me,
I shall be afraid of making another;
or if I find in myself rebukes for not keeping my promise, or for doing anything amiss,
and have regard to such rebukes, I shall be afraid to do the like,
lest the next rebukes be sharper; and as this holy fear abides in us,
we come to deny ungodliness, and in denying ungodliness we learn righteousness:
but such as find in themselves rebukes for sin, and have no regard thereunto,
are like unto children that carry horn-books at their sides, and learn nothing therein:
they are no scholars in the school of grace.

We have read,
that "`Reproofs of instruction are the way of life,`"
and many good men may be found at this day,
who will acknowledge that they had never come to a life of righteousness,
had they not had reproofs of instruction from their own hearts,
by which they came to deny unrighteousness.
For where rebukes for sin are received in love, the Lord does not leave such souls,
but follows them therewith; and the more vices they subdue, the more,
in the light of the Lord, shall they see,
and the more power shall they receive from him to overcome them.

If one plague will not make Pharaoh willing to let Israel go, he shall have another,
and another, until he be willing;
and if one rebuke will not make us willing to part with a beloved sin,
we shall have another, yes, trouble and terror.

Paul knew terror before he came to find peace with God, and peace in his own conscience;
he was acquainted with judgment, before he came to obtain victory.
Nothing has power to break the bonds of captivity,
and set us free from the law of sin and death,
but the law of the Spirit of life in our own hearts.

Israel`'s main enemies were not subdued as soon as they came out of Egypt,
but when they came into the promised land;
neither is the body of sin made weak as soon as we turn from unrighteousness,
but when we come into the life of righteousness, to have grace before our faces,
as Joshua was before their faces: for sin cannot stand in the face of righteousness,
no more than the Canaanites could stand in the face of Joshua.

And if any stubborn sin has got dominion over us, I shall not say, as one formerly said,
"`Fight not with small or great, save only with the king of Israel,`" but rather,
when violent motions arise, Stand still, and the Lord will fight for us;
for as our hearts come to be possessed with grace,
if the enemy should come in as a flood, the Spirit of the Lord,
being in our inward parts, will lift up a standard against him.

The Lord`'s controversy is not, as men vainly imagine, against the sinner,
but against the author of sin; his appearances are all in love to save the sinner,
and by his judgments to weaken the strength of sin: for man once freed from sin,
is as willing to lead a righteous life, as any ungodly man can be to lead a wicked life,
and more joy he has, though the world cannot see it.

[.discourse-part]
_Question 7:_ What may truly and properly be called a "`sober, righteous, godly life?`"

[.discourse-part]
Answer: A sober life, many may, in some measure, be acquainted with, but a righteous,
godly life, is rarely considered.

Devotion, which consists in hearing of sermons, reading of good books,
performing of family duties, etc. has for many ages been accounted godliness,
and the practitioners thereof righteous people.

These things are not to be discommended, where they are done in sincerity;
but these are not the true character of righteousness and godliness.

This and much more might be found among the Scribes and Pharisees,
yet Jesus told his disciples,
that except their righteousness exceeded the righteousness of the Scribes and Pharisees,
they could in no way enter into the kingdom of God.

And who is there among us, that are called Christians,
but one day in seven will be in the exercise of something that is called godliness,
though they have not learned to deny ungodliness.
And such as have not learned to deny ungodliness, are far from such a righteous,
godly life, as the grace of our Lord Jesus Christ teaches all its followers.

One way to know what is righteous and godly,
is to consider what is unrighteous and ungodly, for the one is opposite to the other,
as light to darkness: and these things that follow,
most will acknowledge to be unrighteous and ungodly, namely, drunkenness, whoredom,
theft, envy, hatred, bloodshed, swearing, cursing, lying, extortion, fraud,
double-dealing, talebearing, and whispering (which is the seed of strife):
all these things are unrighteous, and pride, above many evils, most ungodly.

These are not fruits proceeding from the good Spirit of God,
but from the evil spirit of this world; not issues of life,
but streams that flow from a corrupt spring;
these come not from the teaching of grace in our hearts,
but from evil motions that arise in our minds; these make us sinners before the Lord;
and as long as we live in the practice of any of them,
we shall not be righteous in his sight: those that brought forth fruits of this kind,
have, in all ages of the world, been testified against as unrighteous and ungodly livers.
These are infirmities of the soul,
that millions of money have been given to physicians to cure,
but behold health has not been by them restored.
These are weeds that thousands have been hired to pluck up,
but to this day have not made clean gardens, nor ever will by all the art they have,
for Christ is the Physician of souls; none can take away the sins of the world,
but he alone.

Whosoever thinks to attain to a righteous, godly life,
but by the teachings of grace in his own heart, deceives his own soul.

Men may lop, or hinder the growth of many branches of iniquity that appear outwardly,
but cannot take away the cause which is within; and until the cause is removed,
there can be no thorough cure.

As grace has a spring, so iniquity has a root,
and the axe that smites at this root is in Christ`'s hands; and what is the axe,
but the law of the Spirit of life, a law of righteousness in our inward parts.
This wrought a perfect cure in Paul; this made him a free man, a good man,
and a preacher; and that which cured Paul, and set him free from the power of sin,
has a sufficiency in it to set all men free therefrom.

"`Walk in the Spirit,`" said Paul, "`and you shall not fulfill the lust of the flesh.`"
That is the only remedy, that is the soul-healing salve;
and what is the walking in the Spirit,
but following the leadings of grace in our own hearts: For grace,
as it comes to have the rule over us, brings down all exalted thoughts, abases pride,
shuts out covetousness, gives no place unto wrath, reduces us to a cool,
quiet frame of spirit, in which frame we can bear and suffer.
Grace will not allow us to do any unjust thing, nor allow us to speak an ill word,
much less to be drunk, commit whoredom, steal, or any such abominable vices:
for it is the promised Spirit of truth that leads into all truth, leads out of all error,
and so brings salvation indeed.

No man can lead a righteous life,
till a right spirit comes to have the whole possession of his heart;
for from the good treasures of the heart proceeds all good living; for that is the guide,
and this guide being a divine nature, makes us to be heavenly-minded.

Nothing exceeds the righteousness of the Scribes and Pharisees,
but the righteousness that proceeds from a right spirit in our own hearts;
for that is not our own righteousness, but the righteousness of Christ.

As murder, adultery, theft, which are some of the worst of evils,
proceed out of the heart, while the evil spirit of this world has the possession thereof;
so good-will to all men, which is a principal virtue, proceeds out of the heart,
when the good Spirit of God comes to make its abode there: but this abode is not known,
till by denying ungodliness and worldly lusts, the spirit of this world is denied,
and thereby the heart cleansed; then, and not till then,
can we come to know "`the Lord our Righteousness.`"

He that is reduced to such a qualification, as to have good-will to all men,
is of all men most godly; for as God, in his unlimited love to mankind,
"`makes his sun to rise on the evil and on the good,
and sends rain on the just and on the unjust;`" so he that has good-will to all,
will not wrong any, oppress any, show violence to any, or speak evil of any,
but be ready to serve all men in love and faithfulness;
and this is a true character of a sober, righteous, godly man;
such a one is converted indeed, and become a weaned child,
and is entered into that kingdom that consists in righteousness, peace,
and joy in the Holy Spirit.

And since this reformation is only and alone by the grace of our Lord Jesus Christ,
give me leave to say, with the prophet, "`Ho, every one that thirsts,
come to the waters,`" and drink;
every one that has a desire in his soul after righteousness,
turn in to the grace of God in his own heart.
The water that the prophet invited all thirsty souls unto,
is no other than that which Christ gives; and whosoever drinks thereof thirsts no more,
but has, as many at this day can witness, a well in himself, not only issuing,
but flowing up to eternal life.

The grace of God is a free gift, without money, and without price;
nothing is required on man`'s part, but to hearken thereunto, and take counsel therefrom;
"`Hear,`" said the prophet, "`and your soul shall live.`"
Adam, hearkening to evil motions, died unto righteousness, and so do all ungodly men;
but he that hearkens to the voice of grace, lives unto righteousness,
and from the flowings of that spring that he has in himself, leads a sober, righteous,
godly life in this present world.

Hearing and reading, at the best, tend to instruct us in what we ought to do;
but godliness is doing what grace teaches; and all such doings are right and good.

[.discourse-part]
_Question 8:_ Were not the scriptures written for our learning,
and are not they a sufficient rule of righteousness?

[.discourse-part]
Answer: The scriptures are a rule; but who can walk by that rule,
unless he be inspired with the good Spirit of God?

The house of Jacob had not only ten commands written on tables of Stone,
but many other statutes and commandments, proceeding from a righteous judge,
written in their books, and not only read,
but also expounded unto them every sabbath-day, that they might walk in righteous paths;
but though they had the words of God in their books,
many had not the fear of God in their hearts,
and so though they had a great zeal for an outward worship and form of devotion,
yet were they ungodly in life and conduct.

And what shall I say of us who are called Christians?
We have the words of God, and the words of Christ, the words of the prophets,
and the words of the apostles in our books; we have large rules of righteousness,
but do we guide our steps by our rule?
or can we?

The Christian`'s rule of righteousness is Christ`'s direction; let us,
who say the scripture is our rule, examine our abilities to walk by our rule:
Are we lights to the world?
Do our good works glorify God, or shame our Christian profession?
Are we so far from committing adultery, that we have not so much as a lustful thought?
Are we so far guided by the truth, that every word that proceeds out of our mouths,
by way of promise, is sure and steadfast?
Can we refrain from smiting when we are smitten?
Can we give our cloak to him that sues us at the law, and wrongfully takes away our coat?
Can we love our enemies?
Can we bless them that curse us?
Can we do good to them that hate us?
Can we pray for them that despitefully use us?
Can we depend on God`'s providence, without taking care what we shall eat,
or what we shall drink Can we do unto all men, in all things whatsoever,
as we would that they should do unto us?
This is Christ`'s yoke; can we bow our hearts and minds thereunto?
This is Christ`'s burden, and can we bear it?
He said, his yoke was easy, and his burden light; but if these things are too hard,
and too heavy a burden to us, it is because we have not his grace and his spirit;
we have a Christian name, but are not in the Christian nature; we have a rule,
but have not power to walk by our rule; and then what good does our rule do us?

If ever we think to walk by scripture rules,
if ever we intend to keep our Lord`'s command, and if we would lead a righteous,
godly life in this present world, we must turn in to the grace of God in our own hearts;
for that gives us power to keep to our rule.

It was for lack of grace, that the seed of Abraham could not keep Moses`'s commands;
it is for lack of grace that Christians do not keep Christ`'s commands;
he lays no other burden on us than what he bore himself;
the fulness of grace that dwelt in him, made all these things easy to him; and,
as we grow in grace till we come to be filled therewith, they will be easy unto us:
grace mortifies sin, and where sin is mortified,
nothing is easier than to lead a righteous life.

[.discourse-part]
Objection: But some may say,
our dependance for life and salvation is not on works of righteousness, but on faith:
we believe, and therefore hope to be saved.

[.discourse-part]
Answer: I know that is most men`'s dependance, and faith we all think we have:
but is it a faith that purifies the heart,
and makes our bodies fit temples for the Holy Spirit?

Paul put the Corinthians on an examination of themselves,
on a trial and proof of their faith, and it would not be amiss,
if all that account themselves believers did prove their faith by the same touchstone;
"`Do you not know,`" said Paul, "`that Christ is in you, unless you are reprobates?`"
Was Christ in the Corinthians?
And is he not in all men that turn from ungodliness,
and come to have their hearts purified?

How can we know the only true God, if we do not behold his presence?
How can we know our Saviour, if he be not in us, to save us from our spiritual enemies,
as Joshua was in the camp of Israel, to save them from their outward enemies?
And this is life eternal, not only to hear of a God and a Saviour, but to know him;
to feel the power of God, and to be witnesses of Christ`'s salvation;
these are believers, and true believers, for their eyes have seen what they believe.

Faith and works of righteousness go together; he that has the one has both,
and grace is the spring from which both proceed; the reprobate, the ungodly,
the graceless, have neither.

[.discourse-part]
_Question 9:_ If inward and spiritual grace be sufficient
to teach us our duty towards God and man,
and to establish us in righteousness; wherefore was there an outward ministry,
and to what end were apostles, prophets, evangelists, pastors, and teachers,
given to the church?

[.discourse-part]
Answer: Paul, as he told king Agrippa, was made a minister and a witness;
he was a witness of the powerful operation of grace in his own soul,
and so could tell others what it could do for them.

In the state of degeneration all men are strangers to grace, they know not the Lord;
and the work of the ministry is to open the understandings of all such,
and to turn them to this heavenly teacher;
since nothing else can enable them to lead a sober, righteous, godly life,
in this present world.

And as some were ordained to plant, so others were given to water,
that no young plant might wither before it came to be rooted and grounded.

We find that, in the primitive times, some declined from what they had attained to,
for that they kept not with their guide;
and with such Paul was forced to travail in birth again:
for as plants are not grounded as soon as they are planted,
so men are not established in righteousness as soon as they are turned from unrighteousness;
and such as were strong, were to watch over the weak,
and lend them a helping hand in their travails, until they all came,
in the unity of the Spirit, to be perfect men,
and then there is no more need of man`'s help; and we are all perfect men,
when a right Spirit comes to have the whole government in us.

But who are fit to plant and water?
No ungodly men, for such have not the Spirit of Jesus,
such know not the way of God`'s salvation themselves,
and so cannot direct others thereto, nor lend them a hand therein; but such as are,
what Paul after his conversion was, not only ministers,
but witnesses of what they testify;
or such as have travelled in the way of God`'s salvation themselves, and are come,
through the teachings of grace, to that strength and perfection,
as to deny ungodliness and worldly lusts, and to live soberly, righteously, and godly,
in this present world.
