== Walk in the Spirit (?)

The Grounds

of a

Holy Life

To which is added

Paul`'s Speech to the Bishop of Crete

by

Hugh Turford

To The Reader

Most men will acknowledge that the primitive churches, to whom Paul wrote his epistles,
exceeded in many respects the professors of Christianity in our present age;
and good grounds they have so to believe: for the said apostle, in his epistles,
told the Corinthians, That their bodies were the temples of the Holy Ghost;
he told the Ephesians, That they were fellow-citizens with the saints,
and of the household of God: he told the Philippians,
That their conversation was in heaven; he told the Colossians,
That they were delivered from the power of darkness,
and translated into the kingdom of the dear Son of God; he told the Hebrews,
That they were come to the city of the living God, the heavenly Jerusalem.
And Peter, in his general epistle to the churches, told them,
That they were a chosen generation, a royal priesthood, a holy nation,
a peculiar people.

But is this our state?
Can we say, from a sensible feeling, that the Holy Spirit of God dwells in us?
that our bodies are the temples, in which we may behold his presence, feel his power,
fear, worship, and serve him: Can we say that our conversations are in heaven?
that we are translated into the kingdom of the dear Son of God,
and live under the sceptre of his government?
that we are come to the heavenly Jerusalem,
where the great God is worshipped in spirit and in truth?
Or, are we not strangers to all these things,
and yet persuade ourselves that we are the people of God, and good Christians?

The primitive churches had the honorable name of saints;
we can give ourselves no better name than miserable sinners; and what is the reason?
Most +++[+++in]
the forementioned churches, before their conversion, were but heathens;
they were not born of Christian parents, nor trained up in the Christian faith,
as we think we are; and after conversion they had but little preaching,
in comparison to what we have;
neither were they furnished with books so plentifully as we are.

We cannot conclude that the kingdom of Christ, that then appeared in power,
did (as the sun in the firmament sometimes doth) shew itself in a morning,
and be no more seen all day: for the kingdom of Christ is an everlasting kingdom,
and the new covenant that was made with the house of Jacob an everlasting covenant.
Neither may we conclude that God hath withdrawn himself from the children of men;
for he never forsakes us, unless we first forsake him.

The apostle foresaw that there would be a falling away from
the grace in which many primitive Christians were established:
which soon after his decease came to pass.
But our preachers say, "`That the dark night of apostasy is over,
and that we live in gospel days again;`" but if so, where are the fruits?
We may, I confess, hear gospel words;
but where is the gospel power by which believers come to be the sons of God,
and to bear his image in righteousness?
Why are not we, who are called Christians,
grown to the stature of them that were born Heathens,
and brought up in blindness and ignorance: Why are not we sanctified,
and made a holy people, as well as they?
Why are not our bodies cleansed, and made a habitation for the eternal Spirit,
as theirs were?
Why are not our conversations in heaven, or at least more heavenly than they be?
The reason to me is this,
we have not built upon the same foundation that they built upon:
for this we are to understand, that the Heathens had not the Scriptures as we have,
and so could not frame a form of godliness therefrom, as many since have done,
made up with good words, calling that godliness,
and resting in an outward performance thereof, without any true conversion,
or sense of that inward life and power, that the primitive Christians came to feel,
and found in themselves through faith,
and the operation of the eternal quickening Spirit of Jesus.

The Heathens, as well as others, were of God`'s creation,
(all nations being made of one blood,) and so had in themselves, as every man hath,
a good spirit, as well as a bad; light, as well as darkness;
something that reproved them for sin, as well as something that tempted them to sin.
And being, by the Apostle, turned from the darkness that was in them, to the light;
from that which tempted them to sin, to that which convicted and reproved them for sin;
they cleaved thereunto, confided therein, and became followers thereof:
and by cleaving to the good, they were delivered from evil; by following the light,
they came to be translated out of the kingdom of darkness,
and to have their conversations in heaven, whilst they were upon earth.

These built on a sure rock, a living foundation, on Christ, as he in all ages was,
and still is, in his spiritual appearance, the light of the world,
and the life of righteousness; and,
taking his eternal Spirit in themselves for their guide,
turned from whatsoever they were thereby convicted of, and reproved for; by which Esau,
or the first nature, came to be supplanted, and He, whose right it is to reign,
came to have the rule in them, and the government over them.
And, as the darkness that eclipsed the brightness of the
sun of righteousness in them came to be removed,
they came to have a clear discerning what was of God, and what was selfish,
and to be denied; and, turning from every motion that was not of God,
the body of sin became mortified, their insides became cleansed,
the lump became leavened; such as were carnal became spiritual;
and this made them a peculiar people.

And did we walk in their footsteps, we might rise to their attainment;
but if we build on words, and outward services without spirit and life,
we can never rise; for, as Paul said in another case,
"`If I speak with the tongue of men and angels, and have not charity,
I am become as sounding brass:`" so, say I in this case, if we hear men and angels,
if we could live continually under the sound of good words,
if we have no regard to that inward light which discovers the rising of evil motions,
and power from God to turn from them, we can never mortify sin, cleanse our souls,
and become a holy people.
The work of sanctification is inward, and to be effected by inward means;
nothing but inward light can expel inward darkness;
nothing less than eternal life can deliver our souls from the power of death.

Since men came to be persuaded that though they sow tares, they shall reap wheat;
though they go down into the grave sinners, they shall rise saints,
and attain in another world what the primitive Christians attained to in this world;
their conversations have not been in heaven, but in the earth;
they have walked in darkness, and not in the light;
the god of this world hath been served, and not the God of heaven.
And what future happiness this can produce, let the wise in heart judge.

GROUNDS OF A HOLY LIFE

PAUL, in his Epistle to the Galatians, chap. v. 16. had this saying,
"`Walk in the Spirit, and ye shall not fulfill the lust of the flesh.`"
And, in his Epistle to the Romans, chap. viii. 13, he had this saying,
"`If ye live after the flesh, ye shall die;
but if ye through the Spirit do mortify the deeds of the body, ye shall live.`"
If ever scriptures were written for our learning, these scriptures were;
for much may be learned therefrom.
The end of preaching, in our present age, and many ages past, hath been,
that the sons and daughters of men might learn thereby to deny, turn from,
and forsake every evil deed; and come to live a sober, righteous,
godly life in this present world,
that they might have peace with God in their own consciences here,
and eternal life hereafter.

Now to effect this great work,
in which thousands of laborers have for many years been employed,
the apostle gives this short exhortation:
"`Walk in the Spirit,`" affirming unto the Galatians, that if they walked in the Spirit,
they should not fulfill the lusts of the flesh; they should not yield to evil motions,
nor satisfy their carnal desires; which is the only way to mortify the deeds of the body,
and cure all spiritual infirmities.
But this way of God`'s salvation hath been so long rejected,
that few in our present age know what this Spirit is,
where they may have acquaintance therewith, or how they may walk therein.
And that our understanding may be opened in this weighty concern, let us consider,

1+++.+++ What Paul was, and how he came to be a gospel minister.

2+++.+++ What the people were to whom he wrote those epistles.

3+++.+++ What the apostle called flesh and spirit, and wherein we walk after them.

4+++.+++ What we are to understand by his words die and live.

5+++.+++ How we may, through the Spirit, mortify the deeds of the body.

By reading the Scriptures we may find, that Paul was an Israelite,
of the seed of Abraham, and brought up a scholar, well instructed in the law;
and as to his religion, he was a Pharisee.
And what were the Pharisees?
Not a loose, profane people; but, in outward appearance, a very religious people,
zealous for their temple and the service thereof, with all other outward observations;
insomuch that Jesus said of them,
that they make clean "`the outside of the cup and the platter;`" which few now do.

But when the time drew nigh,
in which God would be no longer worshipped in temples made with hands,
but would dwell in, and be worshipped by, sanctified hearts;
and that the laws that were written by that great prophet Moses,
for the house of Israel to observe and walk in,
must no longer be a rule of righteousness,
but Jews and Gentiles must walk by a law proceeding
from the Spirit of God in their inward parts;
when a greater than Moses was come, proclaiming a kingdom at hand,
that consisted of a more excellent righteousness than theirs,
testifying to the faces of those outside worshippers, that,
notwithstanding their great zeal for the temple and the service thereof,
they were but hypocrites and blind guides;--the rulers
of those people were greatly offended,
and, having a bitter spirit notwithstanding their outside righteousness,
endeavored by persecution, to stop the coming of that kingdom; murdering the prince,
and imprisoning his subjects.
In which persecution none was more active than Paul, wasting the churches beyond measure.

But in the height of his persecution, not man, but God, put a stop to his proceedings;
shewing him, that it was not men, but Christ in men, that he persecuted:
which was really so; for had not Christ, by his eternal Spirit,
been in those men whom Paul persecuted,
opening the eyes of their understandings to see the emptiness of all shadows,
and to turn from them, Paul would have had nothing to say to them;
but they inclining to the worship of God in spirit, and slighting temple-worship,
Paul looked upon them as a people not worthy to live.

But it pleased God to reveal in Paul the same Christ that he persecuted in others;
and that revelation, or inward knowledge of Christ,
was the foundation of all Paul`'s knowledge in the mystery of godliness.
He had not his future teaching from men, nor from books,
but from the operation of the eternal Spirit of Jesus in himself;
for keeping to the leading of that Spirit, he grew in grace; and as he grew in grace,
he grew in the knowledge of Christ, and so went not up to Jerusalem,
to them who were apostles before him, for instructions or orders:
but in the strength of the Lord, with a book of experiences in his heart,
instead of a bible in his hand, he went into Arabia to preach the gospel to the Heathen.
And what foundation did he lay?
Not circumcision, which was the foundation of the Jews religion; nor John`'s baptism,
which since became the foundation of the Christian religion: for he told the Corinthians,
that Christ did not send him to baptize, but to preach; and thanked God,
that he baptized no more of them than Crispus and Gaius, and the household of Stephanus.

As Paul`'s eyes were then open to see the gift of God in himself,
so his work was to open the eyes of others,
that they might see the gift of God in themselves also.

Those Heathens had, as every man that cometh into the world hath, an inward light,
that shewed them, as it shows us, what is right, and what is wrong; what is just,
and what is unjust:
though in their ignorance they might have as little
regard thereunto as any of us now have.

As the kingdom of heaven consisteth of righteousness,
Paul`'s work was to reduce those people to a righteous life and heavenly conversation.
And what better foundation could any man lay, in order to a righteous life,
than a light in ourselves, that shines continually, manifesting every unrighteous action?
A guide that, truly followed, will lead unto God, from whom, by unrighteous living,
all men depart.
This, Paul experienced, and his experiences made him an able minister,
capable of preaching without book or study, and confidently to affirm unto the Galatians,
that their way to a righteous life, was to walk in the Spirit; or to keep to this guide.

And thus have I shewn how Paul came to be a gospel minister: and now I shall shew,
what the people were to whom he wrote those epistles.

The Romans and Galatians, before their conversion, were called Heathens,
for they knew not the true God, but worshipped dumb idols.
A people that lived, as too many now do, in all manner of ungodliness, walking,
as Paul told the Ephesians,
"`according to the prince of the power of the air;`" but being turned from their darkness,
became acquainted with this true light, which never consented to any unrighteous action.

To this light many of those Heathens turned, taking it for their guide,
and confiding therein as a sure foundation;
which was true faith in him who was given for a light to the Gentiles,
and one in nature with the faith of Abraham.

This people became convinced, though many of us are not,
that after they were turned unto the Lord, they had a race to run.
As from God and godliness they had departed, so to God and godliness they were to return.
They did not content themselves, as too many of us do, with a Christian name;
but following this leader, they walked in newness of life, sober, righteous, and godly,
which Paul commended, telling the Galatians that they ran well:
and we should run well also, if we ran the like race; growing, from day to day,
more just, more upright, more honest, more faithful, and more circumspect:
which cannot be expected until we take their guide for our leader.

But the churches of Galatia, being at that time, as Paul called them, little children,
a people of small growth in the knowledge of the mystery of godliness, were by some,
whom Paul wished cut off, persuaded, as many now are, that an upright, sober, godly life,
and blameless conversation, was not enough:
but they must be also in the exercise of some outward worship;
and the Jews`' religion carrying the greatest shew of godliness,
they were persuaded to imitate their customs and observations.

But Paul,
having experienced the insufficiency of outward services to change men`'s natures,
and reduce them to a righteous life, told the Galatians, that if they were circumcised,
Christ should profit them nothing.
If they went from an inward guide, to rest, as the zealous Pharisees did,
on outward performances, he that was given for a light and a leader,
would not be their light, nor their leader.
And, indeed, nothing is more evident; for if Christ be the way,
if walking by the Spirit be the means, by which we must mortify sin,
and come to a righteous life; whosoever goeth from this way,
whosoever slighteth this means, hath no more benefit by Christ,
than a traveller that forsaketh his guide hath from his guide,
in order to a righteous godly life.

As Christ is a quickening spirit,
it must be by following him in his spiritual manifestations,
that a righteous life is recovered; nothing less can change our natures,
and make us new creatures; and until we are new creatures,
our conversations cannot be in heaven.

So the epistles of Paul were written to a people
who were on their journey from death to life;
they were come out of Egypt, but not come to the promised land;
they were turned from their darkness, and had their faces Sion-ward,
but were not come to the New Jerusalem, the city of God; they had begun in the Spirit,
but were not come to the true worship in spirit; they had received Christ,
but were not rooted and grounded in Christ: and to perfect what was begun,
the apostle put them on nothing but this,
"`Walk in the Spirit:`" keep to your inward guide, the light of righteousness,
for it is that alone that can raise the sons and daughters of men from their fall,
and bring them to a life of righteousness.

The third thing to be considered is, what the apostle calls flesh and spirit,
and wherein we walk after them.

It is evident, that flesh and spirit are both leaders,
otherwise we could not walk after them; and if leaders,
our visible parts must be followers,
bringing forth in our words and deeds what is in our hearts, or conceived in our minds:
for every deed hath first a thought, either good or evil.
Evil thoughts arise from that which Paul called flesh:
good thoughts proceed from that which he called spirit.
So then flesh and spirit is a root of evil, and a spring of good, in ourselves.

From the flesh proceed all such motions as lead unto vice:
from the Spirit proceed such doubts as we find in ourselves of yielding thereunto;
and all the rebukes that follow us when we have suffered the enemy to prevail over us;
and those rebukes are in love unto us, as our rebukes are in love to our children,
that they may stand in awe, and not offend.

As oft as we yield to evil motions, we give place to the devil;
and whosoever yields to one evil motion, shall have another of the same kind:
and the oftener we yield, the more ground he hath in us,
and the more power he comes to have over us.
And all the refuge that any man hath to fly unto, when evil motions arise,
is that in his own heart, that Paul calls the Spirit,
for that will not consent to any evil deed; and whosoever keeps close to that,
keeps close to God; they abide with their guide, and "`walk in the Spirit.`"

The converted Heathens walked by this rule;
they took the eternal Spirit of Christ in themselves for their guide:
they confided therein, and became followers thereof;
and that brought them to be a holy nation, and a peculiar people.
And we should be the same did we turn to this eternal Spirit in our own hearts,
and order our conversations according to the leadings and guidings thereof;
for keeping to this, we should not fulfill the deeds of the flesh.

The fourth thing to be considered is, what the Apostle intended by these words,
die and live.

Certainly he did not, by the word die, intend a cessation of their mortal lives,
for such a dying in the Lord`'s appointed time is common to all men;
they that live after the Spirit, as well as they who walk after the flesh,
must go down into the grave.

But the dying that the Apostle intended, was a decay of our inward life,
a dying unto righteousness; which few in our present age take notice of:
such a dying as the first man Adam died,
when he fell from the government of the eternal Spirit, which was man`'s first state;
or such a dying as the house of Israel died, when they stuck to outward observations,
slighting justice, mercy, and a humble walking with their God.

Now such as walk after the flesh, living in the practice of any known sin,
depart further from God, and come to have less life, less light, less grace,
less fear of offending God, and injuring their neighbors;
as we may see by men`'s conversations.
And this decrease is a dying unto righteousness.

And as they that live after the flesh, have less life, less light, less grace, less fear;
so such as walk after the Spirit, doing such things as are upright, honest,
and of good report, from a principle in their own hearts, find an increase;
they come to have more life, more light, more grace, more fear of offending God,
or their neighbor: and this increase is a living unto righteousness.
As the one goes further from, so the other draws nearer to, the kingdom of heaven.

Had we not in ourselves spirit as well as flesh; light as well as darkness;
a conductor in the way of life and salvation,
as well as a leader in the paths of destruction; we might lay the loss of life,
and all the calamities that sin brings, on Adam`'s score,
or on the account of the wicked one, from whom all wicked motions proceed.

Paul was an expert doctor in divinity;
he knew what corrupted the sons and daughters of men,
and from whence all the ungodliness that is in the world doth arise; and to cleanse,
to purge, to purify, to make Heathens become sound Christians, and sinners become saints,
describes no other means but this, "`Walk in the Spirit.`"
For as we keep to this, we shall learn, as the converted Heathens did,
not only to deny ungodliness, but also to live godly in this present world.

But if we rest, as the zealous Pharisees did, in outward performances,
accounting ourselves righteous, because we have, as we are persuaded,
a right form of godliness, and make no use of the aforesaid means;
though we have as great a zeal for our forms of godliness,
as ever Paul had for the Jews`' religion,
it will profit us no more than circumcision would have profited the Galatians.

We have had much preaching and teaching;
the joys of heaven promised to them that did well;
the torments of hell threatened to them that did ill;
but have these promises and threatenings made us a holy nation, and a peculiar people,
exceeding all others for justice, equity, truth, and faithfulness?
Have all the exhortations that we have had, enabled us to mortify the body of sin,
which is the cause of ungodliness?
Are we thereby translated, as the Heathens were,
out of the region of darkness into the kingdom of the dear Son of God,
so as to have our conversations in heaven, whilst our bodies are on earth?
Can we say, "`Old things are done away,`" all exalted thoughts,
all covetous inclinations, all wrath and bitterness;
and these new things come in their places, humility, meekness, temperance, self-denial,
with unfeigned love to God, and our neighbor?
Can we say, There was a time in which sin had such dominion over us,
that we could not refrain from fulfilling the lusts of the flesh;
but now we are so limited by the eternal Spirit, that we must be temperate,
we must be sober and vigilant, we must be just, upright, and faithful in word and deed.
If this be our state, we are, as the primitive Christians were at their full attainments,
dead unto sin, and alive unto righteousness: built upon the same rock as they were.
But if we are not come to this, it would be our wisdom to turn to the Lord, as they did,
and build on the same foundation that they built upon,
"`The true light that enlightens every man that cometh into the
world;`" that we may come to be acquainted with the eternal Spirit,
as they were, and have a guide and leader in the paths of godliness, as they had;
for it is by and through the assistance of the eternal Spirit of
Jesus in our own hearts that our corruptions must be purged out,
and our inside made clean.
For as our walking after the flesh made all wounds;
so it must be our walking after the Spirit that must heal all wounds;
as our living after the flesh was the growth of our unrighteousness;
so by walking after the Spirit we mortify sin, and recover a life of righteousness.

Paul spoke from a good understanding, when he told the Romans,
"`That which may be known of God is manifest within:`"
there he had his knowledge in the mysteries of godliness:
whatever he preached, whatever he wrote, the spring was in himself.
He knew no more of the operation of inward and spiritual grace than one of us,
`'till he came to have his eyes inward, and to walk in the Spirit;
and so he recommended to the churches what he had experienced.

Many can talk of redemption, justification, sanctification, and salvation by Christ:
but he is a Christian who is a witness of such things wrought in himself.
Such may properly be called learned men: they know what it is to rise, what it is to die,
and what it is to live; what they are redeemed and saved from, and by what means.

The fifth thing to be considered is, how the sons and daughters of men may,
through the Spirit, mortify the deeds of the body.

But first, we will consider, what deeds of the body are to be mortified;
which in general are these: as an evil spirit in man is the root of all evil deeds,
so every deed that proceeds from that root is to be mortified:
and nothing can manifest such deeds, giving us a true sight thereof,
but the Spirit of the Lord, or light of righteousness in our own hearts,
as it comes to shine in brightness.

To know what deeds are to be mortified in all our attempts and undertakings,
let us look to our ends therein; if we have nothing in our eye but justice, equity,
honesty, and plain dealings, we may go on with safety; but if self be the moving cause,
if we have not an eye to our neighbor`'s interest as well as our own,
pretend what we will, such deeds proceed from an evil root, and are to be denied;
and in denying them, they come to be mortified.
And what can manifest our ends in every action?
Not books nor preachers; but the Spirit of the Lord, which is an inward light.

But we do not find that Paul directly charged the
Galatians with any manner of loose living,
but with their "`observing days and times:`" and what harm could there be in that?

Though the Galatians might see none, Paul saw much,
otherwise he would not have asked them, Who had bewitched them?
They had begun in the Spirit, they had walked for a season after an inward guide,
which is the only leader to such a life of righteousness as the Lord, in all ages,
required of the sons and daughters of men;
which was not a form of godliness without life, but truth in their inward parts:
for if we have truth in our hearts, equity will be performed by our hands.

And to this Paul knew they could never come by imitating an outward worship,
much less by observing days and times,
(which in our present age is become the nursery of vice) and so counted it +++[+++of the]
deeds of the flesh: reasoning thus with them, "`Are ye so foolish,
having begun in the Spirit, are ye made perfect by the flesh?`"
Which is all one as to say, Are ye so void of understanding,
having begun to walk in newness of life,
do you think to come to such perfection as to have your
conversation in heaven whilst living on the earth,
by going back to the performance of outward services: "`This persuasion,`" said he,
"`is not of him that calleth you.`"
And if it was not of God, it must be from the old deceiver;
and many have been since deceived thereby, persuading themselves,
that godliness consisteth in that which is called, but is not, true devotion,
and not in a well ordered conversation, and so live in pride, covetousness, envy,
and many other things, which are really deeds of the flesh;
and never come so far as to mind a translation out of the kingdom of darkness;
to live under the government of the eternal Spirit.

Man`'s fall was not from any outward religion or form of godliness,
but from a life of righteousness: from a state in which husband, wife, parents, children,
masters, servants, and all other relations, would have known their place and duty,
and been found therein: from a state in which the creatures,
that God hath given for man`'s use, would have been used, and none of them,
through excess, wasted or abused:
from a state in which truth would have been found in our words,
and equity in all our deeds:
from a state in which the will of God would have been done on earth,
as it is done in heaven, and the great God by us glorified, and not dishonored.
From this state, through the entrance and growth of sin,
the sons and daughters of men are departed; to this state the primitive Christians,
through the mortification of sin, returned.

This was the life that the first Adam lost:
this is the life that the second Adam came to recover.
As many as have the Spirit of Christ, and become followers thereof, rise from their fall,
return unto God, live under his government, and become witnesses of this life restored.

When I have looked upon that called the book of divine service,
I have found as good words therein as could be collected out of the scriptures;
not one to be admitted into the church without security,
promising in their behalf as much as I have mentioned.
The promises therein contained, were they but truly performed,
would make us a holy nation, no way behind the chiefest of saints.
For those that rose highest,
rose no higher than to "`walk in God`'s commands all the days of their lives.`"

But it is rare to find one man that performs that covenant, and the reason is this;
we say the scriptures are our rule, but we keep not thereunto.
Paul`'s advice is not followed, we do not "`walk in the Spirit;`" which if we did,
the light of righteousness, in our own hearts would shew us the risings of evil motions,
and what they lead to; and that is the time to "`forsake the devil and all his works,
with all worldly vanities and sinful lusts:`" for if we deny evil motions,
we shall never be found in evil actions; and until we depart from evil,
we cannot do the things that are good.
Sin must be mortified before we can lead a righteous life:
the works of the devil must be denied, before the commands of our God can be walked in,
one day, much less all the days of our lives.

And this Paul experienced, which made him with great confidence to say,
"`Walk in the Spirit, and ye shall not fulfill the lust of the flesh.`"
For if we deny and turn from every motion that the light
of righteousness in our own hearts shews us to be evil,
we shall not fulfill them, but shall mortify the root from whence they arise:
for that which is not fed, in time comes to die.

By this the converted Heathens came to be a holy nation:
this is the way to be citizens of the New Jerusalem: by this means the Colossians were,
and we may be, translated into the kingdom of the dear Son of God,
to live under his government: this is the kingdom that,
John the Baptist proclaimed to be then at hand;
this is the kingdom that the disciples of Christ were to pray for the coming of:
this is the kingdom that consisteth of righteousness, and standeth in power:
this is the kingdom that all believers are first to seek:
for under the government of the eternal Spirit of Jesus in their hearts,
the sons and daughters of men are limited from doing any unrighteous thing.

Many of the present professors of Christianity are persuaded,
that though they are unrighteous in their lives,
yet being in the exercise of something called religion, it shall go well with them.
But the living Lord doth not take notice what religion we are of,
but what leader we follow; for let our religion be what it will,
if we live after the flesh, we shall die.
And, though little appears that is called religion, if we walk after the Spirit,
if our conversation be in heaven, if truth be in our mouths,
and equity performed by our hands, we shall live.
But who are capable of walking after the Spirit, and through the Spirit,
of mortifying the deeds of the body?

We may find many, even amongst us, who bear the name of Christians, that,
through a perseverance in evil-doing, are become dead in sin,
having no sense or feeling of any thing in themselves that is of God:
and such as have no acquaintance with the Spirit, cannot "`walk after the Spirit.`"

Others there are who are not dead, but dying; they have both sense and feeling;
they have that in themselves that would lead them to better things than they practise,
but have little or no regard thereunto; they take it not for their guide;
and whilst they slight that in themselves which manifests the deeds of the body,
they can in no wise mortify them.

But some may be found who are weary of their sins, and burdened with their iniquities,
having in themselves a hunger and thirst after righteousness;
and all such are living people, and capable through the Spirit,
of mortifying the deeds of the body.

Satisfied I am, that in our present age, many have been awakened from the sleep of sin,
and have had in themselves a true hunger and thirst after righteousness;
but being awakened by an outward ministry,
from that they expected to have their hunger and thirst satisfied.

Many may be awakened with, but they are not quickened by, an outward ministry;
"`It is,`" as Jesus said, "`the Spirit that quickeneth;`" what can raise life,
but that which giveth life?
What can satisfy a soul that thirsteth after righteousness,
but that which is in very truth the spring of righteousness?
It is in ourselves the well is to be found,
that whosoever drinketh thereof shall never thirst;
there is the spring that floweth up unto everlasting life.

As the kingdom of heaven stands not in words, but in power; so it is not words,
but the power of God that can mortify the deeds of the body, change our nature,
and make us new creatures.

Would words fill us with righteousness, justice, truth, equity, and faithfulness,
we should have been a holy nation long since; for there hath been no want of words,
but there is still want of equity and faithfulness in men`'s deeds.

Could good words reduce hearers to a righteous life,
instead of saying,"`Walk in the Spirit,`" Paul would have said to the Galatians,
"`Hearken to your minister:`" he would have had no
need to have recommended unto them an inward guide.
Paul`'s experience evidenced unto him, that it was not by hearing of words,
but through his obedience to the law of the Spirit,
that he came to mortify the deeds of the body, and lead a righteous life:
and what he found to be effectual in himself, that he recommended to the churches.

Words, though never so numerous, may be forgotten, they do not abide;
but the eternal Spirit abides,
that is the teacher that can never be removed into a corner.
The use of words, in the work of salvation, is to awaken such who are asleep in sin,
and to turn them, as Paul turned the Heathens, to an inward guide; and for admonition,
whilst they are on their journey, to keep with their guide.

Had such, who hungered and thirsted after righteousness,
pressed after what they hungered for;
had they acquainted themselves with the eternal Spirit, that begot those desires,
and followed the leading thereof, it would have rooted out pride and all selfishness;
it would have reduced them to a humble, lowly, meek, patient, peaceable frame,
to keep their promises, to be just in all their dealings,
to do the thing that was right at all times; and this would have removed their burden,
and given them rest and peace.

If we would be as the primitive Christians were, we must begin where they did;
we must turn to the light of righteousness in our own hearts,
and walk in that light until we become children of the light;
we must walk in the just man`'s path by the guidings thereof,
till righteousness becomes our centre.
This made the primitive Christians a religious people indeed; by this they profited;
otherwise the blind ignorant Heathens could not have
come to be fellow-citizens with saints,
and of the household of God.

Paul was no settled minister at any one place, they heard him but seldom;
but they heard the voice of the eternal Spirit, as oft as they strayed from justice,
equity, and faithfulness: and to this voice Christians ought to incline their ear;
for under the new covenant, God doth speak unto his people by his Son,
through the eternal Spirit in their hearts.

The first step to a life of righteousness,
is to acquaint ourselves with that in our own hearts that reproves us for unrighteousness:
for until we come to this, we are strangers to the foundation of a right conversation:
for all building, all journeying, all rising, all approaching,
near to the kingdom of God, depends on our denying, turning from,
and utterly forsaking what the light of righteousness
in our own hearts doth convict us of,
and reprove us for: for by such denials the deeds of the body come to be mortified.
As we make this our concern, and are faithful therein, our light shines more and more;
and the more light we have, the greater discovery it makes of what is evil,
what is to be denied, turned from, and forsaken; and guiding our steps by this,
we build on the true foundation, we walk in the living way,
we grow in grace and the knowledge of Christ,
and draw nearer and nearer to his kingdom and righteous government;
and all power is felt in a righteous life.

This was the advice of Christ, "`Strive to enter in at the strait gate;`" testifying,
that the way to eternal life was narrow; and what is this strait gate, and narrow way?
Not self-interest, nor yet self-righteousness.

Self-interest is the root of all covetous practices, fraudulent dealings,
and unjust actions.
Self-righteousness is the root of all formality and contention about religion,
of which there hath been, and still is, too much in the Christian world,
persecuting one another, as the unconverted Heathens did the primitive converts.

Neither of these paths leads to that kingdom that consists of righteousness and peace.
Had the converted Heathens walked in these paths, they would not have been a holy nation;
their conversations would have been in the earth, and not in heaven.
But the strait gate, and narrow way, that leads to a righteous life, is self-denial;
a denying of everything, the smallest concern, as well as things that seem weighty,
proceeding from an evil root; which nothing can manifest but an inward light,
shining in its brightness.
But with sorrow may we say, it is rare to find one amongst many,
who lives in the practice of what he himself acknowledgeth to be right.
Who is there but will confess, that to speak the truth on all occasions is a right thing?
Who is there but will allow, that to keep every promise, though it be to our hurt,
is an honest thing?
Who is there but will grant, that to do unto all men as we would be done by,
is a just thing?
Yet few live in the practice thereof;
and if we do not live in the practice of what we know to be right,
what doth our knowledge profit us?
We may, as Israel in the wilderness did, keep moving;
but unless we walk in the narrow way, we can never come to a righteous life.

And so, if we do not willfully shut our eyes, we may plainly see;
that the way to a righteous life,
is to "`walk in the Spirit;`" to follow the leadings of an inward guide;
to deny and turn from what the light of righteousness in our own hearts manifests,
unto us to be unrighteous, unjust, or dishonest.
And by turning from evil, we come to embrace the good; by forsaking vice,
we come to be filled with virtue; by dying unto sin,
we come to be made alive unto righteousness; truth, equity, and honesty,
come to be uppermost, and we come to centre there.
And to such, as Paul said,
"`There is no condemnation;`" they have the answer of a good conscience; peace with God,
and peace in themselves; peace whilst they are here, and peace when they go hence.

=== Considerations Grounded On The Foregoing Discourse

Man was made, as many will acknowledge, to glorify God, and to do his will on earth:
and that man might be capable of serving his Creator according to his will,
God gave him a measure of his good Spirit for an instructor; so that there was in man,
as he was first created, much of God, much humility and meekness,
much truth and faithfulness, much heavenly wisdom and understanding.

This eternal Spirit was to be man`'s head and leader, man`'s guide and instructor,
in the paths of righteousness.
On this Spirit man was to fix his eye; to this Spirit man was to incline his ear;
by this Spirit man was to be governed; and so following this guide, this leader,
and this instructor, man would have been capable of governing himself,
and the creation over which he was made lord, according to the will of God.

Did mankind live under the government of this eternal Spirit,
we should all bear the image of God; we should be all godly, humble, lowly, meek,
merciful, patient, peaceable, upright, and faithful; right in all our ways,
and just in all our works.

But man, not keeping with this guide, disobeys the command of his Maker;
and by yielding himself servant to another master, another spirit enters,
as contrary in nature as darkness is to light:
and as many as follow this leader serve not the God of heaven, but the god of this world:
for every man is a servant to whom he obeys.

Now we, being all the offspring of Adam in his fallen state, bear his likeness;
we have all in ourselves, good and evil, a seed of grace, and a seed of sin,
called in scripture, light and darkness, flesh and spirit, the old man and new man,
according to the growth of the seeds in us,
and the dominion that they come to have over us;
for as there is a difference between a seed and an herb, a plant and a tree,
a child and a man; so there is a difference in grace, and also in sin:
according to its growth in us, so is the strength thereof felt by us,
and the names given in scripture are answerable thereto.

For though we have all a seed of sin in us, we are not over mastered therewith,
nor captivated thereby, as soon as we are born:
it must have a time to spring and grow in us, before it comes to have dominion over us.
And I may say the same of the seed of grace, for it is also of a growing kind;
otherwise the kingdom of heaven, or government of Christ in the hearts of his people,
would not have been compared to the seed of mustard, which,
though it be but small when it is sown, yet through the springing and growth thereof,
comes to be of a high Stature.

We may find many in the world who are notoriously wicked,
and much more wicked would they appear, were they not limited by an outward law:
these were not so born; it is the growth of sin, and the dominion,
that it comes to have over men, that makes them notoriously wicked; for the seed of sin,
as it comes to full growth in any of the sons and daughters of men,
converts them into its own nature,
by which they come to be habitually active in wickedness.

This was the devil`'s aim in Adam`'s fall, but his design being not then fully effected,
he hath followed in all ages of the world, and at this day doth follow,
the sons and daughters of men,
putting in their minds evil motions attended with various temptations,
displaying false colors, and putting a more beautiful gloss on things forbidden,
than fallen men can see in paths of righteousness.
And all his evil motions, temptations, baits, snares, lures, and false colors,
are to effect his first design, that we being taken therewith, and led away thereby,
might forget God, and cause him to take his Holy Spirit from us; for till then,
the god of this world can call no man his own; we may be his captives,
but he hath not the whole dominion over us.

In our present age, light within, a law within, Spirit within, Christ within,
is the scoffing of some, and little regarded by many: but whether they know it or not,
I must tell them,
they scoff and slight the chiefest treasure that
ever the soul of any man was possessed of;
they slight the talent that God hath given to every man to improve,
in order to their rising from their fall, and returning to their native country,
to live under the government of the eternal Spirit.
Whosoever is without Spirit and light within, is without God in the world.
Take away this treasure, and we shall have nothing in us that is good:
we shall be left quite graceless.

We read of Jacob and Esau, who were lively figures of these two seeds in man,
how they struggled whilst they were in the womb of Rebecca.

And as there was a struggling between the seed of two nations in the womb of Rebecca,
so there is a struggling between the seed of two kingdoms in every man,
which shall rise to rule in us, and to have the whole dominion over us.

As we are born into the world, we are all innocent; though we have a seed of sin in us,
we are not actual sinners, until we yield to some sinful motion proceeding therefrom:
which the devil knows, though many are of another persuasion.
And that the seed which he hath sown may spring and grow,
that an evil spirit may come to have the rule in us, he begins to struggle betimes,
before we well know the right hand from the left:
and where vice is not kept down by careful parents, or guardians, it quickly gets head;
and such may say, as many do, "`That there is no good thing in us,`"

For, through the speedy growth of that which is evil,
they never have any acquaintance with that which is good, except inward rebukes,
which few will acknowledge to be of God.
For as weeds left to grow in a garden overshadow and keep down herbs,
so that they cannot grow; so doth vice suppress virtue,
and make God`'s creation such strangers to their Creator, that though in him they live,
move, and have their being, yet are they without sense or feeling of his presence.

And as all evil motions that lead unto sin, all baits, snares, and lures,
that we meet with in the course of our lives,
are the strugglings and strivings of the evil seed;
so all calls that we find in ourselves for justice, equity, honesty, truth,
and faithfulness, with all inward checks, rebukes, and convictions,
are the strugglings and strivings of the good seed;
for if these things are hearkened unto, obeyed, followed after, and lived in,
they keep down the growth of vice; so that though we have a root of sin in us,
it remains powerless; it doth not rise and come to reign over us.

In which suppressing of vice, in order to the growth of virtue,
parents and guardians ought to be much concerned;
for as the wicked one takes the advantage of our childhood, to make us commit evil,
before we have any acquaintance with that which is good; parents and guardians,
like faithful weeders, should eye, suppress, keep down,
and use all endeavors to root out every vice as soon as it appears, till grace grows,
and a right spirit comes to reign in them, and have the rule over them.

But this is our present state:
as Esau by his struggling came to be the first-born in days past; so iniquity,
through the early rising of the subtle serpent, is the first-born still.
And though most parents, in the Christian world, are careful to provide weeders betimes,
almost as soon as a child is born, yet few weeds do they root up;
and many parents none at all; by which great neglect, most children come to be wild,
stubborn, self-willed, disobedient to parents, and very ungodly in their lives.
But the ground of all ungodliness is the growth of that seed which the wicked one sowed.
And how may vice be brought down when it is come to a head?
Not by parents, not by guardians, not by sureties, and I may say, not by preachers:
but as it was Jacob that supplanted Esau, so it must be grace that must supplant sin.
We see, notwithstanding all preaching, more pride and haughtiness,
than humility and meekness; more fraudulent dealings, and contentious practices,
than self-denial; more seeking the world, and the vanities thereof,
than the kingdom of heaven, and the righteousness thereof.
And thus it will be whilst the firstborn is uppermost.

And if we would have the firstborn supplanted;
if we would have that which strives to deprive us of life, light, and grace,
and all goodness, made powerless; if we would have that suppressed,
which continually labors to make us servants to sin, and bond-slaves to Satan;
if we would see the death of that which makes us
incapable of glorifying God in our lives;
if we would be, as the primitive Christians were, delivered from the power of darkness,
and translated into the kingdom of the dear Son of God,
to live under the government of his eternal Spirit, which was man`'s first state;
let us consider, how that which hinders came to rise,
and by what means it may be brought down.

I have said, and say again, that it is not the indwelling,
but the growth of an evil seed, that makes the sons and daughters of men proud, haughty,
high-minded, envious, cruel, merciless, fraudulent, and ungodly;
darkening their understandings,
and making them strangers to the gift of God in themselves.
And the growth of this evil seed stands in our often
yielding to such evil motions as proceed therefrom,
and that the subtle serpent knows; and we may know it also,
from the manifold temptations we have thereunto,
especially where he finds them to be effectual.

Whoever yielded to any evil motion, committing sin, and taking pleasure therein,
that hath not been tempted again to the same thing?
Or who is there that doth not know, that the oftener we yield to any temptation,
the stronger our temptations are, and the harder to be denied?
And by every yielding, this sin riseth, and comes to have more power over us.

And if it be by our yielding to evil motions that the evil spirit riseth,
and comes to have power over us,
it must be by denying evil motions that he must be supplanted, and made powerless in us.

Whosoever will be a follower of Christ, must first learn to deny himself.
We must turn from whatsoever the eternal light in our own hearts shews us to be selfish,
though it may seem never so much to our disadvantage; and by denying ourselves,
we shall abundantly deny the author of all evil motions.

Pride, pleasure, and unrighteous gain, are baits that have caught many;
all which with many other things, we must deny, and turn from,
if we will be followers of Christ in a righteous life:
and by such denials we shall find the root of iniquity wither, and grace grow;
sinful motions will diminish, and heavenly desires increase;
the small seed will become the tallest of herbs;
and the lump come to be one in nature with the leaven.

But this denial must be whilst the cockatrice is yet in the shell;
whilst sin is in the motion, before it comes to action;
for sinful motions may be turned from, but sinful actions are past recall.
And what can shew us the rising of evil motions?
Preachers cannot; books cannot;
nothing that is without can effectually shew us what is within;
it must be an inward light; it must be the candle of the Lord, the eternal Spirit,
that was in the beginning given unto man for an instructor.

There were in the creation good men, faithful men, self-denying men,
when there were no preachers, nor books, that we read of:
and who was their teacher but the eternal Spirit?
What guide had they but the light of righteousness in their own hearts?
And did our present preachers make it their concern
to turn people`'s minds to eye this inward guide,
and to become faithful followers thereof, we should have more good men, faithful men,
and self-denying men, than can now be found.

Men or angels could not give better advice to a people,
that was turned to this inward light, than Paul gave to the Galatians,
when he exhorted them to "`Walk in the Spirit;`"
for if we are not guided by a right spirit,
we can never lead a righteous life.

As the seed of sin grows and waxeth strong in us by our yielding to evil motions,
so the seed of grace grows and waxeth strong in us by the denying of evil motions:
the putting off of the old man, is the putting on of the new;
and it is the new man that makes any of us to be new creatures, and to bring forth,
in the course of our lives, a new and heavenly conversation.

If we do not come to a denial of evil motions,
and to live in a continual exercise thereof,
though we hear preachers all the days of our lives,
we shall be but as the door on the hinges, or as Israel in the wilderness, often moving;
yet as short of a righteous life,
as they that then came out of Egypt were of having
peaceable possessions in the promised land.

We cannot come to a righteous life, until our lights shine with such brightness,
that we can see the rising of all evil motions at a distance:
for as grace comes to be uppermost, the root of iniquity will be lowermost;
as the one comes to be before our faces, the other will be behind our backs.

Our conversation is not in heaven, till truth comes to be in all our words,
equity in all our deeds, and faithfulness in all our promises;
this makes the sons and daughters of men a holy nation, and a peculiar people;
this makes such as were Heathens to be true Christians;
and such as were the vilest of sinners, worthy of the honorable name of saints.

Whence come pride and haughtiness, contention and strife, fraud and deceit,
oppression and cruelty, but from the author of all wickedness: Where the flesh,
with the affections thereof, is crucified, such things are not to be found; and,
let us pretend to what religion we will, whilst such things are practised,
we keep alive what ought to be mortified.

Where an evil spirit is uppermost, men know no limit; their ears, eyes, tongues, hands,
and feet, are at liberty to hear evil reports, behold vanity, speak proudly, rashly,
unadvisedly, and deceitfully, to do violence, take bribes, and go where they list.

But where a right spirit rules, every member of the body is under a limit;
the ear is turned from fables, and the eye from beholding vanity: they cannot,
as too many do, cover, dissemble, and lie, to accomplish self-ends:
vain communication is not allowed to come out of their mouths;
their hands are limited from taking bribes, using of violence, or doing any wrong;
the paths of rioters they cannot walk in, but are lovers of righteousness,
and haters of iniquity in themselves and others.
And to this estate we might all come,
by denying such motions as the light of righteousness
in our own hearts manifests to be evil.

And now my advice to all professors of Christianity is,
that instead of contending about forms of godliness,
they take heed to that in themselves which leads to godliness;
instead of searching the scriptures for a right form,
they would labor to live under the government of a right spirit;
for such are delivered from the power of darkness, and return to Sion the city of God,
and to the New Jerusalem, where God is known and truly worshipped.

One thing more I would have the reader to consider, and that is this:
Though every man that cometh into the world is attended with two spirits,
yet can he have but one Lord, and he is Lord that hath the whole rule over thee.

The right of government, in all men, belongs to the eternal Spirit,
that was with the Father before the world began,
called in scripture the Spirit of Christ; for in Jesus, the second Adam,
no other spirit dwelt.
He was not attended with two spirits, as the offspring of fallen Adam are:
he had not in himself light and darkness, good and evil, a seed of grace,
and a seed of sin: but he was, as the Scripture saith, "`Full of grace,
and full of truth.`"
In him was life, even the life that the first Adam lost, a spring of righteousness;
and this life he retained, though his temptations far exceeded those of Eve,
and so did keep out the evil spirit, which is the author of all wickedness.
Though he lived many years on earth, and met with many provocations,
he was in the whole course of his life, humble, lowly, meek, merciful, patient,
peaceable, just, and faithful; and therein fulfilled all righteousness,
and so did the will of God on earth.

And the seed of grace in every man, is one in nature with the fulness that dwelt in him;
and as this seed springs in any of us, and grows to strength and stature,
it makes us conformable to his image.
The more grace any man hath, the more humble, meek, and merciful he is;
the more light any of us have,
the greater discovery it makes of what is amiss in ourselves and others`';
the more truth dwells in us, the less fraud and deceit is wrought by us.

And as we walk in the light, we shall grow in grace, and "`add to our faith virtue,
knowledge, temperance: patience, godliness, brotherly kindness, and charity;`" by which,
as Peter said,
"`an entrance will be ministered unto us abundantly
into the everlasting kingdom of Christ.`"
A right spirit will come to be exalted in us,
and to have the alone rule and government over us;
and under the government of a right spirit, we shall bring forth a right conversation,
acceptable in the sight of God.

Now the prince of darkness, being an enemy to all righteousness,
useth all endeavors to blind the eyes of our understanding,
and to keep us strangers to this righteous seed,
which is the spring of all grace and virtue, that he may draw us away from God,
and all godliness: and as such as walk in the light of the Lord add virtue to virtue,
until they are filled with righteousness,
so such as follow the leadings of an evil spirit, add vice to vice,
until they come to be filled with wickedness; and all such have likewise but one lord;
the prince of the power of darkness hath the whole rule over them.
And these two states are called in Scripture life and death.

Every man, as he cometh into the world, hath, as I may say,
life and salvation before him, death and destruction behind him,
and both at a distance from him:
he hath also a good spirit to conduct him in the way of life and salvation,
and an evil spirit waits to lead him in paths of death and destruction;
and most men are strangers to both, although they be in them.
And the preaching of the gospel was, and ought still to be,
for the opening of such blind eyes,
to see the working of these two spirits in themselves, and the leadings thereof,
that they might turn from the evil, and become followers of that which is good, that he,
whose right it is, might come to have the rule in them and over them.

And certain I am, that though many are ignorant of these things,
many may be found that have some sight, some sense,
and some feeling of the eternal Spirit of Jesus:
they have the knowledge of something in themselves
that calls for just weights and an equal balance,
for doing unto all men as they would be done by, for truth in their words,
and faithfulness in their promises; so that did they keep to this,
they would follow a right guide, and the seed of grace would grow,
truth and faithfulness would grow: knowledge, temperance, patience, brotherly-kindness,
and charity, would grow; and we should find in ourselves,
that an entrance into the kingdom of Christ would be abundantly administered.

But whilst the evil spirit remains unmortified, self stands in our way,
and to accomplish self-ends, an equal balance is not kept, justice is not done,
equity is not performed, promises are not kept, undertakings are not faithfully managed,
the fashions and customs of this sinful world are not forsaken;
and that hinders the growth of the righteous seed;
for as there was no bringing down of the Canaanites
whilst there was an accursed thing in the camp;
so there is no bringing down the strength of sin
whilst we have more regard to self than a Saviour;
and that which manifests self is light, by it we see to what every evil motion doth lead,
and walking in the light, we walk in the way of God`'s salvation.

But some may say of this eternal life, as wicked men and sons of Belial said of Saul,
the chosen of the Lord; "`How shall this man save us?`"
What can the taking heed to this light advantage us?
We find in ourselves rebukes for sin,
but we find nothing in ourselves to save us from sin.

To all such I have this to say,
Christ was given to the Gentiles for a light and for a leader.
Whilst we are in the nature of the Gentiles, whilst we walk after the flesh,
whilst we follow evil motions, we are departed from God,
we are aliens from the commonwealth of Israel,
and are strangers to the new covenant that God made with the house of Jacob;
and in that state we cannot know Christ the Saviour of the world,
any otherwise than as a reprover; but those reproofs, being reproofs of instruction,
are the way to life, even to that life that the first Adam through transgression lost.

For if at those reproofs we turn from such things as we are reproved, for,
whether it be idle communication, intemperate living, unjust dealing, pride, passion,
or any other vice, that the evil spirit of this world leads unto;
and follow after righteousness, doing such things as are just, upright, honest,
and of good report; rebukes will cease, and our reprover will become our leader;
that which was behind our backs, will be before our faces,
and that which would have led us, will pursue us, as Pharaoh pursued Israel,
to bring us back to our old manner of living again,
and then we shall find Christ to be our Saviour.
As many as followed Saul saw how he saved them from their outward enemies;
and all that come to be followers of the eternal Spirit of Jesus
do see how he saves them from spiritual enemies.

Whilst we follow motions of sin, we follow a wrong guide,
and in that path we may know the prevailing power of sin,
but can never know the restraining power of grace.
It is to as many as receive Christ that he gives power; and none receive him,
but such as turn from their iniquities at his reproof, and confide in him for a Saviour:
such truly believe in his name.

I grant, that the shining of an inward light,
which is the first manifestation of Christ to the sons and daughters of men,
seems at first small and powerless; and so do our first motions to sin:
but follow such sinful motions as far as they will lead,
and we shall find them powerful enough.
May not many be found at this day, even amongst us who are called Christians,
so captivated under the power of sin, that a bond-slave, who is held in chains of iron,
can easier break his bonds, arise, depart, and return unto his native country,
than they can cease from iniquity, rise from their fall, and lead a sober, righteous,
godly life.

And if the seed of sin comes, by our following the motions thereof,
to have such power over us, why may not the seed of grace, if we return whereunto,
and become followers thereof, have as much power over us?

Undoubtedly John, who had travelled from death to life,
and was an eye-witness of things as they were in the beginning,
felt in himself such a power, when he said,
"`Whosoever is born of God doth not commit sin, for his seed remaineth in him,
and he cannot sin.`"
And many living witnesses may be found at this day, who can say,
from a sensible experience, That where this righteous seed is risen,
and comes to have dominion, it is so powerful and restraining,
that they cannot be unjust in their dealings, nor unfaithful in their promises;
they cannot tell an untruth, though never so much to their outward advantage;
they cannot be intemperate,
wasting the good creatures that God hath given for their nourishment,
by excessive eating and drinking; they cannot oppress the poor, the widow,
and fatherless, nor take by violence that which they have no right unto:
the small seed in them is become the tallest of herbs, and hath as much power over them,
as sin hath over such who dwell therein.

These are, as the Colossians were, delivered from the power of darkness; these have,
as the Philippians had, their conversation in heaven; these glorify God in their lives,
and so answer the end of their creation.

Much preaching hath made many godly talkers; but it is grace in the heart,
and truth in our inward parts, that makes godly livers.
And to a fulness of this heavenly treasure none of us can attain,
but by denying such motions as the eternal light of righteousness, in our inward parts,
shews us to be unjust and dishonest; for in denying the evil, we choose the good;
and as the growth of sin stands in our ill-doing,
so the growth of grace stands in our well-doing.

Our ancestors have told us,
that there was more honesty and plain dealing amongst men in ages past,
when there was less preaching, than can be found amongst men now.
And their saying I can easily believe; knowing that it is a true self-denial,
and not the hearing of preachers, that must mortify sin, change our natures,
and make us new creatures; which is the ground of all honesty and plain dealing.

And of this true self-denial,
I am apt to think we have much less than former generations had; for we see,
though preaching abounds, pride, covetous practices, with many other vices, super-abound:
and the reason to me is this, conformity to outward forms of worship,
being more taking with people than the strait gate and narrow way of self-denial,
hath in our present age gotten the name of religion, Christianity, and true godliness;
insomuch, that should a man add to his faith virtue, and all other graces,
by which an entrance into the everlasting kingdom of Christ is abundantly ministered,
if there be not withal a conformity to some outward way of worship,
he shall not pass for a godly man.
Nay, though his conversation be never so heavenly; though he be humble, lowly, meek,
patient, peaceable, though truth be in all his words,
equity and faithfulness in all his deeds; though he visits the fatherless and the widow,
and keeps himself unspotted from the world;
if he be not in the exercise of some outward form of godliness,
he shall not be counted religious, nor hardly a Christian.^
footnote:[But it is not hereby intended to discourage the assembling
of ourselves together for the public worship of Almighty God,
agreeable to the advice of the Apostle, Heb. 10:25.]

Conformity in every sect, opinion, or persuasion,
is become the character of a religious man, and the only band of unity and brotherhood;
if this fail, there soon comes an estrangedness:
and so there is much pressing into conformities,
but little minding the mortification of sin, in order to a life of righteousness.
But let our zeal for conformity be never so much,
it is he that ordereth his conversation aright, that shall see the salvation of God.

The conformity that the living Lord requires,
is a conformity to the image of Christ in the course of our lives,
to be holy as he was holy; without which we cannot be, as the primitive Christians were,
of the household of God: we are not come to the New Jerusalem,
and so cannot be fellow citizens with saints.
Though we bear the primitive Christians`' name,
we are not in the primitive Christians`' nature; the first-born is not so brought down,
as to have a right spirit alone to rule in us, and to have the dominion over us.

If the sayings contained in this book seem strange unto the reader,
it is because the reader is a stranger to the primitive Christians`' life:
if He who was their head and leader, were become ours; had we fellowship with them,
as they had with Christ; we should have an echo in ourselves,
answering to what is here said: our hearts would say, "`It is so.`"

And the way to come to their righteous life, is to walk in the light,
denying and turning from the least thing that it shall manifest unto us to be evil.
At the beginning of our journey, it will seem a strait and narrow way;
but after we have travelled on a while, we shall run therein with great delight.
For the kingdom of heaven,
or Christ`'s government by his eternal Spirit in the hearts of his people,
doth not consist of righteousness alone:
the righteousness that proceeds from a right spirit, is accompanied with peace and joy:
as ill-doing is attended with trouble and sorrow,
well-doing is attended with peace and joy.
All the pleasures of wickedness, that the whole world affords,
are not to be compared to the joys of a righteous life.
Every evil motion we deny, in obedience unto Christ,
affordeth a superior joy to that which a warrior hath in battle,
when his enemy flies before him.

The Jews counted themselves more holy than the Gentiles, though both made of one blood;
and as both were the offspring of Adam, both had in themselves good and evil.
But to the Jews the Lord gave laws, statutes, and judgments, for a rule of righteousness;
and they, conforming thereunto in worship and outward services, counted themselves,
as we who are called Christians do, holier than the Heathen.

But this was a selfish persuasion in the Jews,
and no better in us who are called Christians,
whilst we continue in a state of degeneration: for no outward conformity,
without inward sanctification, can make any man holy; and no man is sanctified,
till sin is mortified.

When the Heathens, through the preaching of the gospel, turned from their darkness,
and came to be followers of the eternal Spirit, thereby mortifying the strength of sin,
they were more holy than many of the Jews, and called by the apostle Saints;
which was more suitable than the name of Christians;
was was at first given in derision to the followers
of Christ by the unconverted Heathens at Antioch,
and but once sincerely mentioned in all the Scripture.
But the name saints is peculiar to all truly sanctified souls.

As circumcision gave many the name of Jews,
so the imitating of John`'s baptism hath given many the name of Christians;
but nothing can give Jew or Christian the name of a saint, in truth,
but a heart made pure, single, upright, and honest, through the mortification of sin,
called in Scripture,
"`The baptism of the Holy Ghost;`" for that is effected not by any outward means,
but by our walking after the Holy Ghost.
Till this is wrought, though we have a Christian name,
we cannot bring forth a heavenly conversation, and so the name profiteth little.

For we who are called Christians, as we are born into the world,
have in ourselves a seed of sin as well as others;
and for want of faithful weeders to root up vice as it appears,
iniquity grows to that height,
that nothing less than the powerful Spirit of Christ can bring it down:
and from such who remain strangers to the working of this Spirit a cry hath gone forth,
"`That there is no freedom from sin on this side the grave:`" but the Colossians,
who were delivered from the power of darkness, knew better things; and so should we,
if we did turn from iniquity, acquaint ourselves with their guide,
and walk in newness of life.

A numberless number at this day bear the Christian name, because it is easily obtained:
nothing is required at the receiving of it but promises.
But small is the number of saints, because no man can be a saint,
but by a performance of those promises; and that no man can do,
until he turn to that in himself which manifests the works of the devil; and,
on discovery thereof, deny, turn from, and quite forsake them.
By taking this way, and using this means, sin will certainly be mortified,
the soul sanctified, and such as were sinners will come to be saints.

But as nothing discouraged the camp of Israel from going up to possess the land of Canaan,
more than the report that ten spies gave of the strength of the people that dwelt therein;
so nothing discourageth awakened souls from pressing after a life of righteousness,
more than the report that hath been given by professors
of godliness concerning the strength of sin,
that it could not be overcome:
when they that so reported never made trial in the way of God`'s salvation.

All the spies spake well of the land, as all sorts of people now do of a sober,
righteous, godly life and conversation: all will commend humility, meekness, moderation,
temperance, patience, chastity, and, above all, plain, upright, honest, just dealings,
though they do not practise them; and nothing hinders but this,
the evil spirit of this world is uppermost, and few endeavor, in God`'s way,
to bring it down.

Had the camp of Israel made them a captain, and gone back into Egypt,
they could never have subdued the Canaanites:
and whilst we allow our selves to live in sin, it is impossible we should subdue it,
for we strengthen what we should mortify.
The Canaanites were made weak by war, and so must the strength of sin;
with this difference, theirs was an actual war, and ours must be defensive.
When, by the candle of the Lord that shines in our souls, we see an aspiring thought,
a lustful desire, a covetous inclination, or any other evil motion;
if we stand on our guard, and deny it entrance into our affection, it will retreat,
and after many attempts, being still put back, will hardly attempt any more; at most,
the motions thereof will be but weak.

Whilst there was an accursed thing in the camp, the enemy prevailed,
and Israel retreated: and so it is at this day; if we cover, if we hide,
if we justify what our own hearts condemn, the evil prevails, and the good retreats.

Let us but accustom ourselves to true denials, and the strength of sin, will,
from day to day, be weakened; and as Joshua and Caleb said, the Lord will be with us;
his grace will be in our hearts, and his fear before our eyes; truth, equity,
and honesty, will be uppermost: and then it will be as easy to lead a sober, righteous,
godly life, as ever it was to live a loose and ungodly life:
for though something of sin may remain in us,
as some of the Canaanites remained in the good land, it will be powerless, as they were;
and all our members that were servants to sin, will become servants to righteousness,
as it is written, "`The elder shall serve the younger.`"

But if we rebel against the Lord, by joining with motions of sin,
as many who are called Christians, as well as Heathens, do,
this war will be over before it is begun; that which is uppermost, will continue so;
and as we live, so we shall die, receiving wages, not according to our words, but,
according to our works: and then we shall know that a Christian name,
without a Christian conversation, will stand us in little stead;
for it is not he that is overcome, but he that overcometh,
that the second death shall not hurt.

=== Paul`'s Speech To The Bishop Of Crete

BY HUGH TURFORD

To The Reader

MOST men have learned to speak well of grace, but few of them can tell what it is,
or where it may be found: many will acknowledge it to be the gift of God;
yet think to have it from the lips of men: many are persuaded,
that all wickedness is for want of grace;
yet through their ignorance slight the appearances thereof in themselves:
many are convinced, that there is a sufficiency therein, were it before men`'s faces,
to preserve them from great sins;
but cannot believe there is a sufficiency therein to save them from any sin.
Which plainly shews, that their speaking well of grace is from hear-say,
and not from experience.

This little Treatise shows, what grace is, where it may be found,
and how it comes to be before men`'s faces; that it is +++[+++that which saves]
from sin, and so the true salvation.
For whosoever is saved from sin here,
shall certainly be saved from death and condemnation hereafter:
and that many may come to be witnesses of this salvation is the desire of,

Hugh Turford

[.asterism]
'''

Paul, an apostle of Jesus Christ, writing to Titus, the first bishop of Crete,
had this saying, "`The grace of God, that brings salvation, hath appeared unto all men,
teaching us, that denying ungodliness and worldly lusts, we should live soberly,
righteously, and godly, in this present World.`"
From which weighty sayings these following questions arise:

Question 1. What is the grace of God?

Answer: The grace of God, that brings Salvation, is no less than a divine inspiration,
the gift of God to the sons and daughters of men, an adversary to the devil,
a destroyer of sin, and that which saves mankind therefrom.

The gift of grace, under the gospel administration,
is the fulfilling of that promised covenant, which God,
by the mouth of his prophet Jeremiah, promised to make with the house of Jacob,
which was, "`that he would write his law in their hearts,
and put his Spirit in their inward parts:`" that his people might have
a rule of righteousness in themselves to guide their steps by.

As the princes of the earth rule and govern their people by an outward law,
so the Lord resolved to rule and govern his people by an inward law:
they should have no need to turn over the leaves of a book,
as the seed of Abraham under the first covenant had,
to know how they should walk in right paths; but they should know,
by looking into their own hearts, what was right, and what was wrong; what they might do,
and what they should leave undone; what was just, and what was unjust;
what was pleasing to God, and what was not: for this law is a light,
that enlightens men`'s souls, as the sun in the firmament enlighteneth our houses,
shewing what is clean, and what is unclean; what may remain,
and what is to be swept out.

For as God made man in the beginning, humble, lowly, meek, merciful, pure, peaceable,
just, and faithful; he would have all men to be so.
But forasmuch as nothing less than the good Spirit of God, in the inward parts of man,
can reduce any of us to such a qualification,
God hath given to every man a measure thereof, to enlighten his understanding,
and to guide him in the path of life and salvation; and this measure,
being the free gift of God, is, by the apostle in the text,
and in many other places of Scripture, called Grace.

Question 2. Where doth the grace of God, that brings salvation, appear?

Answer: The great God, in his infinite wisdom and everlasting love,
hath placed his royal seed and plant of renown in
the hearts of the sons and daughters of men,
for that is the chief garrison of the soul; there the grace of God,
that brings salvation, may be found: from thence,
until it come to be veiled by clouds of iniquity,
it shews itself a witness against all unrighteousness and ungodliness.

As every evil motion and temptation, that leads to sin, appears within;
so the grace of God, that is given to men, to save from sin, appears also within.

There is not a man born into the world, if he has lived to commit sin,
but hath felt and known in himself rebukes for sin;
and these rebukes are the appearances of grace, and called in Scripture Light,
and true Light; for it manifests every work of darkness;
it shews us both when and wherein we have done amiss: and this it hath done in all ages.

God hath not in any age left himself without a witness in the hearts of men,
to declare his righteousness, truth, and faithfulness.
But there is as much difference between the appearance of grace,
and the power of grace to salvation; the light of righteousness,
and that fulness which enables us to lead a life of righteousness;
as is between a seed that is sown, and the herb when it is come to full growth;
but the one leads to the other; and it is he that attains to the fulness of grace,
that comes to lead a sober, righteous, godly life in this present world.

It was said of Jesus, the second Adam,
that he was "`full of grace;`" and we may believe
it from the fruits he brought forth in this life:
he was humble, lowly, meek, patient, peaceable, just, and faithful;
he resisted the devil in all his temptations, led a blameless life,
fulfilled all righteousness, and in the whole course of his life,
retained what the first Adam soon lost, namely, the image of God:
and whosoever grows in grace until he attains to his stature, namely,
to be filled therewith, may be called, as Job was, "`a perfect man.`"

And as the appearances of grace are inward, so are all its discoveries, revelations,
and teachings;
whosoever applies himself to man for a right knowledge of the things of God,
goes to a wrong school; for, as Paul truly said,
"`That which may be known of God is manifest within.`"

The proud, the covetous, the envious, and other ungodly persons, may, for a time,
and a long time, have the appearances of grace; they may have rebukes for sin;
but if by such rebukes, they do not learn righteousness, they grow not in grace,
neither doth grace grow in them; all such hide their talent, and in time,
for want of improvement, come to have it quite taken from them; and being left graceless,
lead a wicked and ungodly life in this present world.

Question 3. If the grace of God appears unto all,
and if there is a sufficiency therein to make them godly, how comes it to pass,
that there are so many ungodly:

Answer: As the grace of God that brings salvation, appears unto all men,
so motions of sin, that lead to destruction, appear unto all men,
and commonly make the first appearance.
All men have evil motions and temptations in themselves to sin,
before they are acquainted with any rebukes in themselves for sin;
and the work of the devil is to make forbidden things appear desirable,
the world and the vanities thereof to be full of pleasantness:
and as our affections come to be taken therewith, as we make the world our delight,
and pursue after it, we depart from God; and though grace may make many appearances,
though the good Spirit of God may long strive with us,
though we have in ourselves many checks and rebukes,
and are thereby made sensible that our ways and our doings displease God,
yet are we prone to persevere therein; and through a continued perseverance,
sin grows and comes to have dominion over us:
and the devil making one ungodly person a bait to catch another,
is the very cause why we have so many ungodly livers in the world.

The further any man goeth from God and godliness, the less desire he hath to return;
and the more delight he takes in the vanities of this world,
the less felicity he beholds in the things of God.
And as long as one spark of grace remains,
the devil will follow all such with his temptations; for he can call none really his own,
until they become quite graceless;
and many such graceless ones would be apparently found,
were not wickedness limited by an outward law.

Were we, as Israel once was, without a king; or as the inhabitants of Laish,
who had no magistrate in the land, to put them to shame for any thing;
we should find many who bear the Christian name to be of the devil`'s nature,
working all manner of wickedness.
And so it highly concerns all who have the appearances of grace,
from the rebukes thereof, to learn righteousness, that it may grow in them,
and be their guide: for nothing but grace, and obedience unto righteousness,
makes any of us differ from the worst of men in vile actions;
for as all righteousness proceeds from a fulness of grace,
so the aboundings of wickedness are through a deprivation of grace.

Question 4. What manner of salvation doth the grace of God bring?

Answer: As the appearances of grace are rebukes for sin,
so the salvation that grace brings, is a saving from sin.

If grace teacheth men to live soberly, righteously, and godly in this present world,
grace saves good men from sin in this present world.

We read of an angel that appeared to Joseph, saying,
"`Fear not to take unto thee Mary thy wife, for that which is conceived in her,
is of the Holy Ghost; and she shall bring forth a Son,
and thou shalt call his name Jesus, for he shall save his people from their sins.`"

Nothing defaceth the image of God in man but sin;
nor can any thing recover that image again, but our being saved from sin.

The mortification of sin brings men to their beginning: the more humble, lowly, meek,
and merciful any man is, the more patient, peaceable, just, upright,
and faithful any man is found,
the more conformable he is to the life and nature of Christ.

Paul told the Ephesians, that they were saved by grace; and what were they saved from,
but from the power of sin and Satan: And where was this grace but in their own hearts:
Before they came, through turning from their iniquities, to have grace in their hearts,
they walked, as thousands now do, according to the course of the world, not denying,
but fulfilling the desires of their minds; and all such are, as they then were,
without Christ, without light, without life,
without the sense or feeling of any thing in them that was of God;
aliens from the government of Christ`'s eternal Spirit in their inward parts,
and strangers from the promised covenant; knowing no more of a law in their hearts,
to guide their steps by, than the ungodly men of this age do.

But when they came to be quickened by Christ,
and to have in their own hearts his good Spirit, and to be led thereby,
they were saved from sin, they came to have new natures, and so to be new creatures:
and then they were no longer strangers to Christ`'s government, by a law in themselves,
but subjects to righteousness, citizens with saints, and of God`'s family.
To which blessed state we might all come,
did we but embrace the gift of God for our salvation,
and give ourselves up to be taught and guided thereby; which would be our wisdom,
since nothing else can subdue Satan, save from sin, and enable us to live soberly,
righteously, and godly, in this present world.

Saving from sin, on this side the grave, may,
to such as are strangers to God`'s salvation, seem an incredible thing;
but were they so well acquainted with the power of grace,
as too many are with the strength of sin, they would say, Christ`'s yoke was easy.

Hath it not been the saying of many ungodly men, "`That they would amend their lives,
if they had but power.`"

Where the hearts of any, through a perseverance in sin,
come to be filled with unrighteousness,
sin and Satan hath such power over the faculties of their souls,
that they cannot resist evil motions and temptations; but must yield thereunto,
and suffer themselves to be led away thereby, though they know it is to evil practices.

And if sin hath such dominion over ungodly men,
why may not grace have as much dominion over godly men?
Surely good Joseph found such a power in his soul, when he said,
"`How can I do this great wickedness, and sin against God?`"

Grace being a divine inspiration, commands the hearts of all good men;
and the heart being the chief garrison of the soul, commands every member of the body,
holding them in with bit and bridle.

The ear of a gracious man is shut from hearkening to fables and evil reports;
his eye is turned aside from gazing upon vanity; his tongue is not suffered to curse,
swear, lie, or to be employed in any idle communication;
his hand is limited from taking of bribes to pervert justice,
and from taking by violence, or otherwise, any thing that is not his own:
his feet are restrained from going with the drunkard to excess,
or with a lewd woman to the chamber of wantonness, or with rude persons to rioting,
revelling, or any other rude exercise: and by this dominion,
that grace comes to have over us, the Lord saves his people from their sins.
And as we live in subjection to this power, we are servants to another prince;
sin and Satan have lost their dominion over us; and this is God`'s salvation;
by this we come to live soberly, righteously, and godly, in this present world.

Question 5, Whom did the apostle mean when he said,
"`teaching us;`" was it the world in general, or only some particulars?

Answer: Christ was given as a light to the Gentiles; to which, as they became obedient,
he was also their leader out of all ungodliness,
and they came to live under the government of his eternal Spirit in their own hearts;
for such only the Lord owns for his people,
and none but such can call him Lord in truth.

Grace appears unto all men:
every one that is born into the world hath a light in his soul,
that shews him the motions of sin,
and rebukes him when and as oft as he yields thereunto.

All righteousness is learned out of the book of the law,
when it comes to be written in our hearts;
but that law being the law of the Spirit of life, we must be quickened by Christ,
and have the Spirit of life, before we can learn from that law.

Our ancestors made it their concern to teach youth good manners, as temperance,
moderation, chastity, civil behavior, to be dutiful to parents,
to shew respect to their elders, to be circumspect in their communication, swift to hear,
slow to speak, to answer with meekness and gravity, to be true to their trust,
faithful in their promises, just in their dealings, keeping to their word in all things,
that their word might be taken in all cases without doubt or scruple;
every one to know his place, and abide therein.

Now as we turn from ungodliness to sobriety,
we bring forth all these fruits in our lives; for grace teacheth all this and much more;
but since we find so few thus qualified, we may certainly conclude,
that though grace appears unto all, all are not obedient thereto.

Question 6. We must confess that we have known inward rebukes for sin;
we have been checked, reproved, and convicted in ourselves after we have done amiss;
but we have not found any thing in and of ourselves,
when strong motions and temptations have arisen in our minds,
to restrain us with bit and bridle from doing amiss;
and to deny ungodliness and worldly lusts in our own strength,
seems too hard for any mortal;
especially when any worldly sin hath got the dominion over us:
what can we do in such a case?

Answer: Could man, in his own strength,
deliver his soul from under the power of sin and Satan, return unto God,
and lead a sober, righteous, godly life in this present world,
there would have been no need of a Redeemer, no occasion for a Saviour,
no use of a quickening Spirit, to give life to our souls,
no necessity of God`'s writing his law in our hearts, for a rule to guide our steps by;
no want of a light in our souls to shew us where the devil spreads his net,
casts his bait, lays his gin, and displays his false colors:
but man can no more deliver his soul from the power
of sin and Satan without the help of the Lord,
than Israel, when they were in Egypt,
could go free from the servitude of Pharaoh without his help;
therefore grace appears unto all men for their aid.
And though the appearance of grace may seem but small aid
to set our souls free from the servitude of sin and Satan,
and to conduct us in the way of life and salvation, till we come to the end of our race,
to live under Christ`'s government; it is not smaller than Israel`'s aid was,
to bring them from under the servitude of Pharaoh,
and conduct them to the promised land.

Israel`'s aid was but two aged men (the younger of them being about
eighty years old) having no weapons but a rod in one of their hands;
yet by this small means, God being with them,
they brought from under the power and servitude of Pharaoh, six hundred thousand men,
besides women and children; and grace, being a divine inspiration,
is aid enough to bring six hundred thousand millions
from under the servitude of sin and power of Satan,
did men but confide therein, and give themselves up to be guided thereby.

Inward rebukes, if we have regard thereunto, beget a fear in men,
as the shaking of the rod doth in children;
and as "`The fear of the Lord is the beginning of wisdom,`"
so it is the beginning of a reformation of our lives.

If I am checked in myself for making a lie, and have regard to that which checked me,
I shall be afraid of making another;
or if I find in myself rebukes for not keeping my promise, or for doing any thing amiss,
and have regard to such rebukes, I shall be afraid to do the like,
lest the next rebukes be sharper; and as this holy fear abides in us,
we come to deny ungodliness, and in denying ungodliness we learn righteousness:
but such as find in themselves rebukes for sin, and have no regard thereunto,
are like unto children that carry horn-books at their sides, and learn nothing therein:
they are no scholars in the school of grace.

We have read,
that "`Reproofs of instruction are the way of life,`"
and many good men may be found at this day,
who will acknowledge that they had never come to a life of righteousness,
had they not had reproofs of instruction from their own hearts,
by which they came to deny unrighteousness.
For where rebukes for sin are received in love, the Lord doth not leave such souls,
but follows them therewith; and the more vices they subdue, the more,
in the light of the Lord, shall they see,
and the more power shall they receive from him to overcome them.

If one plague will not make Pharaoh willing to let Israel go, he shall have another,
and another, until he be willing;
and if one rebuke will not make us willing to part with a beloved sin,
we shall have another, yea, trouble and terror.

Paul knew terror before he came to find peace with God, and peace in his own conscience;
he was acquainted with judgment, before he came to obtain victory.
Nothing hath power to break the bonds of captivity,
and set us free from the law of sin and death,
but the law of the Spirit of life in our own hearts.

Israel`'s main enemies were not subdued as soon as they came out of Egypt,
but when they came into the promised land;
neither is the body of sin made weak as soon as we turn from unrighteousness,
but when we come into the life of righteousness, to have grace before our faces,
as Joshua was before their faces: for sin cannot stand in the face of righteousness,
no more than the Canaanites could stand in the face of Joshua.

And if any lordly sin hath got dominion over us, I shall not say, as one formerly said,
"`Fight not with small or great, save only with the king of Israel,`" but rather,
when violent motions arise, Stand still, and the Lord will fight for us;
for as our hearts come to be possessed with grace,
if the enemy should come in as a flood, the Spirit of the Lord,
being in our inward parts, will lift up a standard against him.

The Lord`'s controversy is not, as men vainly imagine, against the sinner,
but against the author of sin; his appearances are all in love to save the sinner,
and by his judgments to weaken the strength of sin: for man once freed from sin,
is as willing to lead a righteous life, as any ungodly man can be to lead a wicked life,
and more joy he hath, though the world cannot see it.

Question 7. What may truly and properly be called a "`sober, righteous, godly life?`"

Answer: A sober life, many may, in some measure, be acquainted with, but a righteous,
godly life, is rarely considered.

Devotion, which consists in hearing of sermons, reading of good books,
performing of family duties, etc. hath for many ages been accounted godliness,
and the practitioners thereof righteous people.

These things are not to be discommended, where they are done in sincerity;
but these are not the true character of righteousness and godliness.

This and much more might be found among the Scribes and Pharisees,
yet Jesus told his disciples,
that except their righteousness exceeded the righteousness of the Scribes and Pharisees,
they could in no wise enter into the kingdom of God.

And who is there amongst us, that are called Christians,
but one day in seven will be in the exercise of something that is called godliness,
though they have not learned to deny ungodliness.
And such as have not learned to deny ungodliness, are far from such a righteous,
godly life, as the grace of our Lord Jesus Christ teacheth all its followers.

One way to know what is righteous and godly,
is to consider what is unrighteous and ungodly, for the one is opposite to the other,
as light to darkness: and these things that follow,
most will acknowledge to be unrighteous and ungodly, viz. drunkenness, whoredom, theft,
envy, hatred, bloodshed, swearing, cursing, lying, extortion, fraud, double-dealing,
talebearing, and whispering (which is the seed of strife):
all these things are unrighteous, and pride, above many evils, most ungodly.

These are not fruits proceeding from the good Spirit of God,
but from the evil spirit of this world; not issues of life,
but streams that flow from a corrupt spring;
these come not from the teaching of grace in our hearts,
but from evil motions that arise in our minds; these make us sinners before the Lord;
and as long as we live in the practice of any of them,
we shall not be righteous in his sight: those that brought forth fruits of this kind,
have, in all ages of the world, been testified against as unrighteous and ungodly livers.
These are infirmities of the soul,
that millions of money have been given to physicians to cure,
but behold health hath not been by them restored.
These are weeds that thousands have been hired to pluck up,
but to this day have not made clean gardens, nor ever will by all the art they have,
for Christ is the Physician of souls; none can take away the sins of the world,
but he alone.

Whosoever thinks to attain to a righteous, godly life,
but by the teachings of grace in his own heart, deceiveth his own soul.

Men may lop, or hinder the growth of many branches of iniquity that appear outwardly,
but cannot take away the cause which is within; and until the cause is removed,
there can be no thorough cure.

As grace hath a spring, so iniquity hath a root,
and the axe that smites at this root is in Christ`'s hands; and what is the axe,
but the law of the Spirit of life, a law of righteousness in our inward parts.
This wrought a perfect cure in Paul; this made him a free man, a good man,
and a preacher; and that which cured Paul, and set him free from the power of sin,
hath a sufficiency in it to set all men free therefrom.

"`Walk in the Spirit,`" said Paul, "`and ye shall not fulfill the lust of "`the flesh.`"
That is the only remedy, that is the soul-healing salve;
and what is the walking in the Spirit,
but following the leadings of grace in our own hearts: For grace,
as it comes to have the rule over us, brings down all exalted thoughts, abaseth pride,
shuts out covetousness, gives no place unto wrath, reduceth us to a cool,
quiet frame of spirit, in which frame we can bear and suffer.
Grace will not suffer us to do any unjust thing, nor allow us to speak an ill word,
much less to be drunk, commit whoredom, steal, or any such abominable vices:
for it is the promised Spirit of truth that leads into all truth, leads out of all error,
and so brings salvation indeed.

No man can lead a righteous life,
till a right spirit comes to have the whole possession of his heart;
for from the good treasures of the heart proceeds all good living; for that is the guide,
and this guide being a divine nature, makes us to be heavenly-minded.

Nothing exceeds the righteousness of the Scribes and Pharisees,
but the righteousness that proceeds from a right spirit in our own hearts;
for that is not our own righteousness, but the righteousness of Christ.

As murder, adultery, theft, which are some of the worst of evils,
proceed out of the heart,
whilst the evil spirit of this world hath the possession thereof;
so good-will to all men, which is a principal virtue, proceeds out of the heart,
when the good Spirit of God comes to make its abode there: but this abode is not known,
till by denying ungodliness and worldly lusts, the spirit of this world is denied,
and thereby the heart cleansed; then, and not till then,
can we come to know "`the Lord our Righteousness.`"

He that is reduced to such a qualification, as to have good-will to all men,
is of all men most godly; for as God, in his unlimited love to mankind,
"`maketh his sun to rise on the evil and on the good,
and sendeth rain on the just and on the unjust;`" so he that hath good-will to all,
will not wrong any, oppress any, shew violence to any, or speak evil of any,
but be ready to serve all men in love and faithfulness;
and this is a true character of a sober, righteous, godly man;
such a one is converted indeed, and become a weaned child,
and is entered into that kingdom that consists in righteousness, peace,
and joy in the Holy Ghost.

And since this reformation is only and alone by the grace of our Lord Jesus Christ,
give me leave to say, with the prophet, "`Ho, every one that thirsteth,
come ye to the waters,`" and drink;
every one that hath a desire in his soul after righteousness,
turn in to the grace of God in his own heart.
The water that the prophet invited all thirsty souls unto,
is no other than that which Christ giveth;
and whosoever drinketh thereof thirsteth no more, but hath,
as many at this day can witness, a well in himself, not only issuing,
but flowing up to eternal life.

The grace of God is a free gift, without money, and without price;
nothing is required on man`'s part, but to hearken thereunto, and take counsel therefrom;
"`Hear,`" said the prophet, "`and your soul shall live.`"
Adam, hearkening to evil motions, died unto righteousness, and so do all ungodly men;
but he that hearkens to the voice of grace, lives unto righteousness,
and from the flowings of that spring that he hath in himself, leads a sober, righteous,
godly life in this present world.

Hearing and reading, at the best, tend to instruct us in what we ought to do;
but godliness is doing what grace teacheth; and all such doings are right and good.

Question 8. Were not the scriptures written for our learning,
and are not they a sufficient rule of righteousness?

Answer: The scriptures are a rule; but who can walk by that rule,
unless he be inspired with the good Spirit of God?

The house of Jacob had not only ten commands written on tables of Stone,
but many other statutes and commandments, proceeding from a righteous judge,
written in their books, and not only read,
but also expounded unto them every sabbath-day, that they might walk in righteous paths;
but though they had the words of God in their books,
many had not the fear of God in their hearts,
and so though they had a great zeal for an outward worship and form of devotion,
yet were they ungodly in life and conversation.

And what shall I say of us who are called Christians?
We have the words of God, and the words of Christ, the words of the prophets,
and the words of the apostles in our books; we have large rules of righteousness,
but do we guide our steps by our rule?
or can we?

The Christian`'s rule of righteousness is Christ`'s direction; let us,
who say the scripture is our rule, examine our abilities to walk by our rule:
Are we lights to the world?
Do our good works glorify God, or shame our Christian profession?
Are we so far from committing adultery, that we have not so much as a lustful thought?
Are we so far guided by the truth, that every word that proceeds out of our mouths,
by way of promise, is sure and steadfast?
Can we refrain from smiting when we are smitten?
Can we give our cloak to him that sues us at the law, and wrongfully takes away our coat?
Can we love our enemies?
Can we bless them that curse us?
Can we do good to them that hate us?
Can we pray for them that despitefully use us?
Can we depend on God`'s providence, without taking care what we shall eat,
or what we shall drink Can we do unto all men, in all things whatsoever,
as we would that they should do unto us?
This is Christ`'s yoke; can we bow our hearts and minds thereunto?
This is Christ`'s burden, and can we bear it?
He said, his yoke was easy, and his burden light; but if these things are too hard,
and too heavy a burden to us, it is because we have not his grace and his spirit;
we have a Christian name, but are not in the Christian nature; we have a rule,
but have not power to walk by our rule; and then what good does our rule do us?

If ever we think to walk by scripture rules,
if ever we intend to keep our Lord`'s command, and if we would lead a righteous,
godly life in this present world, we must turn in to the grace of God in our own hearts;
for that gives us power to keep to our rule.

It was for want of grace, that the seed of Abraham could not keep Moses`'s commands;
it is for want of grace that Christians do not keep Christ`'s commands;
he lays no other burden on us than what he bore himself;
the fulness of grace that dwelt in him, made all these things easy to him; and,
as we grow in grace till we come to be filled therewith, they will be easy unto us:
grace mortifies sin, and where sin is mortified,
nothing is easier than to lead a righteous life.

Objection: But some may say,
our dependance for life and salvation is not on works of righteousness, but on faith:
we believe, and therefore hope to be saved.

Answer: I know that is most men`'s dependance, and faith we all think we have:
but is it a faith that purifies the heart,
and makes our bodies fit temples for the Holy Ghost?

Paul put the Corinthians on an examination of themselves,
on a trial and proof of their faith, and it would not be amiss,
if all that account themselves believers did prove their faith by the same touchstone;
"`Know ye not,`" said Paul, "`that Christ is in you, except ye be reprobates?`"
Was Christ in the Corinthians?
And is he not in all men that turn from ungodliness,
and come to have their hearts purified?

How can we know the only true God, if we do not behold his presence?
How can we know our Saviour, if he be not in us, to save us from our spiritual enemies,
as Joshua was in the camp of Israel, to save them from their outward enemies?
And this is life eternal, not only to hear of a God and a Saviour, but to know him;
to feel the power of God, and to be witnesses of Christ`'s salvation;
these are believers, and true believers, for their eyes have seen what they believe.

Faith and works of righteousness go together; he that hath the one hath both,
and grace is the spring from whence both proceed; the reprobate, the ungodly,
the graceless, have neither.

Question 9. If inward and spiritual grace be sufficient
to teach us our duty towards God and man,
and to establish us in righteousness; wherefore was there an outward ministry,
and to what end were apostles, prophets, evangelists, pastors, and teachers,
given to the church?

Answer: Paul, as he told king Agrippa, was made a minister and a witness;
he was a witness of the powerful operation of grace in his own soul,
and so could tell others what it could do for them.

In the state of degeneration all men are strangers to grace, they know not the Lord;
and the work of the ministry is to open the understandings of all such,
and to turn them to this heavenly teacher;
since nothing else can enable them to lead a sober, righteous, godly life,
in this present world.

And as some were ordained to plant, so others were given to water,
that no young plant might wither before it came to be rooted and grounded.

We find that, in the primitive times, some declined from what they had attained to,
for that they kept not with their guide;
and with such Paul was forced to travail in birth again:
for as plants are not grounded as soon as they are planted,
so men are not established in righteousness as soon as they are turned from unrighteousness;
and such as were strong, were to watch over the weak,
and lend them a helping hand in their travails, until they all came,
in the unity of the Spirit, to be perfect men,
and then there is no more need of man`'s help; and we are all perfect men,
when a right Spirit comes to have the whole government in us.

But who are fit to plant and water?
No ungodly men, for such have not the Spirit of Jesus,
such know not the way of God`'s salvation themselves,
and so cannot direct others thereto, nor lend them a hand therein; but such as are,
what Paul after his conversion was, not only ministers,
but witnesses of what they testify;
or such as have travelled in the way of God`'s salvation themselves, and are come,
through the teachings of grace, to that strength and perfection,
as to deny ungodliness and worldly lusts, and to live soberly, righteously, and godly,
in this present world.

=== Trial Of Christianity, From The Life And Nature Of Christ And True Christians:

With a Description of TRUE GODLINESS,
and the Way by which we may conform our Lives thereunto.

MANY professors of Christianity, in our present age,
conclude that Godliness consisteth in hearing, reading, praying, praising,
etc. which are all good exercises, if rightly performed,
and may be called Christian duties; for all true Christians are required, and,
by the good Spirit of God in their own hearts, often stirred up to perform them.

Howbeit, the performance of these and such like things alone,
is no certain proof of Godliness; Christianity cannot be known thereby,
for as there was a more excellent righteousness than what was found in the zealous Pharisees,
so there is a more excellent godliness than what appears in most professed Christians.

For hearing, reading, praying, praising, with other exercises of that nature,
may be imitated; the ungodly, as well as the godly, the formalist as well as the sincere,
may be found in the practice of such things; but true godliness cannot be imitated,
being the natural effects of the rule and government of a right Spirit,
and may be truly called the issues of life, which none can bring forth,
but such who are Christians indeed.

True godliness is supernatural, and so above the reach of Adam`'s offspring, who,
whilst they continue in the fall, are servants to sin;
we must be reduced to a God-like nature before we can bring forth a godly conversation:
grapes cannot be expected from thorns, nor figs of thistles;
the tree must be made good before the fruit can be good;
a righteous life is the natural effect of a right Spirit;
our lights cannot shine forth before men,
until we are enlightened with the light of Christ: without a true conversion,
there can be no true conversation; for all men, in the nature of fallen Adam,
being ungod-like, until they are raised by Christ the second Adam, cannot live God-like.

The life and nature of Christ, all true Christians, who have the Spirit of Christ,
may find in themselves;
and others may have some sense thereof by reading
and well considering the contents of the fifth,
sixth, and seventh chapters of Matthew, where it is said,
that Jesus "`seeing the multitude, went up into a mountain, and when he was set,
his disciples came unto him,
and he opened his mouth and taught them;`" and what he taught his disciples then,
he teacheth all true Christians now: though he ascended,
the Holy Spirit that dwelt in him descended, and did then, doth now,
and to the end of the world will,
tabernacle with all the Lord`'s redeemed to be their teacher;
and as many as walk after this Spirit are taught of Christ, and walk in his footsteps;
for as no vine beareth one kind of grape, and the branches another,
so all the members of Christ answer the life of Christ in their conversations;
they are naturally humble, lowly, meek, merciful, patient, peaceable, just, upright,
honest, and faithful: a Christian is not known by his words or his devotion;
but by his works, his nature, his life, and his conversation.

I shall not insist on all particulars contained in the fore-mentioned chapters,
but chiefly on the five following exhortations or commands of our Lord;
the least of which, for a true trial of Christianity,
is more to be observed than that command, Luke 22:19.

"`This do in remembrance of me;`" for the proud as well as the humble,
the cruel as well as the merciful, the fraudulent as well as the just,
the ungodly as well as the godly, can conform to the one,
but cannot conform to the other.

The true trial of Christianity is to be found in the life and nature of Christ;
if the Spirit of Christ hath the rule in us,
these following fruits will be brought forth by us:

1+++.+++ In all our communication, our yea will be yea, and our nay, nay;
the word that goeth out of our lips will be sure.

He that is a Christian indeed hath no necessity in himself,
nor need to be urged by others, to bind his soul with an oath to perform his word,
for the law of the Spirit of life in his own heart constrains him so to do.

Christians in their communications weigh their words, before they utter them,
with their capacities to perform them;
knowing that a promise cannot be broken without violating
the righteous law of God in their own hearts;
and whenever such violence is done, terror ensues; and this makes good men,
who live under the government of Christ, dread much more to break their words,
than others do to forfeit their bonds; and this holy dread makes our yea to be yea,
and our nay to be nay; this makes us cautious in our promises,
and careful in our performances; the exhortation may be read in scripture,
but the binding tie must be known in our own hearts:
all that have the scripture have this rule;
but unless we have a principle of life in ourselves, we cannot walk by this rule;
and we must not only have such a principle,
but we must also improve it by a continued practice, before it comes to be our life,
our centre, and our nature; till then we may say,
"`These things we should do;`" but cannot say,
"`These things we do;`" and so witness against ourselves, that,
though we have the scriptures, we walk not according to the scriptures;
though we have the words of Christ, we are not in the life and nature of Christ;
our yea is not yea, and our nay, nay, in our communication;
our words and our promises are not stedfast and sure.

Swearing, in the communication of Christians, is superfluous;
for where truth rules in the heart, there cannot be falsehood in the lips.
Prove a professed Christian by this rule, measure him by this line,
weigh him in this balance: if his yea be yea, and his nay, nay, in all his communication;
if he be a man of his word at all times; if his performances be one with his promises,
he abides in the doctrine of Christ;
and this is an evident demonstration that he is +++[+++so far]
a Christian indeed.
But if these Performances are wanting, though he have a Christian name,
he is not in the Christian nature; for, as I said before,
what manner of grape the vine beareth, the branches thereof,
if they continue in the vine, bear the same.

The second exhortation or command of our Lord was this,
"`Resist not evil;`" and this was not only his doctrine, but his life and nature,
as we may plentifully read in scripture.
Though he met with revilings, reproaches, buffetings, and cruel usage,
we do not find that he was once moved thereby, much less that ever he resisted;
but gave his face to the smiter, and his cheeks to them that plucked off the hair;
and when he was led as a lamb to the slaughter,
he was as a sheep dumb before the shearer; he opened not his mouth, so much as to say,
"`What have I done?`"
or, "`Why is it thus?`"

Now the fruits of the Spirit, in head and members, captain and followers,
Christ and Christians, are one in nature; for as Christ was humble, lowly, meek, patient,
peaceable, under all his sufferings, so are Christians, if Christians indeed;
they render not evil for evil, they desire not an eye for an eye,
nor a tooth for a tooth; revenge of any kind is far from them;
but as patience and forbearance was the life and nature of Christ,
so it is the life and nature of all Christians, as they grow in grace,
and come to the fulness of the stature of Christ.

And by this also, professors of Christianity may prove themselves,
whether they are Christians indeed; for it is the deed that manifesteth all things,
for bad men may have good words; forms may be imitated, but the patience, the meekness,
the forbearance that dwelt in Christ, and may be found in all true Christians,
cannot be imitated.
If any vice hath got head in us, make what profession we will,
the fruit of that vice will be brought forth by us; we shall be proud,
we shall be covetous, we shall be envious: if we are reviled, we shall revile;
if we are smitten, we shall smite; if we are sued at the law causelessly, we shall sue:
whilst it is so, we are in the world`'s nature, its spirit hath the rule over us;
and not the lowly, meek, lamb-like Spirit of Jesus.

The third exhortation or command of Christ was this, "`Love your enemies,
bless them that curse you, do good to them that hate you,
and pray for them which despitefully use you, and persecute you.`"

This also was not only the doctrine, but the life and nature of Christ;
and as it is the life and nature of Christ, so it is the life and nature of Christians,
who are thoroughly leavened with the Spirit of Christ.

No man, having the Spirit of Jesus, and living under the government thereof,
can hate the person of any man;
for by creation we are all the workmanship of God`'s hands;
and all true Christians know that enmity, hatred, cursing, spite, and persecution,
proceed not from men or women as they are the Lord`'s creation,
but as they have lost this image, and thereby become emptied of good,
and filled with all evil: for as an evil spirit comes to have the rule over us,
evil fruits will be brought forth by us.

Could we but see ourselves, did we but observe our own natures,
with the fruits we bring forth in our lives,
we might easily judge of ourselves and others, whether we were converts or not;
whether the Spirit of Christ, or the spirit of this world, had the rule in us,
and over us; for the course of our lives, especially in times of trial,
declares who are led by the meek Spirit of Jesus, and who are not;
who leavened with the leaven of righteousness, and who are not; who lead a sober,
upright, godly life, and who do not; for it is not our words,
but our conversation that manifests what spirit hath rule in us and over us.

For until, by conversion, our natures come to be changed, we cannot love enemies,
having as much enmity against them, as they have against us; we cannot bless them,
we cannot pray for them, we shall be forward to do them hurt,
but far from doing them good.

Come, professors of Christianity,
lay aside your forms that you have long contended about; measure yourselves by this line,
try yourselves by this touchstone:
are you reduced to such a frame of spirit as to "`love your enemies,
bless them that curse you, do good to them that hate you,
and pray for them which despitefully use you, and persecute you?`"
This is a true character of Christianity; this declares us to be Christians indeed.

But if our natures are averse to these things, let our profession be what it will,
we bear not the image of God, we are not the children of our heavenly Father,
"`for he maketh his sun to rise on the evil and on the good,
and sendeth rain on the just and on the unjust:`" and were we but truly converted,
were our natures thoroughly changed, our lives would be conformable;
we should be Christians indeed.

A fourth branch of the life, nature,
and doctrine of Christ was manifested in these words,
"`Take no thought what ye shall eat, what ye shall drink,
nor yet for your body what ye shall put on;--but seek ye first the kingdom of God,
and his righteousness.`"

And what is this kingdom that all true Christians should first seek?
It cannot be any thing above our reach;
it must be that kingdom that Jesus compared to a lost piece of silver;
it must be an acquaintance with that Spirit, and the government thereof, that,
from the beginning, the great God placed in the hearts of men,
to be their instructor in paths of righteousness:
which Spirit alone for some time dwelt in the first Adam,
but was more abundantly manifested in Christ the second Adam,
and so called in scripture the Spirit of Christ; for it always dwelt in him,
and was not only his life, but the life that he gives to all true believers,
for their ransom from under the power of sin and Satan,
and so necessary to be first sought; for until a humble, lowly,
meek lamb-like spirit be raised in us, and come to have the rule over us,
we know not the Lord, nor can depend on his providence:
for the rule and government of this Spirit reduceth every member to an excellent qualification,
and as many as are taught thereby, learn therefrom, in all estates, to be content.

This was the life and nature of Christ:
"`The foxes have holes, and the birds of the air have nests,
but the Son of Man hath not where to lay his head;`" yet was he content;
his thoughts run not out on things pertaining to the body:
it was meat and drink unto him to do his Father`'s will,
and to finish the work that he was sent to do; a work that none before him ever did,
namely, the fulfilling of all righteousness,
by doing the thing that was right in the whole course of his life,
as a precedent to all his followers.

And as many as have found the kingdom of God and his righteousness,
and are come to live under the rule and government of a right Spirit,
have the mind of Christ: though they live in the world,
their thoughts run not out after the world.
A true Christian conversation is to be diligent in our callings,
moderate in our expenses, and content with our estates:
whosoever are reduced to a state of temperance and moderation,
take but little thought what they shall eat, or what they shall drink,
or wherewithal they shall be clothed; they delight in justice, equity, truth,
and faithfulness, and their thoughts are exercised therein, and,
resting on God`'s providence, their honest endeavor is attended with a blessing.

And here professors of Christianity may also prove themselves;
this is a true measuring line, a path that no man can tread,
but such as have the Spirit of Jesus: all ungodly men seek the world first,
I may say first and last; the riches of the world, the honor of the world,
the pleasures of the world, and the praise of the world; what they shall eat,
or what they shall drink, to please their appetites: what they shall put on,
to be accounted great in the world,
and to have the preeminence above and before their fellow creatures;
their thoughts run far more, how they shall be conformable to the fashions of the world,
than how they shall be conformable to the life, nature, and doctrine of Christ;
which is more heathen-like than Christian-like,
and not effected for the most part without much dishonesty.

This is the natural state of the sons and daughters of men,
whilst they continue in a state of degeneracy, aliens to the commonwealth of Israel,
and strangers to that covenant of promise that the Lord made with the house of Jacob.
And to a better state none can come,
but by seeking and finding the kingdom of God and his righteousness,
or the rule and government cf Christ, by his eternal Spirit in their own hearts;
there the seed is sown; there the leaven is laid;
there the pearl of great price is found, but not without digging deep:
for whilst vice is uppermost, virtue is lowermost; whilst sin reigns,
the power of grace is not felt;
the bringing down of the one is the exaltation of the other;
there must be a death unto sin, before there can be a new birth unto righteousness;
and there must be a new birth unto righteousness, and a growth in righteousness,
before we can centre in that content, as to take no thought what we shall eat,
what we shall drink, or wherewithal we shall be clothed.
And so it is every man`'s principal concern, first, to seek the kingdom of God,
and his righteousness; first,
to know the rule and government of a right Spirit in himself; for this qualifies him,
and makes him capable of leading a Christian life,
and of performing Christian duties both to God and man.

The fifth and last branch of the life, nature, and doctrine of Christ,
that I shall here insist upon, is this:
"`All things whatsoever ye would that men should do to you, do ye even so un-to them,
for this is the law and the prophets;`" for this is that the righteous
Lord God requireth from his people in all ages.

This doing is accounted by many zealous professors of Christianity, in our present age,
a moral righteousness, and so but a small part, or rather no part of true godliness;
but rightly considered, all actual righteousness, if it proceed from a right spirit,
is in it self the true righteousness of faith; and that moral, or of no authority,
which is performed from a carnal mind, in imitation of good men`'s practices,
but out of their life and nature: for if the tree be known by its fruits,
fruit manifesteth the nature of the tree.
If our God be, as certainly he is, righteous in all his ways, and just in all his works,
no people on the face of the earth are more God-like, none bear his image more exact,
than such whose conversations are upright, honest, and just;
and nothing can be more just, than to do unto others in all things,
whatsoever we would that they should do unto us.

This is the excellent righteousness;
this exceeds not only the righteousness of the Scribes and Pharisees,
but the righteousness of most professors of Christianity;
for hereby we walk in Christ`'s footsteps, we fulfill both the law and the prophets.

Moses,
from an admiration of the justice and equity that the Lord
required from the sons and daughters of men,
under the administration of the law, uttered these words,
"`What nation is there so great, that hath statutes and judgments so righteous,
as all this law which I set before you:`" And doth the law of the
Spirit of life require less righteousness from Christians,
than that outward law did from the Jews?
I tell you nay, but rather more,
for that more power is given to all true Christians to perform acts of righteousness.

Were the understandings of all who are called Christians
enlightened to see themselves as they are,
or had they but hearts to prove themselves by this Christian rule,
measure themselves by this straight line, weigh themselves in this equal balance,
the following sorts of men and women, with many others,
would no more pass for true Christians, in God`'s account,
than clipped and counterfeit money, when it came to the balance, did in men`'s accounts.

As first, all such who in suits of law, by perverting justice,
or other subtle contrivances, possess themselves of houses, lands, or goods,
that they have no right unto.

Secondly, all such who by violent robbing, or private stealing,
take that which is not their own.

Thirdly, all such who detain the wages of the hireling,
or grind on the necessities of the poor,
by beating down the value of their labor till they cannot live thereby.

Fourthly, all such who in trade or dealing use light weights, short measure,
or any other kind of deceit.

Fifthly, all such who cast their burdens on other men`'s shoulders,
and go free themselves.

Sixthly, all such as either give or take bribes to effect things that are not right.

Seventhly, all such who take wages to serve lord or master,
and are not faithful to their trust.

Eighthly, all such as make contracts, and perform not the same,
or engage themselves by promises, and have no regard to their word.

Ninthly, all such who by evil reports, whisperings, or backbitings,
sow the seeds of strife, create prejudice, or quench charity.

None of these abide in the doctrine of Christ,
none of these do as they would be done unto; though they bear a Christian name,
they are strangers to a Christian life; they live not under Christ`'s government;
they are not swayed by a scepter of righteousness; and so are not God-like.

Godliness and Christianity bear but one image;
and if we would know the nature of godliness, let us consider the nature of ungodliness.
All sober men will grant that the proud, the covetous, the envious, the fraudulent,
the extortioner, the swearer, the liar, etc. are ungodly; and well they may,
for where any such vice gets head, little of the image of God appears;
and if such things make men ungodlike, the contrary, which is humility, meekness,
moderation, sobriety, truth, equity, and faithfulness, must needs make them godly.

To become ungodly is an easy thing; for if our backs are turned on God,
we have nothing in our eye but the world, and the vanities thereof,
promising us such content, that little else is minded.

But the great difficulty is to become godly again; though thousands are employed therein,
little shew doth appear; for in the eyes of degenerated men,
there is no loveliness in that path; and therefore the great query is,
By what way may the proud become humble, the wild become sober,
the covetous become content, the fraudulent become just, the intemperate become moderate,
the incontinent become chaste, the unfaithful become faithful?
I know many will say, By hearing good ministers, reading good books,
and conferring with good men.
But these things have been tried, and that for several years, by many,
yet no such change hath been wrought thereby.

If advice, exhortation, or counsel, would effect this great work,
we need not go any further than the heavenly sayings of Christ, in the aforesaid fifth,
sixth, and seventh chapters of Matthew;
for if we could hear all the ministers in the world,
read all the good books in the world, and confer with all the good men in the world,
we could not have better advice, counsel,
and exhortations than are contained in those three chapters.

By hearing good ministers, reading good books, and conferring with good men,
we may be convicted, but not thoroughly converted: for as virtue hath a spring,
so vice hath a root, that words will not reach.
The strength of sin is the growth of that seed that the wicked one hath
sown in the inward parts of the sons and daughters of men;
and forasmuch as the cause is within,
it is impossible it should be wholly removed by things without;
but as the cause is within, so the cure must be within, by mortifying the body of sin,
or bringing down the strength thereof, which is thus effected:

There is no unrighteous thing done,
but there is an inward motion before there is any outward action; and,
by that light which enlightens every man that cometh into the world,
if our eyes are inward, we may see those motions: and the way to mortify the body of sin,
is to deny and turn from every such motion in the rising thereof,
and so to crush the cockatrice in the shell;
for in their rising they are weak and powerless, and may be easily turned back.
And if we do not suppress vice in the risings thereof, it will continue our lord;
but by every such denial,
we bring down that which would arise and reign in us and over us, whether it be pride,
covetousness, envy, falsehood, or any other vice whatever;
for the more denials are given to vice, the fewer assaults it will make;
the stronger the opposition, the weaker the attempt:
as yielding gives vice ground to grow from a seed to a body,
denials bring it down from a body to a seed;
so that though something there of may abide in us, it doth not reign over us;
but is in subjection to the sceptre of righteousness, or rule of a right spirit.

The axe is never laid to the root of the tree, till a reformation begins within;
the life of righteousness stands in the mortification of sin, which is an inward work.
The spirit of this world must be brought down,
before the Spirit of the Lord can be exalted in us; but as a right Spirit comes to reign,
we have as many motives to acts of righteousness,
as ever we had to acts of unrighteousness,
and as we give ourselves in obedience thereunto, grace grows in us, and we grow in grace:
it is a change in government that changeth our natures,
and makes us to become new creatures.

By this we come to have the blessing as well as the birth-right;
for the blessing is not to the exalted mind, but to the poor in spirit, to the merciful,
to the pure in heart, who hunger and thirst, not after riches and honor,
but after righteousness; and all that hunger and thirst after it,
will endeavor to satisfy their souls with an increase of it.

Now a talent is not improved by lying hid in a napkin; if we would have more grace,
we must exercise the measure we have attained unto;
we must live in the continual practice of right things; we must keep in lowliness,
meekness, temperance, patience, and other virtues; we must be just in our dealings,
as well in the smallest concern, as such as are more weighty;
for a small matter turns the balance; and if that small matter be wanting,
things are not just, we do not even as we would be done by.

And this just dealing, as righteousness comes to reign, will be no hard thing,
for as we accustom ourselves thereunto, it will be uppermost;
it will be as a diligent handmaid, ready to offer her service;
and every act of righteousness performed from the motives of a right spirit,
hath its immediate reward; which is not only an answer of peace,
but joy in the Holy Ghost.

The way of life is the way of pleasantness, all her paths are peace;
nothing makes it to seem difficult, but the averseness of our natures,
when once corrupted, thereunto; but as our natures come to be changed, we shall,
from a sensible experience, say with David, "`Thy commandment is exceeding broad.`"

I cannot recommend myself, nor any other, after we are awakened unto righteousness,
to any better way for the reforming of our lives,
than to turn in our eye to the gift of God in ourselves:
that by his candle we may see the rising of vice, and so deny it; that the contrary,
which is grace and truth, may rise and grow in us; for that is our help,
that is our strength, and that is our defense.

Words, whether retained in our memories, or written in our books,
are but weak instruments for this work, because the old man must be put off,
which is an inward work; and how is a sorry guest put off,
or a man that urgeth for what we are not willing to grant, but by denying him,
and turning from him?

Should we enter into reasoning with any motions of sin,
it is much if we are not overcome thereby, for that it is the nature of sin,
not to turn back at a small denial,
especially if it be a sin that hath prevailed over us before;
but in turning therefrom we give it the repulse; if it be not hearkened unto,
it goes back.

And as the old man is put off, the new man is put on; as vice is denied,
virtue is embraced, and this new man makes us new creatures;
that which is created after God renews in us the image of God;
and bearing that image in holiness and righteousness,
our conversations will declare us to be Christians indeed.

But if this old man with his deeds of darkness be not put off,
the new man that is created after God`'s image in righteousness and true holiness,
will not be put on; and though we have been awakened unto righteousness,
we shall fall asleep again, some in one form and some in another,
feeding on words without any sense of power or life;
and this second sleep appears to be dead sleep;
for that though we may hear much spoken against pride, covetousness, envy,
etc. we are not as much as touched therewith, but live in the open shew thereof.

Did the sons and daughters of men who are called Christians,
make it their concern to be Christians indeed by
mortifying in themselves the spirit of this world,
which is the original of all vice, they would be not only a happy, but a lovely people;
for by mortifying the body of sin, oppression would cease,
all wrongs and injuries would determine and be at an end;
love would spring both to God and man; grace would grow; humility, meekness, moderation,
and all other virtues would shew themselves;
they would be another manner of people in their conversations;
their words and their works would be just, upright, and honest;
they would confide in one another without any scruple or doubt.
What is more lovely than to be at all times, and on all occasions, just, upright, honest,
and faithful, doing to all men in all things whatsoever,
even as we would that they should do unto us?
A living under the rule and government of a right spirit, qualifies us,
and makes us capable of performing every Christian duty:
we shall love the Lord our God with all our hearts, and our neighbors as ourselves;
which is the sum of all godliness, and the true character of Christianity.
