== Considerations Grounded On The Foregoing Discourse

Man was made, as many will acknowledge, to glorify God, and to do his will on earth:
and that man might be capable of serving his Creator according to his will,
God gave him a measure of his good Spirit for an instructor; so that there was in man,
as he was first created, much of God, much humility and meekness,
much truth and faithfulness, much heavenly wisdom and understanding.

This eternal Spirit was to be man`'s head and leader, man`'s guide and instructor,
in the paths of righteousness.
On this Spirit man was to fix his eye; to this Spirit man was to incline his ear;
by this Spirit man was to be governed; and so following this guide, this leader,
and this instructor, man would have been capable of governing himself,
and the creation over which he was made lord, according to the will of God.

Did mankind live under the government of this eternal Spirit,
we should all bear the image of God; we should be all godly, humble, lowly, meek,
merciful, patient, peaceable, upright, and faithful; right in all our ways,
and just in all our works.

But man, not keeping with this guide, disobeys the command of his Maker;
and by yielding himself servant to another master, another spirit enters,
as contrary in nature as darkness is to light:
and as many as follow this leader serve not the God of heaven, but the god of this world:
for every man is a servant to whom he obeys.

Now we, being all the offspring of Adam in his fallen state, bear his likeness;
we have all in ourselves, good and evil, a seed of grace, and a seed of sin,
called in scripture, light and darkness, flesh and spirit, the old man and new man,
according to the growth of the seeds in us,
and the dominion that they come to have over us;
for as there is a difference between a seed and an herb, a plant and a tree,
a child and a man; so there is a difference in grace, and also in sin:
according to its growth in us, so is the strength thereof felt by us,
and the names given in scripture are answerable thereto.

For though we have all a seed of sin in us, we are not over mastered therewith,
nor captivated thereby, as soon as we are born:
it must have a time to spring and grow in us, before it comes to have dominion over us.
And I may say the same of the seed of grace, for it is also of a growing kind;
otherwise the kingdom of heaven, or government of Christ in the hearts of his people,
would not have been compared to the seed of mustard, which,
though it be but small when it is sown, yet through the springing and growth thereof,
comes to be of a high Stature.

We may find many in the world who are notoriously wicked,
and much more wicked would they appear, were they not limited by an outward law:
these were not so born; it is the growth of sin, and the dominion,
that it comes to have over men, that makes them notoriously wicked; for the seed of sin,
as it comes to full growth in any of the sons and daughters of men,
converts them into its own nature,
by which they come to be habitually active in wickedness.

This was the devil`'s aim in Adam`'s fall, but his design being not then fully effected,
he hath followed in all ages of the world, and at this day doth follow,
the sons and daughters of men,
putting in their minds evil motions attended with various temptations,
displaying false colors, and putting a more beautiful gloss on things forbidden,
than fallen men can see in paths of righteousness.
And all his evil motions, temptations, baits, snares, lures, and false colors,
are to effect his first design, that we being taken therewith, and led away thereby,
might forget God, and cause him to take his Holy Spirit from us; for till then,
the god of this world can call no man his own; we may be his captives,
but he hath not the whole dominion over us.

In our present age, light within, a law within, Spirit within, Christ within,
is the scoffing of some, and little regarded by many: but whether they know it or not,
I must tell them,
they scoff and slight the chiefest treasure that
ever the soul of any man was possessed of;
they slight the talent that God hath given to every man to improve,
in order to their rising from their fall, and returning to their native country,
to live under the government of the eternal Spirit.
Whosoever is without Spirit and light within, is without God in the world.
Take away this treasure, and we shall have nothing in us that is good:
we shall be left quite graceless.

We read of Jacob and Esau, who were lively figures of these two seeds in man,
how they struggled whilst they were in the womb of Rebecca.

And as there was a struggling between the seed of two nations in the womb of Rebecca,
so there is a struggling between the seed of two kingdoms in every man,
which shall rise to rule in us, and to have the whole dominion over us.

As we are born into the world, we are all innocent; though we have a seed of sin in us,
we are not actual sinners, until we yield to some sinful motion proceeding therefrom:
which the devil knows, though many are of another persuasion.
And that the seed which he hath sown may spring and grow,
that an evil spirit may come to have the rule in us, he begins to struggle betimes,
before we well know the right hand from the left:
and where vice is not kept down by careful parents, or guardians, it quickly gets head;
and such may say, as many do, "`That there is no good thing in us,`"

For, through the speedy growth of that which is evil,
they never have any acquaintance with that which is good, except inward rebukes,
which few will acknowledge to be of God.
For as weeds left to grow in a garden overshadow and keep down herbs,
so that they cannot grow; so doth vice suppress virtue,
and make God`'s creation such strangers to their Creator, that though in him they live,
move, and have their being, yet are they without sense or feeling of his presence.

And as all evil motions that lead unto sin, all baits, snares, and lures,
that we meet with in the course of our lives,
are the strugglings and strivings of the evil seed;
so all calls that we find in ourselves for justice, equity, honesty, truth,
and faithfulness, with all inward checks, rebukes, and convictions,
are the strugglings and strivings of the good seed;
for if these things are hearkened unto, obeyed, followed after, and lived in,
they keep down the growth of vice; so that though we have a root of sin in us,
it remains powerless; it doth not rise and come to reign over us.

In which suppressing of vice, in order to the growth of virtue,
parents and guardians ought to be much concerned;
for as the wicked one takes the advantage of our childhood, to make us commit evil,
before we have any acquaintance with that which is good; parents and guardians,
like faithful weeders, should eye, suppress, keep down,
and use all endeavors to root out every vice as soon as it appears, till grace grows,
and a right spirit comes to reign in them, and have the rule over them.

But this is our present state:
as Esau by his struggling came to be the first-born in days past; so iniquity,
through the early rising of the subtle serpent, is the first-born still.
And though most parents, in the Christian world, are careful to provide weeders betimes,
almost as soon as a child is born, yet few weeds do they root up;
and many parents none at all; by which great neglect, most children come to be wild,
stubborn, self-willed, disobedient to parents, and very ungodly in their lives.
But the ground of all ungodliness is the growth of that seed which the wicked one sowed.
And how may vice be brought down when it is come to a head?
Not by parents, not by guardians, not by sureties, and I may say, not by preachers:
but as it was Jacob that supplanted Esau, so it must be grace that must supplant sin.
We see, notwithstanding all preaching, more pride and haughtiness,
than humility and meekness; more fraudulent dealings, and contentious practices,
than self-denial; more seeking the world, and the vanities thereof,
than the kingdom of heaven, and the righteousness thereof.
And thus it will be whilst the firstborn is uppermost.

And if we would have the firstborn supplanted;
if we would have that which strives to deprive us of life, light, and grace,
and all goodness, made powerless; if we would have that suppressed,
which continually labors to make us servants to sin, and bond-slaves to Satan;
if we would see the death of that which makes us
incapable of glorifying God in our lives;
if we would be, as the primitive Christians were, delivered from the power of darkness,
and translated into the kingdom of the dear Son of God,
to live under the government of his eternal Spirit, which was man`'s first state;
let us consider, how that which hinders came to rise,
and by what means it may be brought down.

I have said, and say again, that it is not the indwelling,
but the growth of an evil seed, that makes the sons and daughters of men proud, haughty,
high-minded, envious, cruel, merciless, fraudulent, and ungodly;
darkening their understandings,
and making them strangers to the gift of God in themselves.
And the growth of this evil seed stands in our often
yielding to such evil motions as proceed therefrom,
and that the subtle serpent knows; and we may know it also,
from the manifold temptations we have thereunto,
especially where he finds them to be effectual.

Whoever yielded to any evil motion, committing sin, and taking pleasure therein,
that hath not been tempted again to the same thing?
Or who is there that doth not know, that the oftener we yield to any temptation,
the stronger our temptations are, and the harder to be denied?
And by every yielding, this sin riseth, and comes to have more power over us.

And if it be by our yielding to evil motions that the evil spirit riseth,
and comes to have power over us,
it must be by denying evil motions that he must be supplanted, and made powerless in us.

Whosoever will be a follower of Christ, must first learn to deny himself.
We must turn from whatsoever the eternal light in our own hearts shews us to be selfish,
though it may seem never so much to our disadvantage; and by denying ourselves,
we shall abundantly deny the author of all evil motions.

Pride, pleasure, and unrighteous gain, are baits that have caught many;
all which with many other things, we must deny, and turn from,
if we will be followers of Christ in a righteous life:
and by such denials we shall find the root of iniquity wither, and grace grow;
sinful motions will diminish, and heavenly desires increase;
the small seed will become the tallest of herbs;
and the lump come to be one in nature with the leaven.

But this denial must be whilst the cockatrice is yet in the shell;
whilst sin is in the motion, before it comes to action;
for sinful motions may be turned from, but sinful actions are past recall.
And what can shew us the rising of evil motions?
Preachers cannot; books cannot;
nothing that is without can effectually shew us what is within;
it must be an inward light; it must be the candle of the Lord, the eternal Spirit,
that was in the beginning given unto man for an instructor.

There were in the creation good men, faithful men, self-denying men,
when there were no preachers, nor books, that we read of:
and who was their teacher but the eternal Spirit?
What guide had they but the light of righteousness in their own hearts?
And did our present preachers make it their concern
to turn people`'s minds to eye this inward guide,
and to become faithful followers thereof, we should have more good men, faithful men,
and self-denying men, than can now be found.

Men or angels could not give better advice to a people,
that was turned to this inward light, than Paul gave to the Galatians,
when he exhorted them to "`Walk in the Spirit;`"
for if we are not guided by a right spirit,
we can never lead a righteous life.

As the seed of sin grows and waxeth strong in us by our yielding to evil motions,
so the seed of grace grows and waxeth strong in us by the denying of evil motions:
the putting off of the old man, is the putting on of the new;
and it is the new man that makes any of us to be new creatures, and to bring forth,
in the course of our lives, a new and heavenly conversation.

If we do not come to a denial of evil motions,
and to live in a continual exercise thereof,
though we hear preachers all the days of our lives,
we shall be but as the door on the hinges, or as Israel in the wilderness, often moving;
yet as short of a righteous life,
as they that then came out of Egypt were of having
peaceable possessions in the promised land.

We cannot come to a righteous life, until our lights shine with such brightness,
that we can see the rising of all evil motions at a distance:
for as grace comes to be uppermost, the root of iniquity will be lowermost;
as the one comes to be before our faces, the other will be behind our backs.

Our conversation is not in heaven, till truth comes to be in all our words,
equity in all our deeds, and faithfulness in all our promises;
this makes the sons and daughters of men a holy nation, and a peculiar people;
this makes such as were Heathens to be true Christians;
and such as were the vilest of sinners, worthy of the honorable name of saints.

Whence come pride and haughtiness, contention and strife, fraud and deceit,
oppression and cruelty, but from the author of all wickedness: Where the flesh,
with the affections thereof, is crucified, such things are not to be found; and,
let us pretend to what religion we will, whilst such things are practised,
we keep alive what ought to be mortified.

Where an evil spirit is uppermost, men know no limit; their ears, eyes, tongues, hands,
and feet, are at liberty to hear evil reports, behold vanity, speak proudly, rashly,
unadvisedly, and deceitfully, to do violence, take bribes, and go where they list.

But where a right spirit rules, every member of the body is under a limit;
the ear is turned from fables, and the eye from beholding vanity: they cannot,
as too many do, cover, dissemble, and lie, to accomplish self-ends:
vain communication is not allowed to come out of their mouths;
their hands are limited from taking bribes, using of violence, or doing any wrong;
the paths of rioters they cannot walk in, but are lovers of righteousness,
and haters of iniquity in themselves and others.
And to this estate we might all come,
by denying such motions as the light of righteousness
in our own hearts manifests to be evil.

And now my advice to all professors of Christianity is,
that instead of contending about forms of godliness,
they take heed to that in themselves which leads to godliness;
instead of searching the scriptures for a right form,
they would labor to live under the government of a right spirit;
for such are delivered from the power of darkness, and return to Sion the city of God,
and to the New Jerusalem, where God is known and truly worshipped.

One thing more I would have the reader to consider, and that is this:
Though every man that cometh into the world is attended with two spirits,
yet can he have but one Lord, and he is Lord that hath the whole rule over thee.

The right of government, in all men, belongs to the eternal Spirit,
that was with the Father before the world began,
called in scripture the Spirit of Christ; for in Jesus, the second Adam,
no other spirit dwelt.
He was not attended with two spirits, as the offspring of fallen Adam are:
he had not in himself light and darkness, good and evil, a seed of grace,
and a seed of sin: but he was, as the Scripture saith, "`Full of grace,
and full of truth.`"
In him was life, even the life that the first Adam lost, a spring of righteousness;
and this life he retained, though his temptations far exceeded those of Eve,
and so did keep out the evil spirit, which is the author of all wickedness.
Though he lived many years on earth, and met with many provocations,
he was in the whole course of his life, humble, lowly, meek, merciful, patient,
peaceable, just, and faithful; and therein fulfilled all righteousness,
and so did the will of God on earth.

And the seed of grace in every man, is one in nature with the fulness that dwelt in him;
and as this seed springs in any of us, and grows to strength and stature,
it makes us conformable to his image.
The more grace any man hath, the more humble, meek, and merciful he is;
the more light any of us have,
the greater discovery it makes of what is amiss in ourselves and others`';
the more truth dwells in us, the less fraud and deceit is wrought by us.

And as we walk in the light, we shall grow in grace, and "`add to our faith virtue,
knowledge, temperance: patience, godliness, brotherly kindness, and charity;`" by which,
as Peter said,
"`an entrance will be ministered unto us abundantly
into the everlasting kingdom of Christ.`"
A right spirit will come to be exalted in us,
and to have the alone rule and government over us;
and under the government of a right spirit, we shall bring forth a right conversation,
acceptable in the sight of God.

Now the prince of darkness, being an enemy to all righteousness,
useth all endeavors to blind the eyes of our understanding,
and to keep us strangers to this righteous seed,
which is the spring of all grace and virtue, that he may draw us away from God,
and all godliness: and as such as walk in the light of the Lord add virtue to virtue,
until they are filled with righteousness,
so such as follow the leadings of an evil spirit, add vice to vice,
until they come to be filled with wickedness; and all such have likewise but one lord;
the prince of the power of darkness hath the whole rule over them.
And these two states are called in Scripture _life_ and _death._

Every man, as he cometh into the world, hath, as I may say,
life and salvation before him, death and destruction behind him,
and both at a distance from him:
he hath also a good spirit to conduct him in the way of life and salvation,
and an evil spirit waits to lead him in paths of death and destruction;
and most men are strangers to both, although they be in them.
And the preaching of the gospel was, and ought still to be,
for the opening of such blind eyes,
to see the working of these two spirits in themselves, and the leadings thereof,
that they might turn from the evil, and become followers of that which is good, that he,
whose right it is, might come to have the rule in them and over them.

And certain I am, that though many are ignorant of these things,
many may be found that have some sight, some sense,
and some feeling of the eternal Spirit of Jesus:
they have the knowledge of something in themselves
that calls for just weights and an equal balance,
for doing unto all men as they would be done by, for truth in their words,
and faithfulness in their promises; so that did they keep to this,
they would follow a right guide, and the seed of grace would grow,
truth and faithfulness would grow: knowledge, temperance, patience, brotherly-kindness,
and charity, would grow; and we should find in ourselves,
that an entrance into the kingdom of Christ would be abundantly administered.

But whilst the evil spirit remains unmortified, self stands in our way,
and to accomplish self-ends, an equal balance is not kept, justice is not done,
equity is not performed, promises are not kept, undertakings are not faithfully managed,
the fashions and customs of this sinful world are not forsaken;
and that hinders the growth of the righteous seed;
for as there was no bringing down of the Canaanites
whilst there was an accursed thing in the camp;
so there is no bringing down the strength of sin
whilst we have more regard to self than a Saviour;
and that which manifests self is light, by it we see to what every evil motion doth lead,
and walking in the light, we walk in the way of God`'s salvation.

But some may say of this eternal life, as wicked men and sons of Belial said of Saul,
the chosen of the Lord; "`How shall this man save us?`"
What can the taking heed to this light advantage us?
We find in ourselves rebukes for sin,
but we find nothing in ourselves to save us from sin.

To all such I have this to say,
Christ was given to the Gentiles for a light and for a leader.
Whilst we are in the nature of the Gentiles, whilst we walk after the flesh,
whilst we follow evil motions, we are departed from God,
we are aliens from the commonwealth of Israel,
and are strangers to the new covenant that God made with the house of Jacob;
and in that state we cannot know Christ the Saviour of the world,
any otherwise than as a reprover; but those reproofs, being reproofs of instruction,
are the way to life, even to that life that the first Adam through transgression lost.

For if at those reproofs we turn from such things as we are reproved, for,
whether it be idle communication, intemperate living, unjust dealing, pride, passion,
or any other vice, that the evil spirit of this world leads unto;
and follow after righteousness, doing such things as are just, upright, honest,
and of good report; rebukes will cease, and our reprover will become our leader;
that which was behind our backs, will be before our faces,
and that which would have led us, will pursue us, as Pharaoh pursued Israel,
to bring us back to our old manner of living again,
and _then_ we shall find Christ to be our Saviour.
As many as followed Saul saw how he saved them from their outward enemies;
and all that come to be followers of the eternal Spirit of Jesus
do see how he saves them from spiritual enemies.

Whilst we follow motions of sin, we follow a wrong guide,
and in that path we may know the prevailing power of sin,
but can never know the restraining power of grace.
It is to as many as receive Christ that he gives power; and none receive him,
but such as turn from their iniquities at his reproof, and confide in him for a Saviour:
such truly believe in his name.

I grant, that the shining of an inward light,
which is the first manifestation of Christ to the sons and daughters of men,
seems at first small and powerless; and so do our first motions to sin:
but follow such sinful motions as far as they will lead,
and we shall find them powerful enough.
May not many be found at this day, even amongst us who are called Christians,
so captivated under the power of sin, that a bond-slave, who is held in chains of iron,
can easier break his bonds, arise, depart, and return unto his native country,
than they can cease from iniquity, rise from their fall, and lead a sober, righteous,
godly life.

And if the seed of sin comes, by our following the motions thereof,
to have such power over us, why may not the seed of grace, if we return whereunto,
and become followers thereof, have as much power over us?

Undoubtedly John, who had travelled from death to life,
and was an eye-witness of things as they were in the beginning,
felt in himself such a power, when he said,
"`Whosoever is born of God doth not commit sin, for his seed remaineth in him,
and he cannot sin.`"
And many living witnesses may be found at this day, who can say,
from a sensible experience, That where this righteous seed is risen,
and comes to have dominion, it is so powerful and restraining,
that they cannot be unjust in their dealings, nor unfaithful in their promises;
they cannot tell an untruth, though never so much to their outward advantage;
they cannot be intemperate,
wasting the good creatures that God hath given for their nourishment,
by excessive eating and drinking; they cannot oppress the poor, the widow,
and fatherless, nor take by violence that which they have no right unto:
the small seed in them is become the tallest of herbs, and hath as much power over them,
as sin hath over such who dwell therein.

These are, as the Colossians were, delivered from the power of darkness; these have,
as the Philippians had, their conversation in heaven; these glorify God in their lives,
and so answer the end of their creation.

Much preaching hath made many godly talkers; but it is grace in the heart,
and truth in our inward parts, that makes godly livers.
And to a fulness of this heavenly treasure none of us can attain,
but by denying such motions as the eternal light of righteousness, in our inward parts,
shews us to be unjust and dishonest; for in denying the evil, we choose the good;
and as the growth of sin stands in our ill-doing,
so the growth of grace stands in our well-doing.

Our ancestors have told us,
that there was more honesty and plain dealing amongst men in ages past,
when there was less preaching, than can be found amongst men now.
And their saying I can easily believe; knowing that it is a true self-denial,
and not the hearing of preachers, that must mortify sin, change our natures,
and make us new creatures; which is the ground of all honesty and plain dealing.

And of this true self-denial,
I am apt to think we have much less than former generations had; for we see,
though preaching abounds, pride, covetous practices, with many other vices, super-abound:
and the reason to me is this, conformity to outward forms of worship,
being more taking with people than the strait gate and narrow way of self-denial,
hath in our present age gotten the name of religion, Christianity, and true godliness;
insomuch, that should a man add to his faith virtue, and all other graces,
by which an entrance into the everlasting kingdom of Christ is abundantly ministered,
if there be not withal a conformity to some outward way of worship,
he shall not pass for a godly man.
Nay, though his conversation be never so heavenly; though he be humble, lowly, meek,
patient, peaceable, though truth be in all his words,
equity and faithfulness in all his deeds; though he visits the fatherless and the widow,
and keeps himself unspotted from the world;
if he be not in the exercise of some outward form of godliness,
he shall not be counted religious, nor hardly a Christian.^
footnote:[But it is not hereby intended to discourage the assembling
of ourselves together for the public worship of Almighty God,
agreeable to the advice of the Apostle, Heb. 10:25.]

Conformity in every sect, opinion, or persuasion,
is become the character of a religious man, and the only band of unity and brotherhood;
if this fail, there soon comes an estrangedness:
and so there is much pressing into conformities,
but little minding the mortification of sin, in order to a life of righteousness.
But let our zeal for conformity be never so much,
it is he that ordereth his conversation aright, that shall see the salvation of God.

The conformity that the living Lord requires,
is a conformity to the image of Christ in the course of our lives,
to be holy as he was holy; without which we cannot be, as the primitive Christians were,
of the household of God: we are not come to the New Jerusalem,
and so cannot be fellow citizens with saints.
Though we bear the primitive Christians`' name,
we are not in the primitive Christians`' nature; the first-born is not so brought down,
as to have a right spirit alone to rule in us, and to have the dominion over us.

If the sayings contained in this book seem strange unto the reader,
it is because the reader is a stranger to the primitive Christians`' life:
if He who was their head and leader, were become ours; had we fellowship with them,
as they had with Christ; we should have an echo in ourselves,
answering to what is here said: our hearts would say, "`It is so.`"

And the way to come to their righteous life, is to walk in the light,
denying and turning from the least thing that it shall manifest unto us to be evil.
At the beginning of our journey, it will seem a strait and narrow way;
but after we have travelled on a while, we shall run therein with great delight.
For the kingdom of heaven,
or Christ`'s government by his eternal Spirit in the hearts of his people,
doth not consist of righteousness alone:
the righteousness that proceeds from a right spirit, is accompanied with peace and joy:
as ill-doing is attended with trouble and sorrow,
well-doing is attended with peace and joy.
All the pleasures of wickedness, that the whole world affords,
are not to be compared to the joys of a righteous life.
Every evil motion we deny, in obedience unto Christ,
affordeth a superior joy to that which a warrior hath in battle,
when his enemy flies before him.

The Jews counted themselves more holy than the Gentiles, though both made of one blood;
and as both were the offspring of Adam, both had in themselves good and evil.
But to the Jews the Lord gave laws, statutes, and judgments, for a rule of righteousness;
and they, conforming thereunto in worship and outward services, counted themselves,
as we who are called Christians do, holier than the Heathen.

But this was a selfish persuasion in the Jews,
and no better in us who are called Christians,
whilst we continue in a state of degeneration: for no outward conformity,
without inward sanctification, can make any man holy; and no man is sanctified,
till sin is mortified.

When the Heathens, through the preaching of the gospel, turned from their darkness,
and came to be followers of the eternal Spirit, thereby mortifying the strength of sin,
they were more holy than many of the Jews, and called by the apostle Saints;
which was more suitable than the name of Christians;
was was at first given in derision to the followers
of Christ by the unconverted Heathens at Antioch,
and but once sincerely mentioned in all the Scripture.
But the name saints is peculiar to all truly sanctified souls.

As circumcision gave many the name of Jews,
so the imitating of John`'s baptism hath given many the name of Christians;
but nothing can give Jew or Christian the name of a saint, in truth,
but a heart made pure, single, upright, and honest, through the mortification of sin,
called in Scripture,
"`The baptism of the Holy Ghost;`" for that is effected not by any outward means,
but by our walking after the Holy Ghost.
Till this is wrought, though we have a Christian name,
we cannot bring forth a heavenly conversation, and so the name profiteth little.

For we who are called Christians, as we are born into the world,
have in ourselves a seed of sin as well as others;
and for want of faithful weeders to root up vice as it appears,
iniquity grows to that height,
that nothing less than the powerful Spirit of Christ can bring it down:
and from such who remain strangers to the working of this Spirit a cry hath gone forth,
"`That there is no freedom from sin on this side the grave:`" but the Colossians,
who were delivered from the power of darkness, knew better things; and so should we,
if we did turn from iniquity, acquaint ourselves with their guide,
and walk in newness of life.

A numberless number at this day bear the Christian name, because it is easily obtained:
nothing is required at the receiving of it but promises.
But small is the number of saints, because no man can be a saint,
but by a performance of those promises; and that no man can do,
until he turn to that in himself which manifests the works of the devil; and,
on discovery thereof, deny, turn from, and quite forsake them.
By taking this way, and using this means, sin will certainly be mortified,
the soul sanctified, and such as were sinners will come to be saints.

But as nothing discouraged the camp of Israel from going up to possess the land of Canaan,
more than the report that ten spies gave of the strength of the people that dwelt therein;
so nothing discourageth awakened souls from pressing after a life of righteousness,
more than the report that hath been given by professors
of godliness concerning the strength of sin,
that it could not be overcome:
when they that so reported never made trial in the way of God`'s salvation.

All the spies spake well of the land, as all sorts of people now do of a sober,
righteous, godly life and conversation: all will commend humility, meekness, moderation,
temperance, patience, chastity, and, above all, plain, upright, honest, just dealings,
though they do not practise them; and nothing hinders but this,
the evil spirit of this world is uppermost, and few endeavor, in God`'s way,
to bring it down.

Had the camp of Israel made them a captain, and gone back into Egypt,
they could never have subdued the Canaanites:
and whilst we allow our selves to live in sin, it is impossible we should subdue it,
for we strengthen what we should mortify.
The Canaanites were made weak by war, and so must the strength of sin;
with this difference, theirs was an actual war, and ours must be defensive.
When, by the candle of the Lord that shines in our souls, we see an aspiring thought,
a lustful desire, a covetous inclination, or any other evil motion;
if we stand on our guard, and deny it entrance into our affection, it will retreat,
and after many attempts, being still put back, will hardly attempt any more; at most,
the motions thereof will be but weak.

Whilst there was an accursed thing in the camp, the enemy prevailed,
and Israel retreated: and so it is at this day; if we cover, if we hide,
if we justify what our own hearts condemn, the evil prevails, and the good retreats.

Let us but accustom ourselves to true denials, and the strength of sin, will,
from day to day, be weakened; and as Joshua and Caleb said, the Lord will be with us;
his grace will be in our hearts, and his fear before our eyes; truth, equity,
and honesty, will be uppermost: and then it will be as easy to lead a sober, righteous,
godly life, as ever it was to live a loose and ungodly life:
for though something of sin may remain in us,
as some of the Canaanites remained in the good land, it will be powerless, as they were;
and all our members that were servants to sin, will become servants to righteousness,
as it is written, "`The elder shall serve the younger.`"

But if we rebel against the Lord, by joining with motions of sin,
as many who are called Christians, as well as Heathens, do,
this war will be over before it is begun; that which is uppermost, will continue so;
and as we live, so we shall die, receiving wages, not according to our _words,_ but,
according to our _works:_ and then we shall know that a Christian name,
without a Christian conversation, will stand us in little stead;
for it is not he that is overcome, but he that overcometh,
that the second death shall not hurt.
